### ISSUE TITLE
bug: Can't login to youtube music

### ISSUE THREAD

**Issue by Proggie** [webcatalog/webcatalog-legacy#1007]
# Bug Report
**Specifications:**
- WebCatalog Version v24.3.0
- Youtube Music App Version v10.0.0-alpha.6. Powered by WebCatalog.
  Electron Version: 10.1.1
  Node Version: 12.16.3
  Chromium Version: 85.0.4183.93
- macOS 10.15.6 (19G2021):

**Description:**
Created an app for Youtube Music streaming service, but can't log in. It just refreshes the page instead of asking for login information.

**Steps to Reproduce:**
Go to music.youtube.com
Click on Login

**Comment by quanglam2807** [comment]
Thank you for reporting this! It'll be fixed shortly.
