### ISSUE TITLE
bug: Cmd+ to zoom in doesn't work with non-US keyboard

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1015]
This is the layout our keyboards use (we both use laptops though): https://www.apple.com/es/shop/product/MLA22Y/A/magic-keyboard-espa%C3%B1ol

_Originally posted by @hacknug in https://github.com/atomery/singlebox/pull/257#issuecomment-692063028_

**Comment by quanglam2807** [comment]
@hacknug Was it fixed?

**Comment by hacknug** [comment]
@quanglam2807 yes! Thank you ❤️

**Comment by quanglam2807** [comment]
That's awesome! Thanks for testing!
