### ISSUE TITLE
bug: Dark Reader doesn't seem to work as well as the browser extension

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1024]
Try it with Google Analytics as an example.

I wonder if you have "Mode" = "Dynamic" set in the config?

**Comment by quanglam2807** [comment]
Thank you for reporting, @marcusquinn. This bug is actually related to CORs (see #993). I've managed to fix it by using deeper-level APIs. Hopefully, it's completely fixed this time.

**Comment by marcusquinn** [comment]
Awesome - looks like that fixed it - brilliant work!!
