### ISSUE TITLE
Application name cannot contain Ampersand

### ISSUE THREAD

**Issue by davosian** [webcatalog/webcatalog-legacy#103]
When using & (ampersand) in the application name, WebCatalog will not be able to launch the application on macOS.

**Comment by quanglam2807** [comment]
@davosian Thanks for reporting. What engine are you using?

**Comment by davosian** [comment]
Juli
Am 26. Aug. 2018, 05:11 +0200 schrieb Quang Lam <notifications@github.com>:

**Comment by quanglam2807** [comment]
I just checked. macOS doesn't allow users to have ampersand in file name. I'll try to add a notification to clarify this in future update.

**Comment by davosian** [comment]
Makes sense, thank you!
Am 26. Aug. 2018, 09:56 +0200 schrieb Quang Lam <notifications@github.com>:
