### ISSUE TITLE
feature: Smaller sidebar icons

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1030]
# Feature Request
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
As I run multiple applications within WebCatalog, the sidebar is filled up to the point that I get presented with a scrollbar. I would prefer to have the ability to use smaller sized icons, to make the sidebar smaller, thus preventing to have a scrollbar.

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/149
