### ISSUE TITLE
feature: Automatic account specific icons

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1031]
# Feature Request
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
Some accounts like those from Google show your own selected avatar when logged in. Would be nice if those could be used as overlay on the standard workspace icon. Or even used instead of the standard workspace icon, optionally keeping the standard icon as overlay.

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/198
