### ISSUE TITLE
feature: Show app name below/next to icon

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1032]
# Feature Request
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
Together with #1030 to have smaller icons, I would prefer to have the app name mentioned next to the icon. Although most icons are very easy to distinguish, it does help me with the large list of apps listed to select the app I was looking for.

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/149
