### ISSUE TITLE
bug: Facebook Messenger unable to sign in with 2FA enabled

### ISSUE THREAD

**Issue by insanityinside** [webcatalog/webcatalog-legacy#1035]
# Bug Report
**Specifications:**
- App Version: 9.8.0
- WebCatalog version 24.7.0.0
- OS (macOS, Windows, Linux): Windows 10 x64 1909

**Description:**
Attempting to sign in to a Messenger account via the app to a Facebook account with 2FA enabled results in being stuck on a screen with "Please verify your Facebook account", but clicking Continue causes a loop.

![image](https://user-images.githubusercontent.com/652759/94059955-15956980-fddb-11ea-87e6-debf4a19e285.png)

**Steps to Reproduce:**
Attempt to log in to the Messenger app with a Facebook account with Two Factor Authentication enabled.
Facebook page appears requesting 2FA code. Entered.
Returns to messenger,com, above message appears.

**Additional Context**
I'm using a generic 2FA app on my phone (Authenticator Plus), rather than the Facebook mobile app, but it's standard TOTP.
The URL the page is stuck on is https://www.messenger.com/login/checkpoint_interstitial/?next=... (plus pile of parameters with the URL encoded for the "Continue" link).
Then links to https://www.facebook.com/checkpoint/start/?ip=x.x.x.x and a bunch of other parameters encoded up, including a return URL back to messenger.com at the end.
Network console shows the messenger.com request being loaded, followed by the facebook.com one automatically, which it 302s back to https://www.messenger.com/login/auth_token/?userid=[xxx]&auth=[xxx] (and a few more parameters), sets a 'checkpoint' cookie, It then redirects back to the first checkpoint_interstitial page, giving the appearance of having done nothing.

Not sure if this is on your end or theirs, but I'm not getting the same issues running incognito in a regular browser. I also tried adding Facebook itself as a workspace app, which logged in just fine, but the messenger.com site still refuses to proceed further.

**Comment by insanityinside** [comment]
Looks like it's actually an issue on their end, it appears messenger.com has completely broken for me in a browser now. That, or I upset some security protocol somewhere.

**Comment by quanglam2807** [comment]
Thank you for reporting this! I'll try to test and see if it works for me.
