### ISSUE TITLE
bug: One of two multisite apps keeps loosing logged in status

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1036]
# Bug Report
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
I have 2 multisite apps created using WebCatalog. One with personal accounts like Gmail, Feedly and GitHub. Another with band accounts like Gmail, Twitter and SoundCloud. Both have the option enabled to "Share browsing data between workspaces". The personal multisite app after closing and opening again, all accounts are logged out. The band multisite app does not show this behavior.

**Comment by quanglam2807** [comment]
I'm investigating this. @ekamran is also facing the same bug.

**Comment by quanglam2807** [comment]
I couldn't reproduce the bug on my computer. Did you guys create custom multisite apps? @ekamram @brownhamer

**Comment by ghost** [comment]
Yes, both multisite apps are custom ones.

**Comment by ghost** [comment]
Also, it doesn't happen all the time. I have not managed to find a specific pattern in it happening.

**Comment by ekamran** [comment]
Default 'School' multisite app is the one which logs out every now and then. 

Custom Multisite App has similar issues. 

Default 'Work' works without any problems. 

**Strange Case**

Custom App created from Amazon.com as **Amazon.in** not only logs out but also resets the window height n width. Feels like a new installation every-time.

**Comment by quanglam2807** [comment]
A user just reported this same behavior on Mac as well (with shared browsing data option enabled)

It’s so frustrating. I’ll try my best to fix this.

**Comment by quanglam2807** [comment]
Good news, everyone! It's fixed in the latest update.

**Comment by ghost** [comment]
That is indeed good news.

**Comment by ekamran** [comment]
Awesome, Great job @quanglam2807

**Comment by ekamran** [comment]
Disheartened to report this again @quanglam2807 

I setup a Custom Multisite App from School, added several workspaces and logged in to all of them.

Restarted just once and half of them lost their login status.

Once again, it is the SCHOOL Multisite App which has this problem for me.
The other works fine like Work & SingleBox (Custom or default).

Overall settings for each multisite app is also same.

**Comment by quanglam2807** [comment]
I'm so sorry for all the troubles. Do you have "Share browsing data between workspaces" option enabled?

**Comment by ekamran** [comment]
Yes, Sharing data is enabled and I understand that once we click on it, each app logs out.

So I enabled this setting on the Blank Canvas.

**Comment by quanglam2807** [comment]
Thank you, @ekamran.

I think this must be something else. The bug that was fixed would basically wipe all your browsing data. But in this case, you're only logged out in half of your workspaces. Would you mind sharing the list of sites that you've added in the School app? If it's too private, you can also share it directly to me via email quang.lam@webcatalog.app

**Comment by quanglam2807** [comment]
It seems like this is caused by a bug in Windows 10 that affects all Chromium-based browsers: https://mspoweruser.com/microsoft-close-to-fixing-windows-10-website-logout-bug/

**Comment by ekamran** [comment]
>  If it's too private, you can also share it directly to me via email [quang.lam@webcatalog.app](mailto:quang.lam@webcatalog.app)

I will send you the list on your email id.



> It seems like this is caused by a bug in Windows 10 that affects all Chromium-based browsers: https://mspoweruser.com/microsoft-close-to-fixing-windows-10-website-logout-bug/

I'm on mac v10.15.7

**Comment by quanglam2807** [comment]
@ekamran confirmed this was fixed with recent updates. Thank everyone for testing this out!
