### ISSUE TITLE
bug: Feedly not updating "count" badge

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1037]
# Bug Report
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
I have Feedly installed, but the icon in the sidebar is not showing the count of unread items, nor is the WIndows taskbar icon updated to reflect that I have unread messages.

**Comment by quanglam2807** [comment]
Thank you for reporting this. 

WebCatalog detects badge count by looking at the site title for something like this "(2) Feedly" so if Feedly uses different structure, the app won't be able to detect it. I'll try to see what I can do to support Feedly.

**Comment by quanglam2807** [comment]
Let's move the discussion to https://github.com/webcatalog/webcatalog-app/issues/1425
