### ISSUE TITLE
Custom app creation fails when using default icon

### ISSUE THREAD

**Issue by TsubasaNoNai** [webcatalog/webcatalog-legacy#104]
MacOS 10.13.6, WebCatalog Version 12.6.1

When trying to create a custom app, it just returns a "We're sorry. WebCatalog has failed to install ***" message. Tested across different engines, all return same error. Installing from the directory works as intended. 

Edit: Apparently only when installing with default icon.

**Comment by apidevlab** [comment]
I see the same behaviour it's also listed in #72

**Comment by quanglam2807** [comment]
I'll try to fix this ASAP.
