### ISSUE TITLE
bug: Squoosh seems to have stopped working - downloads don't download - or is it just me?

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1042]
# Bug Report
**Specifications:**
- App Version: Latest
- OS (macOS, Windows, Linux): Mac

Upload an image, optimise, click the download link in the bottom right. Works fine in a regular browser.

**Comment by quanglam2807** [comment]
Thank you for reporting, Marcus! It seems like I broke something with https://github.com/atomery/juli/pull/114
