### ISSUE TITLE
feature: Firefox engine improvement

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1046]
# Feature Request
**Specifications:**
- App Version: Latest
- OS (macOS, Windows, Linux): Mac

When starting a new Firefox app, it asks you to select a profile.

If you select the `default-release` option that's selected by default, then it just opens your existing Firefox browser. Selecting `default` seems to work for the actual app wanting to be launched.

Maybe the tooltip and other guidance should guide on that.

Haven't tried multiple Firefox apps yet, so not sure if they need a new profile created for each or `default` will work for multiple Firefox apps?

**Comment by marcusquinn** [comment]
I can't get a Firefox webapp to work, it always starts the actual Firefox browser related to the Profile selected, and if I create a new Profile, it starts the standard Firefox browser using that new profile instead of the webapp I'd created.

**Comment by quanglam2807** [comment]
Thank you so much, Marcus! I think it would probably sunset Firefox and Opera support.  The experience is not great and only confuses users.

**Comment by quanglam2807** [comment]
I'll sunset Firefox support. I couldn't figure out a way to bypass Firefox's limitations and since there're not many users using Firefox as browser engine, it's best to sunset the feature so I can focus on more important ones.

To fix the main app, you can run `/Applications/Firefox.app/Contents/MacOS/Firefox --ProfileManager`, then choose `default-release` profile and then `Start Firefox` to make Firefox use the default profile.

**Comment by quanglam2807** [comment]
Feature removed with #1067

**Comment by marcusquinn** [comment]
> I'll sunset Firefox support. I couldn't figure out a way to bypass Firefox's limitations and since there're not many users using Firefox as browser engine, it's best to sunset the feature so I can focus on more important ones.
> 
> To fix the main app, you can run `/Applications/Firefox.app/Contents/MacOS/Firefox --ProfileManager`, then choose `default-release` profile and then `Start Firefox` to make Firefox use the default profile.

Ahh, that's very sad - Firefox (Nightly with Webrender enabled) is by far the fastest browser I use.

Opera I can live without in preference for Vivaldi - but neither is as fast as the latest Firefox.

Anything I can do to persuade you and others to keep Firefox support? If it worked I'd switch all my non-Electron apps to Firefox.

You can remove Chrome if you like though, I'm doing all I can to get rid of that backdoor ridden browser.
