### ISSUE TITLE
feature: add option to create non-Electron multisite apps

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#1059]
# Bug Report
**Specifications:**
- App Version: 25.0.0
- OS (macOS, Windows, Linux): MacOS 10.15.7

**Description:**

Custom Chrome app cannot be created without entering a default URL. When Chrome is set to start with the same pages open as last session, the default URL in the custom Chrome app launches a new tab. When closed and opened again, it launches a new tab again and will continue doing this. Requires the user to close the tab every time the custom Chrome app is started.

Please consider allowing for no URL to be entered at custom Chrome app creation to prevent the new tab to be created at every launch.

**Steps to Reproduce:**

**Additional Context**

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-app/pull/1133
