### ISSUE TITLE
bug: v25.1.0 apps do not open (Electron)

### ISSUE THREAD

**Issue by Ryuk1986** [webcatalog/webcatalog-legacy#1060]
# Bug Report
**Specifications:**
- App Version: v25.1.0
- OS (macOS, Windows, Linux): Widows 10, Build 2004

**Description:**
WebCatalog apps no longer launch
Issue occured when updating today from v25.0.0 to v25.1.0. 

App appears as running in Task manager but does no app window shows

This affects both existing and new apps as well

Tried to uninstall AppCatalog completely and re-install it - issue remains

**Comment by quanglam2807** [comment]
I'm so sorry for this. It has been fixed. You just need to open WebCatalog and update your apps to the latest version.

**Comment by Ryuk1986** [comment]
It works!! Thank you so much! :)
