### ISSUE TITLE
bug: duplicated icon in application bar Ubuntu 20.04

### ISSUE THREAD

**Issue by PietroFara** [webcatalog/webcatalog-legacy#1068]
# Bug Report
**Specifications:**
- App Version: 25.1.0
- OS (macOS, Windows, Linux): Ubuntu Linux 20.04

**Description:**
I add a created app (onedrive) to the application bar in ubuntu 20.04. When I start the app it duplicates the icon on the bar.

**Steps to Reproduce:**
Create any app and then bookmark it from the application menu in Ubuntu

**Additional Context**
 I have fixed it adding 'StartupWMClass=microsoft onedrive' to the webcatalog-microsoft-onedrive.desktop in my .local/share/applications
Could it be automatized?

**Comment by quanglam2807** [comment]
Thank you for reporting this! This can definitely be automated. See https://github.com/webcatalog/webcatalog-app/blob/master/public/libs/app-management/install-app-async/forked-script-electron-v2.js#L329

One question, can `StartupWMClass` value be anything? Or does it need to follow app name or id?

**Comment by PietroFara** [comment]
I searched on google and found this https://askubuntu.com/questions/632382/duplicate-icons-of-an-application-running-in-wine
As it says, I have run 
`xcrop WM_CLASS` 
and it returned
`WM_CLASS(STRING) = "microsoft onedrive", "Microsoft OneDrive"`
Then I chose the first one and modified the .desktop
Maybe it is assigned with the app name, I am not sure about it

**Comment by quanglam2807** [comment]
Thank you for confirmation! I'll fix this.

Related to https://github.com/electron/electron/pull/858

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-app/pull/1070

**Comment by PietroFara** [comment]
Great! Thank you man for your immediate fix. 
I have just downloaded the new version and tried it. It works!

**Comment by quanglam2807** [comment]
That's great! Thank you for letting me know.
