### ISSUE TITLE
Sunset the product

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#108]
Google is adding PWA support to Chrome  with v70 on Windows and v72 on macOS. And it works pretty well. So I think it's time to consider moving the product to maintenance stage.

**Comment by quanglam2807** [comment]
I tested PWA with Chrome on Mac and it worked very well. They even planned to add many great features like: 

> Keyboard shortcuts - Adding support for keyboard shortcuts, so you can provide your own functionality.
Badging for the launch icon Let the user know about important events that you don’t want to display a full notification for.
Link capturing - Opening the installed PWA when the user clicks on a link handled by that app.

So is it still relevant to continue developing WebCatalog? What makes you think WebCatalog is different?

**Comment by robot3498712** [comment]
Quick search I found a tiny set of PWAs; my main application, GMail, is not supported.
It needs to run sandboxed and on demand, so WebCatalog and similar solutions still are very relevant to me.
On that note, I'd like to put forward a feature request (similar to Wavebox): copy link option via context menu on right-click.

Thanks for your work, much appreciated!
