### ISSUE TITLE
feature: add back Firefox support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1091]
> I'll sunset Firefox support. I couldn't figure out a way to bypass Firefox's limitations and since there're not many users using Firefox as browser engine, it's best to sunset the feature so I can focus on more important ones.
> 
> To fix the main app, you can run `/Applications/Firefox.app/Contents/MacOS/Firefox --ProfileManager`, then choose `default-release` profile and then `Start Firefox` to make Firefox use the default profile.

Ahh, that's very sad - Firefox (Nightly with Webrender enabled) is by far the fastest browser I use.

Opera I can live without in preference for Vivaldi - but neither is as fast as the latest Firefox.

Anything I can do to persuade you and others to keep Firefox support? If it worked I'd switch all my non-Electron apps to Firefox.

You can remove Chrome if you like though, I'm doing all I can to get rid of that backdoor ridden browser.

_Originally posted by @marcusquinn in https://github.com/webcatalog/webcatalog-app/issues/1046#issuecomment-707068527_

**Comment by quanglam2807** [comment]
Thank you for the feedback, Marcus. 

Vivaldi, Opera, Chrome are all Chromium-based so they're built on the same code base so it's much easier for me.

I understand it's a real bummer not to support Firefox and I'll try my best to bring it back. After a bit research, I've found some ways to overcome the limitations from the last implementation. It'll take a few weeks before it's added back as I still need to work on some other priorities.

**Comment by marcusquinn** [comment]
Seem to be working nicely now - thank you so much!

I see it as a responsibility for all developments to protect and promote private open-source alternatives, so happy to see this back and will provide any feedback as I see it, but so-far, so-good!

**Comment by quanglam2807** [comment]
@marcusquinn This might affect Firefox support: https://news.ycombinator.com/item?id=25589177

**Comment by marcusquinn** [comment]
Interesting read 🤞
