### ISSUE TITLE
feature: add option to auto-refresh only when the app is inactive

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1092]
Nice, thanks for adding this. However, is there any way to make it so that it only happens if the window is inactive?

I suppose one way would be having a hidden duplicate/tab of a page that is refreshing so that the page being used doesn't refresh while you're using it.

Once solved I can point everyone on this Xero thread to WebCatalog:

https://community.xero.com/business/discussion/64131

_Originally posted by @marcusquinn in https://github.com/webcatalog/webcatalog-app/issues/891#issuecomment-703195615_

**Comment by quanglam2807** [comment]
It's now available v10.3.0, Marcus. I've tested it but if you have some time, please play with it to see it works correctly. Also, inactivity is defined = when the web view is not focused. If that doesn't sound good, please let me know.

**Comment by marcusquinn** [comment]
> It's now available v10.3.0, Marcus. I've tested it but if you have some time, please play with it to see it works correctly. Also, inactivity is defined = when the web view is not focused. If that doesn't sound good, please let me know.

Thank you! Will check!

**Comment by marcusquinn** [comment]
For some reason the switch doesn't work:

![image](https://user-images.githubusercontent.com/6428977/97908113-2a501000-1d3e-11eb-8bb8-8d95b63fbc34.png)

**Comment by quanglam2807** [comment]
> For some reason the switch doesn't work:
> 
> ![image](https://user-images.githubusercontent.com/6428977/97908113-2a501000-1d3e-11eb-8bb8-8d95b63fbc34.png)

Thanks, Marcus!  The bug is so silly. I'll push the release shortly.

**Comment by marcusquinn** [comment]
This works amazingly well - thank you!

I posted on the forum too: https://community.xero.com/business/discussion/64131

Now, can I ask for one minor tweak, can you make it so there's also a manual input for the minutes?

Reason being Xero times-out after 10 minutes, so I would set the refresh value to 9 minutes.

**Comment by quanglam2807** [comment]
Awesome! Thank you so much, Marcus. I'll add the option soon.

**Comment by quanglam2807** [comment]
Hi @marcusquinn, forgot to tell you. The feature is to set custom refresh interval is now available :)

**Comment by marcusquinn** [comment]
Magic - thank you kindly!
