### ISSUE TITLE
bug: Multisite Apps immediately crashes when started if "share browsing data" option is enable

### ISSUE THREAD

**Issue by aleinthesky** [webcatalog/webcatalog-legacy#1094]
# Bug Report
**Specifications:**
- App Version: 25.4.2
- OS: Windows 10

**Description:**
Multisite Apps immediately crashes  when started if "share browsing data" option is enabled and several workspaces are set.

**Steps to Reproduce:**
Create a multisite Electron based App. Enable "Share browsing data between workspaces". Create at least two Workspaces. Close the App. When you relaunch the App, it immediately crashes. 
P.S.: multisite Apps were regularly working about a few weeks ago. They started crashing from the latest Webcatalog versions. 

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for reporting this. I couldn't reproduce the bug nor find out what happened. But I've reverted certain unorthodox changes made in recent releases. Hopefully, it will fix the problem.
