### ISSUE TITLE
Add Chromium support

### ISSUE THREAD

**Issue by aarroz** [webcatalog/webcatalog-legacy#11]
Currently only support Google Chrome, but not Chromium

**Comment by aarroz** [comment]
I can't seem to launch webapps with Chromium as the selected browser. Still only Google Chrome works.

**Comment by quanglam2807** [comment]
@aarroz The apps still launch with Google Chrome, right?

**Comment by aarroz** [comment]
Correct. Testing on Ubuntu 16.04

**Comment by quanglam2807** [comment]
@aarroz Can you open one of the files WebCatalog created in `~/bin`, replace `google-chrome` with `chromium-browser` to see if it would be fixed?

**Comment by aarroz** [comment]
That fixes it. For some reason it appears that the google-chrome still appears even though I choose chromium as the default for creating the webapp.

**Comment by quanglam2807** [comment]
@aarroz Fixed :)
