### ISSUE TITLE
feature: Add web page translation feature

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#1103]
# Feature Request
**Specifications:**
Multi-site apps within WebCatalog

**Description:**
It would be very handy to integrate your Translatium app or a simple button which will translate an entire web page into one's chosen language.

**Additional Context**
I'm not sure how difficult this would be to implement, but I'm thinking something similar to the Google Translate extension which will automatically translate an entire web page without user intervention if in another language, or manually translate if that method is chosen. May be a nice way to bridge Translatium into WebCatalog just like you did with SingleBox.

Thanks for your consideration, Quang!

**Comment by quanglam2807** [comment]
Thank you for suggesting this. At the moment, it would be quite challenging to make this happen. Translatium relies on Google Translate unofficial API to function and that's somewhat OK as Translatium has fairly small traffics and is free open-source app. But for WebCatalog, it would likely lead to legal issues.

**Comment by Woafmann** [comment]
Thanks so much for responding, Quang. Maybe someday the possibility will be available. Thanks again!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
