### ISSUE TITLE
bug: Multi-site app dock icon does not change after changing it.

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#1105]
# Bug Report
**Specifications:**
- App Version: WebCatalog Version v25.5.2
- OS: macOS Catalina 10.15.7 (19H2)

**Description:**
After creating a multi-site application and choosing an icon during creation, it is not possible to change the icon even though the edit page does not specify that this isn't possible.

**Steps to Reproduce:**
Create a multi-site app and then afterwards, go into WebCatalog.app, click, the "Installed" tab, click the kebab menu of the multi-site app you just created and select, "Edit this app". Change the application icon and try saving. It won't.

**Workaround**
Of course, it's possible to change the icon outside of WebCatalog by way of the "Get Info" sub context menu. However, the old icon will still show on the WebCatalog.app "Installed" tab.

**Comment by Woafmann** [comment]
Sorry fo the duplicate issue report. I did search under the word, “Icon” and didn’t see the other issue. My bad.

**Comment by quanglam2807** [comment]
Actually, that email doesn't mean you created a duplicated issue. It means this issue (1105) is fixed by code change/pull request 1108. So don't worry! Thank you so much.

**Comment by Woafmann** [comment]
Oh good. I know you must be very busy, so I try and look through the features/bugs before I post. 

Thanks!
