### ISSUE TITLE
feature: Allow for Multi-Site app name changes after creation

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#1106]
# Feature Request
**Specifications:**
App Version: WebCatalog Version v25.5.2
OS: macOS Catalina 10.15.7 (19H2)

**Description:**
Allow for the changing of Multi-Site app names within WebCatalog

**Temporary Workaround**
Of course, it's possible to change the app name in Finder, but this naturally breaks WebCatalog from further editing or launching of the app. Will this will also break WebCatalog from updating the app as well?

 If it can't be done automatically, can it be changed manually without too much headache? I attempted to change the name in the app in "~/Library/Application Support/<app name>/Settings" but I'm not sure where else I should change it.

Thx!

**Comment by quanglam2807** [comment]
Thank you for this. For now, please don't attempt to rename the app as it would break the app. I'll try to add this feature ASAP.  Currently, app data file paths are tied to the app name, so it would require some underlying changes before the feature is added. 

Probably, this issue will be resolved after https://github.com/webcatalog/webcatalog-app/issues/1033

**Comment by Woafmann** [comment]
Thank you, Quang. Another solution would be to allow existing multi-site apps to be duplicated with the existing websites intact and then just give the duplicate a new name and icon. Then, one can just delete the original multi-site app if they choose. 

This solution would also essentially allow for templates with core websites that people always want in their multi-site apps for instance. 

Currently, creating multi-site apps from other existing multi-site apps does not include the contained websites in it. 

As a further alternative, giving the ability to copy websites from one multi-site to another would achieve the same goal since one could quickly make a blank multi-site app, and then just copy all their existing websites into it. Of all the solutions, this one seems the most useful actually.

**Comment by quanglam2807** [comment]
@Woafmann So sorry for not replying to this thread earlier. This is definitely possible. I'll try to work on it soon.

**Comment by Woafmann** [comment]
Thank you, Quang! You’re the best! :)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
