### ISSUE TITLE
feature: Add support for "picture-in-picture" mode for YouTube

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#1113]
#Feature Request

**Specifications:**
App Version: WebCatalog Version v25.6.0
OS: macOS Catalina 10.15.7 (19H2)

**Description:**
Add support for "picture-in-picture" mode for YouTube in Multi-Site apps. 

In Chrome/Chromium, Safari, others, etc., it's possible to "right-click" and then "right-click" a second time to bring up an additional sub-context menu to enable PiP mode. 

It would be tremendously amazing if this could be enabled in multi-site apps as I rely on this mini Youtube window to float in the bottom of my screen while I'm working.

**Temporary Workaround**
None. I attempted to make a standalone Electron app. Same issue.

Thank you, Quang for your consideration in adding this needful feature!

**Comment by quanglam2807** [comment]
This is definitely possible. The only thing that I haven't managed to figure out is where to put the picture-in-picture button.

**Comment by Woafmann** [comment]
Perhaps as a "right-click" sub-context menu choice on the side-bar icon? Or, as an additional button in the top navigation bar?

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
