### ISSUE TITLE
The program cannot download and install any app

### ISSUE THREAD

**Issue by MSerif** [webcatalog/webcatalog-legacy#1121]
Hello,

The program cannot download and install any application; they all get stuck in the **_same_** spot. I uninstalled and reinstalled, but the error continues. Sample: 
![WebCatalog](https://user-images.githubusercontent.com/35164096/96723827-bfa2ea00-13b7-11eb-9972-29929a6c6e64.png)

**Comment by quanglam2807** [comment]
I'm sorry for the problem. It seems like something went wrong but the app failed to catch the bug and got stuck there. Would you mind updating to v25.8.0 and trying again, please? https://github.com/webcatalog/webcatalog-app/releases/tag/v25.8.0

**Comment by MSerif** [comment]
> I'm sorry for the problem. It seems like something went wrong but the app failed to catch the bug and stuck there. Would you mind updating to v25.8.0 and trying again, please? https://github.com/webcatalog/webcatalog-app/releases/tag/v25.8.0

The program has been updated to v25.8.0 and restarted. However, the issue continued. I uninstalled the program and downloaded v25.8.0 and installed it again. The problem still continues.

**Comment by quanglam2807** [comment]
> > I'm sorry for the problem. It seems like something went wrong but the app failed to catch the bug and stuck there. Would you mind updating to v25.8.0 and trying again, please? https://github.com/webcatalog/webcatalog-app/releases/tag/v25.8.0
> 
> The program has been updated to v25.8.0 and restarted. However, the issue continued. I uninstalled the program and downloaded v25.8.0 and installed it again. The problem still continues.

Thank you for trying! Does it still get stuck at the same spot or does it show an error message now?

**Comment by quanglam2807** [comment]
I'm sorry for this. This bug would take some time to fix as it seems like it only occurs on a few numbers of Windows machines and somehow, the app is not even able to catch the error and report it.

**Comment by MSerif** [comment]
> > > I'm sorry for the problem. It seems like something went wrong but the app failed to catch the bug and stuck there. Would you mind updating to v25.8.0 and trying again, please? https://github.com/webcatalog/webcatalog-app/releases/tag/v25.8.0
> > 
> > 
> > The program has been updated to v25.8.0 and restarted. However, the issue continued. I uninstalled the program and downloaded v25.8.0 and installed it again. The problem still continues.
> 
> Thank you for trying! Does it still get stuck at the same spot or does it show an error message now?

Yes; it still get stuck at the same spot.

**Comment by MSerif** [comment]
> I'm sorry for this. This bug would take some time to fix as it seems like it only occurs on a few numbers of Windows machines and somehow, the app is not even able to catch the error and report it.

Thanks for be interested. Hope you can fix it soon.

Note: **_v25.8.1_** -> problem still continues

**Comment by quanglam2807** [comment]
Thank you so much for the patience! Can hover your mouse over the ring to check which step it gets stuck at? Btw, which Windows version are you?

**Comment by MSerif** [comment]
> Thank you so much for the patience! Can hover your mouse over the ring to check which step it gets stuck at? Btw, which Windows version are you?

"Preparing..." _(Windows 7, 64 bit)_
![WebCatalog2](https://user-images.githubusercontent.com/35164096/96756570-ed4e5a00-13dc-11eb-9e4f-1a90d5fba954.png)

**Comment by quanglam2807** [comment]
Thank you so much for the information. It seems like this bug only occurs on Windows 7. I'll try to fix it ASAP.

**Comment by quanglam2807** [comment]
Fixed with https://github.com/webcatalog/webcatalog-app/pull/1126. An update will be released shortly :)

**Comment by MSerif** [comment]
> Fixed with #1126. An update will be released shortly :)

It is now running smoothly; thanks.
