### ISSUE TITLE
Some valid URLs are not recognized correctly

### ISSUE THREAD

**Issue by allo-** [webcatalog/webcatalog-legacy#113]
When you try to add ``http://someserver:8080/some/path``, webcatalog does not recognize it as valid URL.

**Comment by quanglam2807** [comment]
I think it's because `someserver` is not valid domain or IP.

**Comment by allo-** [comment]
This may be possible, that not the port is the problem, but that this is just a hostname in my LAN and no FQDN.
But it is a valid URL and when disabling the ``is-url`` check, I can use webcatalog to access it.

The alternative would be to use a pseudo domain like ``.local``, but I do not do this in my normal browser either.

**Comment by quanglam2807** [comment]
There's a PR for this segmentio/is-url#16. But nobody has merged it yet. :(

**Comment by allo-** [comment]
It looks like the PR is only adding tests?

What about just including the relevant code instead of loading the module to avoid waiting on upstream?

Another option: Use HTML5 Inputs instead of validating yourself? This seems to be the right place to do it, if we assume that users have a recent browser backend.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url
