### ISSUE TITLE
bug: When configured as default mail client, clicking an email address does not open a new mail (using Gmail)

### ISSUE THREAD

**Issue by bastichelaar** [webcatalog/webcatalog-legacy#1146]
# Bug Report
**Specifications:**
- App Version: v25.12.0
- OS (macOS, Windows, Linux): Windows

**Description:**
When the app is configured as a default mail client, clicking a link in a browser opens the application, but not a compose mail window.

**Steps to Reproduce:**
- Install the Gmail app in Webcatalog
- Configure as default mail client (on Windows 10)
- Click on an email address in your browser

**Comment by quanglam2807** [comment]
Thank you so much for reporting this. This bug is very serious.

**Comment by quanglam2807** [comment]
The bug is fixed with WebCatalog Engine 11.2.3
