### ISSUE TITLE
feature: Only restart the app when closing the preference window

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1154]
There's a few preference changes that require restarting the app, but you end up restarting the app a number of times to make each preference change.

Perhaps better to only offer to restart the app once all preference changes have been made and you "Apply changes" or close the Preferences window?

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/195

**Comment by marcusquinn** [comment]
Nice, thank you!
