### ISSUE TITLE
support for browser extentions?

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#1160]
would it be possible to use browser extentions in the webcatalog apps?

I am thinking about some handy browser extentions for either Chrome/Electron or Firefox that would apply to the website-app

**Comment by floriandierickx** [comment]
This thread seems to provide some clues on whether it is doable / possible : https://stackoverflow.com/questions/53341132/how-can-i-add-a-custom-chrome-extension-to-my-electron-app

It refers to this Electron issue: https://github.com/electron/electron/issues/19447

**Comment by quanglam2807** [comment]
Thank you for bringing this up. Electron does support extensions but it lacks certain APIs so it's not possible at the moment for WebCatalog to support this. I'll close this issue as it's the same as https://github.com/webcatalog/webcatalog-app/issues/710
