### ISSUE TITLE
feature: consider LocalCDN as an additional extension feature to help with speed & privacy

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1171]
I'm sure their website explains it well enough: https://www.localcdn.org

> LocalCDN is a web browser extension that emulates Content Delivery Networks to improve your online privacy. It intercepts traffic, finds supported resources locally, and injects them into the environment. All of this happens automatically, so no prior configuration is required. Feel free to use the following testing utility to find out if you are properly protected. For more information, please look at the graphic below or read the tutorial or our Wiki pages. You can also download the extension directly from Mozilla and just try it.

> LocalCDN supports over 100 Libraries and 27 CDNs!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
