### ISSUE TITLE
feature: Apple Silicon support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1187]
# Feature Request
**Specifications:**
- App Version: 
- OS (macOS, Windows, Linux): macOS

If anyone has a Macbook with Apple M1 chip, please join this thread!

**Comment by scottrbaxter** [comment]
MacBook Air (M1, 2020) on hand... there are plenty of developer tools that i'm currently testing as well, would be happy to help out with Webcatalog if/when needed.

**Comment by wiiiimm** [comment]
👋🏽

**Comment by wiiiimm** [comment]
@quanglam2807 i am happy to help test M1 support. I see that you have switched over to electron v11.

**Comment by quanglam2807** [comment]
Thank you, guys! This is currently blocked by this: https://github.com/electron-userland/electron-builder/pull/5426

**Comment by quanglam2807** [comment]
first build: https://github.com/webcatalog/webcatalog-app/releases/download/v27.2.0-alpha/WebCatalog-27.2.0-alpha-arm64.dmg

**Comment by scottrbaxter** [comment]
@quanglam2807 I've installed the this initial alpha build, and was able to install a custom app with the Brave (which is currently Intel still) engine. So far it seems to be running fine, though I've only just started testing.

I then tested a custom app using the `WebCatalog Engine`, and also the Github app from the Discover page using this same engine, and it crashes with `Failed to install <app_name>. DISMISS`

<img width="315" alt="Screen Shot 2020-12-14 at 9 22 47 PM" src="https://user-images.githubusercontent.com/4142806/102166981-07437080-3e53-11eb-9d4a-4d8ee2819492.png">

Are there any specific logs that'll help you out?

**Comment by quanglam2807** [comment]
Thank you, @scottrbaxter! My bad, I forgot to push the files for WebCatalog Engine. Can you try again, please? Normally, bugs like this are reported automatically by the app so you don't need to do anything.

**Comment by quanglam2807** [comment]
For testing, with the alpha build, WebCatalog apps, WebCatalog-Engine-based apps and WebKit-based should run natively on M1 Macbook

**Comment by scottrbaxter** [comment]
That did it, thanks!

**Comment by quanglam2807** [comment]
> That did it, thanks!

Does it mean it works?

**Comment by scottrbaxter** [comment]
Yes, the WebCatalog Engine is working so far. Started basic testing, but so far it's working.

Is there anything specific that you'd like me to test?

**Comment by quanglam2807** [comment]
Not really, if the generated apps are ARM64-based then everything is working properly.  :) Thank you so much, @scottrbaxter

**Comment by quanglam2807** [comment]
I'll release an update to the WebCatalog app shortly so we can test if the updater is working correctly with M1 version. If it works, then I think everything is ready :)

**Comment by quanglam2807** [comment]
New build (27.2.0-rc) is up. Please try to update to the new version using the app updater to see if it works correctly.

**Comment by scottrbaxter** [comment]
I was able to update to `27.2.0-rc`, and the app runs fine. That said, I happened to notice that the `27.2.0-alpha` version I manually downloaded from your link (above), when I `Get Info` on the `/Applications/WebCatalog.app`, I saw `Application (Apple Silicon)`, however, now that the app auto-updated to `27.2.0-rc`, Get Info states `Application (Intel)`, just as the stable version prior to this alpha release.

I'm not sure what exactly needs to be done during updates to keep it as Apple Silicon, but I'm happy to test if you can determine why it would have reverted to Rosetta2/Intel.

<img width="262" alt="Screen Shot 2020-12-16 at 12 52 45 AM" src="https://user-images.githubusercontent.com/4142806/102315039-0f75db80-3f39-11eb-9a88-d5a7e56201d4.png">

<img width="262" alt="Screen Shot 2020-12-16 at 12 52 06 AM" src="https://user-images.githubusercontent.com/4142806/102315048-1270cc00-3f39-11eb-9cd7-962ac510e538.png">

**Comment by quanglam2807** [comment]
Thank you for reporting, @scottrbaxter. It seems like it happens because 27.2.0-alpha is running an outdated version of the updater. Can you manually download and install the Apple Silicon version for 27.2.0-rc: https://github.com/webcatalog/webcatalog-app/releases/download/v27.2.0-rc/WebCatalog-27.2.0-rc-arm64.dmg and wait for the next update to see if the bug occurs again?

**Comment by scottrbaxter** [comment]
Done.

<img width="260" alt="Screen Shot 2020-12-16 at 2 38 20 AM" src="https://user-images.githubusercontent.com/4142806/102324676-c8dbad80-3f47-11eb-9209-0b17240a6079.png">

**Comment by quanglam2807** [comment]
Awesome! v27.2.0 is up :)

**Comment by videopilot** [comment]
Amazing!

But on my new M1 Mac, it seems the auto-generated icon tiles are bigger than the big sur style.

**Comment by quanglam2807** [comment]
> Amazing!
> 
> But on my new M1 Mac, it seems the auto-generated icon tiles are bigger than the big sur style.

Can you email me at quang.lam@webcatalog.app some examples? The icon template comes straight from Apple so I'm quite certain the size is correct.
