### ISSUE TITLE
feature: 'Save image as' is missing 

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1196]
# Bug Report
**Specifications:**
- App Version: 26.4.1
- OS (macOS, Windows, Linux): Linux

**Description:**
'Save image as' is missing in WhatsApp web

**Steps to Reproduce:**
Right-click on images

**Additional Context**
![Screenshot from 2020-11-25 01-21-36](https://user-images.githubusercontent.com/20030910/100155694-ee334980-2ebc-11eb-868c-926329ee84ca.png)

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/235
