### ISSUE TITLE
feature: automatically start up and minimized

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1198]
# Feature Request
**Specifications:**
- App Version: 26.5.1
- OS (macOS, Windows, Linux): Linux

**Description:**
I put this to startup applications `/home/user/.webcatalog/WhatsApp/WhatsApp` , but its not launch minimized on tray

**Comment by quanglam2807** [comment]
You can actually do this through app preferences: 
<img width="872" alt="Screen Shot 2020-12-08 at 2 28 28 PM" src="https://user-images.githubusercontent.com/1548835/101453340-c682bd80-3961-11eb-9208-a3a81c3fddf7.png">

**Comment by F50Ci37Y** [comment]
I don't have it in Ubuntu

![Screenshot from 2020-12-08 21-58-34](https://user-images.githubusercontent.com/20030910/101525499-a8887d80-39a0-11eb-9b4a-adb50cdc068b.png)


WebCatalog Engine: 13.0.0-alpha

**Comment by F50Ci37Y** [comment]
In `13.0.0-alpha.3` I have `Open at login`, I set `Yes, but minimized` But on login it's open maximize not minimize and `Open at login` reset to `No`
![Screenshot from 2020-12-14 11-28-29](https://user-images.githubusercontent.com/20030910/102055671-717ef580-3e00-11eb-8de6-08ac7fd0a415.png)

**Comment by F50Ci37Y** [comment]
```
WebCatalog Engine: 15.13.2
Electron: 11.3.0
Node: 12.18.3
Chromium: 87.0.4280.141
```
In Linux autostart its work, but not minimized

**Comment by TechnoSparks** [comment]
Hello, is it possible to also do this on Windows? The "Open at login" setting does not have "Yes, but minimized". Only Yes and No.

I did try launching an instance with the `--hidden` switch. But alas it does not work.

**Comment by TechnoSparks** [comment]
I have checked the source code and it seems that Windows is purposely omitted from this feature. I assume that there are probably issues in Windows when it comes to launching an application minimized.

**Comment by quanglam2807** [comment]
@TechnoSparks Currently, the 'Yes, but minimized' option is not available on Windows. We'll try to work on it in the future.

**Comment by TechnoSparks** [comment]
@quanglam2807 i'd like to express my gratitude for your work on this lovely piece of software. It is very useful.

For anyone else who want to do a hacky workaround to this, here are the steps in order to hide your apps on launch on Windows: https://gist.github.com/TechnoSparks/2d7530ef304c3a74b5ed9997b1a0f3c2
