### ISSUE TITLE
Download links on home page are incorrect "404"

### ISSUE THREAD

**Issue by sirweazel** [webcatalog/webcatalog-legacy#12]
The direct download links from the home page <https://quang.im/webcatalog/> are incorrect. It appears you did not update the links when you appended your binary packages with "lite".

Your current 404 links are:
<https://github.com/quanglam2807/webcatalog/releases/download/v1.0.0/webcatalog-1.0.0-x86_64.AppImage>

<https://github.com/quanglam2807/webcatalog/releases/download/v1.0.0/webcatalog-1.0.0.dmg>

When they should be:
<https://github.com/quanglam2807/webcatalog/releases/download/v1.0.0/webcatalog-lite-1.0.0-x86_64.AppImage>

<https://github.com/quanglam2807/webcatalog/releases/download/v1.0.0/webcatalog-lite-1.0.0.dmg>

Thank you

**Comment by quanglam2807** [comment]
Thanks a lot for letting me know! Fixed :)

**Comment by sirweazel** [comment]
Thanks for the quick fix because I had let some other's know of your site/project for someone trying to install ice-ssb but having issues. 
Just in case it isn't intentional, did you know your site is now redirecting to just <https://quang.im/>
I figured maybe you're updating it since making all these code changes.

**Comment by quanglam2807** [comment]
@sirweazel Thanks for letting me know. Fixed :)
