### ISSUE TITLE
bug: Minimize button don't work

### ISSUE THREAD

**Issue by guinuxbr** [webcatalog/webcatalog-legacy#1201]
# Bug Report
**Specifications:**
- WebCatalog-26.5.0.AppImage:
- Linux (openSUSE Tumbleweed):

**Description:**
Installed application do not minimize when the corresponding icon is pressed in the window bar. The window minimizes and get back to the previous state immediately.

**Steps to Reproduce:**
Just install any application and try to minimize it.

**Additional Context**
The main application window respect the minimize command, the problem only occurs with the installed ones.
Here goes a GIF to illustrate the problem: https://imgur.com/a/RTPYel6

**Comment by quanglam2807** [comment]
I'm not sure if this bug only affects OpenSUSE as I can't reproduce it with Ubuntu 20.10

**Comment by guinuxbr** [comment]
Well, in this case, I'm pretty sure that we have a bug. :-D
If you need more testing, just tell me.

**Comment by quanglam2807** [comment]
Thanks @guinuxbr for assisting me with this. 

This bug only affects KDE Plasma desktop environment. Somehow, when a `BrowserView` is set, KDE refuses to minimize the app window.
