### ISSUE TITLE
Latest windows build

### ISSUE THREAD

**Issue by robot3498712** [webcatalog/webcatalog-legacy#121]
Hi,
could someone please provide a windows build for latest release? Not listed via https://github.com/webcatalog/webcatalog/releases
Tried it myself but running into errors and I don't have the time to learn a new build chain right now.
Thank you

**Comment by quanglam2807** [comment]
Thank you for letting me know. I've fixed it.

**Comment by robot3498712** [comment]
Awesome, thanks a lot for the update.
