### ISSUE TITLE
bug: Open App on click notification 

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1221]
# Feature Request
**Specifications:**
- App Version: WebCatalog Engine: 13.0.0-alpha
- OS : Linux

**Description:**
I use Webcatalog for Whatsapp. When I receive a message its show a notification it's ok, but when I click on the notification box the Whatsapp not opening

**Comment by devhammed** [comment]
I was about opening an issue on this too, I have switched back to nativefier CLI tool, for now.

It is really frustrating, I am used to opening apps on notification click.

**Comment by quanglam2807** [comment]
Bug confirmed. I'm working on a fix.

**Comment by devhammed** [comment]
> Bug confirmed. I'm working on a fix.

I can see you have pushed a fix but after inspecting the code, what it is actually doing is just to open the app when you clicked a notification (you can correct me if I am wrong).

But take notifier, for example, if you clicked on a WhatsApp notification, it will open the app and also go to that message which I know it is the default behaviour for service workers in browsers.

Hopefully, this fix should also resolve that.

**Comment by quanglam2807** [comment]
> > Bug confirmed. I'm working on a fix.
> 
> I can see you have pushed a fix but after inspecting the code, what it is actually doing is just to open the app when you clicked a notification (you can correct me if I am wrong).
> 
> But take notifier, for example, if you clicked on a WhatsApp notification, it will open the app and also go to that message which I know it is the default behaviour for service workers in browsers.
> 
> Hopefully, this fix should also resolve that.

That behavior is handled by the web apps so you don't need to worry. It'll work.

**Comment by devhammed** [comment]
> > > Bug confirmed. I'm working on a fix.
> > 
> > 
> > I can see you have pushed a fix but after inspecting the code, what it is actually doing is just to open the app when you clicked a notification (you can correct me if I am wrong).
> > But take notifier, for example, if you clicked on a WhatsApp notification, it will open the app and also go to that message which I know it is the default behaviour for service workers in browsers.
> > Hopefully, this fix should also resolve that.
> 
> That behavior is handled by the web apps so you don't need to worry. It'll work.

Oh, I know about service workers but my thought is that the browser will also have to handle the `client.focus()` or `clients.openWindow()` made by the handler.

**Comment by quanglam2807** [comment]
> > > > Bug confirmed. I'm working on a fix.
> > > 
> > > 
> > > I can see you have pushed a fix but after inspecting the code, what it is actually doing is just to open the app when you clicked a notification (you can correct me if I am wrong).
> > > But take notifier, for example, if you clicked on a WhatsApp notification, it will open the app and also go to that message which I know it is the default behaviour for service workers in browsers.
> > > Hopefully, this fix should also resolve that.
> > 
> > 
> > That behavior is handled by the web apps so you don't need to worry. It'll work.
> 
> Oh, I know about service workers but my thought is that the browser will also have to handle the `client.focus()` or `clients.openWindow()` made by the handler.

Somehow, in this case, that doesn't work on Linux so WebCatalog needs to trigger it manually. 

The reason why it works with Nativefier is because Nativefier probably relies on `BrowserWindow` or `webview` API (I don't remember exactly) but WebCatalog relies on `BrowserView` API which offers better performance than `webview` (and allows it to offer features like workspaces). But `BrowserView` API is still new, somewhat experimental & buggy.

**Comment by devhammed** [comment]
> > > > > Bug confirmed. I'm working on a fix.
> > > > 
> > > > 
> > > > I can see you have pushed a fix but after inspecting the code, what it is actually doing is just to open the app when you clicked a notification (you can correct me if I am wrong).
> > > > But take notifier, for example, if you clicked on a WhatsApp notification, it will open the app and also go to that message which I know it is the default behaviour for service workers in browsers.
> > > > Hopefully, this fix should also resolve that.
> > > 
> > > 
> > > That behavior is handled by the web apps so you don't need to worry. It'll work.
> > 
> > 
> > Oh, I know about service workers but my thought is that the browser will also have to handle the `client.focus()` or `clients.openWindow()` made by the handler.
> 
> Somehow, in this case, that doesn't work on Linux so WebCatalog needs to trigger it manually.
> 
> The reason why it works with Nativefier is because Nativefier probably relies on `BrowserWindow` or `webview` API (I don't remember exactly) which WebCatalog relies on `BrowserView` API which offers better performance than `webview` (and allows it to offer features like workspaces). But `BrowserView` API is still new, somewhat experimental & buggy.

Alright then, thank you.
