### ISSUE TITLE
feature: Exit in tray menu

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1222]
# Feature Request
**Specifications:**
- App Version: 13.0.0-alpha
- OS: Linux

**Description:**
Please add Exit app in tray menu

**Additional Context**
![ksnip_20201209-113731](https://user-images.githubusercontent.com/20030910/101602228-0786da80-3a13-11eb-86d0-19482804407c.png)

**Comment by quanglam2807** [comment]
This should be possible now :D

**Comment by F50Ci37Y** [comment]
Hmmm. I don't have it in Linux

![image](https://user-images.githubusercontent.com/20030910/119263818-d16e9900-bbf5-11eb-8e98-1f93e8f71712.png)

**Comment by F50Ci37Y** [comment]
Version 21.12.0 (WebCatalog, x64)
Neutron: 21.12.0
Electron: 16.0.6
Node: 16.9.1
Chromium: 96.0.4664.110

Still, we don't have a tray menu.
 @quanglam2807
