### ISSUE TITLE
bug: Can't updating/creating custom Multisite app with custom icon

### ISSUE THREAD

**Issue by PietroFara** [webcatalog/webcatalog-legacy#1223]
# Bug Report
**Specifications:**
- App Version: v26.6.1
- OS: macOS Big Sur

**Description:**
A custom multisite app created with an older version (don't remember the version number) with a custom icon doesn't update.

**Steps to Reproduce:**
I have a custom multisite app with telegram and whatsapp (I think that it doesn't matter) with a custom icon (png picked up from the Images default folder). 
You can reproduce the bug also creating a new custom multisite app with custom icon. You just can't.

**Additional Context**
If I reset to default the icon settings everything is working fine and the app can be finally updated. But I have still the default icon.

**Comment by quanglam2807** [comment]
Thank you for reporting this. I've fixed this bug with v27.0.0.

**Comment by PietroFara** [comment]
Great job, sorry but I'm using the stable one and searching around I haven't found any bug report like this.
Anyway your app is awesome, thank you for making it

**Comment by quanglam2807** [comment]
It’s a regression when I attempted to fix this: https://github.com/webcatalog/webcatalog-app/issues/1185

You’re the first person to report this so no need to feel sorry :)
