### ISSUE TITLE
WhatsApp Linux

### ISSUE THREAD

**Issue by Sterntrix** [webcatalog/webcatalog-legacy#123]
WhatsApp stopped working on Linux.  Requires new browser support:
"WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
UPDATE GOOGLE CHROME"

**Comment by quanglam2807** [comment]
I'm sorry but WebCatalog no longer supports Linux.

**Comment by SK9MM777** [comment]
WhatsApp does not work on macOS.

Requires new browser support:
"WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
UPDATE GOOGLE CHROME"
