### ISSUE TITLE
feature: window app always visible

### ISSUE THREAD

**Issue by superlativ0** [webcatalog/webcatalog-legacy#1230]
# Feature Request
**Specifications:**
- App Version: 27.1
- macOS High Sierra

**Description:**
When the window app loses focus it disappears. This is a problem in mail applications because it does not allow dragging files from the desktop to attach files.

Thanks in advance and gorgeous work!!

**Comment by quanglam2807** [comment]
Thanks for the feedback, @superlativo77! Are there any other applications with this behavior?

**Comment by superlativ0** [comment]
> Thanks for the feedback, @superlativo77! Are there any other applications with this behavior?

Sorry, I only use webcatalog for Microsoft Outlook. Thanks

**Comment by quanglam2807** [comment]
Actually, I mean do you know any applications (not WebCatalog) that keep appearing when they lose focus? I'm a little bit confused by the feature request.

**Comment by superlativ0** [comment]
Excuse me, I didn't understand you well. Excuse me but I don't speak English. I have not tried other applications similar to webcatalog so I don't know if losing focus is a fixable thing. I just shared my problem that for example I cannot drag multiple files from the Finder to an email message to add multiple attachments at once.

**Comment by videopilot** [comment]
Do you mean when it's a menu bar app? As a regular window, it does not disappear. Maybe there could be an option for it to not dsappear as a menu bar app as well?

**Comment by superlativ0** [comment]
This must be the problem.  I don't know how it opens as a standalone app.  I have it in the top menu (next to the clock) and I open it from there.

**Comment by quanglam2807** [comment]
Thanks for the feedback. You can use the "Always on top" option in the latest version to achieve what you describe here.
