### ISSUE TITLE
bug: "Open link in new window" doesn't work anymore

### ISSUE THREAD

**Issue by benjaminfrombe** [webcatalog/webcatalog-legacy#1233]
# Bug Report
**Specifications:**
- App Version:27.2.0
- OS (macOS, Windows, Linux):macOS

**Description:**
"Open link in new window" doesn't work anymore

**Steps to Reproduce:**
click "Open link in new window" on a hyperlink, nothing happens

**Comment by quanglam2807** [comment]
Thanks for reporting. The bug is fixed in WebCatalog Engine v13.0.1
