### ISSUE TITLE
bug: MS Teams Screensharing not possible after update to latest version

### ISSUE THREAD

**Issue by palsch** [webcatalog/webcatalog-legacy#1235]
# Bug Report
**Specifications:**
- App Version: 
WebCatalog Engine: 13.0.0
Electron: 11.1.0
Node: 12.18.3
Chromium: 87.0.4280.88
- OS (macOS, Windows, Linux): Ubuntu 20.04

**Description:**
Since the update to the latest version (see App Version) I can't use the MS Teams Screensharing feature.
Normally you get the popup to select a Window/Desktop to share after clicking to the Screenshare button. But after the update this popup doesn't appear, so that I can't select the Desktop to start the sharing.

![image](https://user-images.githubusercontent.com/1561681/102382097-52cc5a80-3fca-11eb-9d81-644e8274f9fc.png)

**Steps to Reproduce:**
Call another user with MS Teams and try to use the screen sharing feature.

**Additional Context**
---

**Comment by quanglam2807** [comment]
Thank you for reporting, @palsch. The bug should be fixed in WebCatalog Engine 13.0.2.
