### ISSUE TITLE
bug: Facebook Messenger unable to log in

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1236]
# Bug Report
**Specifications:**
- App Version: 27.1.0
- OS: Linux

**Description:**

After entering username, password, there will be message:
```
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.
Go Back
Facebook © 2019 · Help
```
Using 2FA (code from app). After entering username, password, the 2FA question should appear and after entering it, should be log in and remain so (even I close the app sometimes). Using WebCatalog Engine as default.

**Steps to Reproduce:**

1. open the app and accept all cookies
2. enter username, password, tick "Keep me signed in"
3. click "Login"

**Additional Context**

Similar issue happens also with [Rambox Pro](https://rambox.pro/#home) - also there is impossible to use Facebook Messenger.
Also tried to add as custom app - still failed.
At the same time Facebook can log in with WebCatalog. As a workaround there is possible to switch to Messenger and vice versa.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
