### ISSUE TITLE
feature: Microsoft Office will open Teams separately in browser and not pop-up window

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1238]
# Feature Request
**Specifications:**
- App Version: 27.3.0
- OS: Linux

**Description:**

Currently when to add Microsoft Office, then other apps will open in pop-up window, but not MS Teams - this will be opened in default web browser. Therefore separate app MS Teams needs to be added and also separately logged in.

**Additional Context**

Haven't tested it with other apps, but this may happen with others as well, where are many apps at one place.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
