### ISSUE TITLE
feature: allow store window size, position

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1239]
# Feature Request
**Specifications:**
- App Version: 27.3.0
- OS: Linux, but applicable for all OSes

**Description:**

Allow to store app-specific window size and position. It helps to ensure, that window is not needed to be resized and/or prepositioned every time. Currently it needs to reopen many times the window, unless at some point it reminds it. But there is no way to check it, which window sizes and positions are stored for that particular app.

Another idea is to allow select one or more or all installed apps and define window size and position for selected apps.

**Additional Context**

For instance, documents in cloud storages require that. Sometimes such documents are in turn embedded at web pages. Therefore it is important to change them for time to time.

**Comment by quanglam2807** [comment]
If you're using WebCatalog Engine, then this behavior is already there: https://github.com/webcatalog/webcatalog-engine/blob/master/public/windows/main.js#L154 (unless something's not working). 

If you're using other engines like Chrome or Firefox, there's not much we can do as the behavior is not controlled by WebCatalog.

**Comment by edmundlaugasson** [comment]
I used WebCatalog Engine and it seemed, that there was difference, where I started the app created by WebCatalog - from desktop, taskbar. Although I set up size, position, when started from desktop, these were not set when started from taskbar. But well, if it is done, then it is. Thank you!

**Comment by quanglam2807** [comment]
> I used WebCatalog Engine and it seemed, that there was difference, where I started the app created by WebCatalog - from desktop, taskbar. Although I set up size, position, when started from desktop, these were not set when started from taskbar. But well, if it is done, then it is. Thank you!

That sounds a bug. If it keeps occurring , please let me know

**Comment by edmundlaugasson** [comment]
Used exact Google Drive spreadsheet document URL to create custom app at Linux Mint 20 with Cinnamon desktop remotely over AnyDesk connection. Couldn't repeat it for now locally - created extra additional app with [public Google Drive document](https://docs.google.com/spreadsheets/d/1XUqTZ3eyf8OoQTE5N-YFD6Mdg_aO0fj6bDGWSS8eCtw/edit?usp=sharing) and it always maintained window size properly regardless, where started (main menu, desktop, taskbar, directly from WebCatalog app).

**Comment by quanglam2807** [comment]
Can you check `~/.config/App Name` to see if there's a file named `window-state.json`. The window position & size are stored there.

**Comment by edmundlaugasson** [comment]
Yes, the file is there and contains position and name data, also at that remote computer.

**Comment by 4yourithing** [comment]
i have macbook pro m1 with dual monitor setup. whenever i open my menubar app, the window opens on the top left of the display. if i move the window then click menubar icon to close it, the next time it opens it is still at top left. it used to stay put before this new setup.
