### ISSUE TITLE
feature: reduce installation size

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1240]
# Feature Request
**Specifications:**
- App Version: 27.3.0
- OS: Linux, but applies to all OSes

**Description:**

Currently ~218 MB per installed icon takes storage space. Perhaps it would be possible to keep containerized approach, when the rendering engine is downloaded at once but used for all installed apps. Then also updating the rendering engine is much easier, simpler, faster.

E.g. there is [Ice](https://github.com/peppermintos/ice) - outdated but very lightweight. It allows to use same browser in the system. It is not hard to use necessary parameters in case of used web browser to ensure isolation. Also --app parameter in case of Chromium or similar to ensure application mode, hide window unnecessary elements.

**Additional Context**

Yet another serious problem is, that WebCatalog doesn't recognise installed Flatpak or other containerized apps and even doesn't allow to browse manually. E.g. Chromium is nowadays mostly installed via Flatpak, Snap or similar (#1241 ).

**Comment by quanglam2807** [comment]
If you're using any browser engine options other than WebCatalog Engine, the implementation of WebCatalog is the same as Ice and doesn't need much space. 

Regarding WebCatalog Engine, it's possible to follow the same approach to save space (WebCatalog used to follow that implementation in early versions). Still, it leads to some problems (one of key ones is that it prevents generated apps to fully function with all features). So for now, it's better to live with the file sizes.

**Comment by edmundlaugasson** [comment]
That is probably so. Even to use incognito, it will share that incognito mode among other incognito windows. Anyway, currently in containers era the browsers are not recognized anyway. Let's hope, that also videoconference and similar websites will also work.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
