### ISSUE TITLE
feature: detect also Flatpak, Snap, AppImage, other versions of web browsers

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1241]
# Feature Request
**Specifications:**
- App Version: 27.3.0
- OS: Linux

**Description:**

WebCatalog doesn't recognise installed Flatpak or other containerized apps and even doesn't allow to browse manually. E.g. Chromium is nowadays mostly installed via Flatpak, Snap or similar.
Web browser can be also in binary format or even something else. As long as it is in path-defined folders (e.g. ~/local/bin/ , ~/bin/ , etc.), then it should be recognized.

**Additional Context**

This could help in turn to reduce also installation size of apps (#1240 ).

**Comment by quanglam2807** [comment]
WebCatalog detects browser installations on Linux by checking if these browser commands can be launched through CLI: https://github.com/webcatalog/webcatalog-app/blob/master/main-src/libs/is-engine-installed.js. So if the browsers are put properly in path-defined folders, WebCatalog will be able to detect them. If it doesn't then please let me know more details. Probably, it fails to detect certain edge cases.

**Comment by edmundlaugasson** [comment]
Flatpak, Snap, AppImage can be run but with a bit different commands.
E.g. Chromium at appropriate .desktop file:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding org.chromium.Chromium @@u %U @@`
This can be run also:
`flatpak run org.chromium.Chromium`
AppImages are just files to execute, users will put them folder ~/.local/bin/ , which is in path.
Certainly anyone can install browsers via different ways and see, where and what files comes and what they contain.

**Comment by quanglam2807** [comment]
Do you have any suggestions to resolve this?

**Comment by edmundlaugasson** [comment]
/var/lib/flatpak/exports/share/applications is *.desktop files location for system-wide Flatpak apps. By default Flatpak installs system-wide. However, when using --user flag, then also user-wide installations are possible (~/.var/ folder). Certainly both should be detected. Same might apply also other packaging systems.

I guess it should be investigated, where each packaging system will store its *.desktop files and try to run there. Also pay attention system- and user-wide installation possibilities. Certainly web browser detection among found *.desktop files should be implemented.

Another and perhaps more sustainable solution is to use direct command to determine installed browser.
E.g. in case of Flatpak something like that:
```
$ flatpak list --app --columns=application|grep -i chromium
# if installed, the output will be: org.chromium.Chromium
# Here you can use output signal detection
# if no errors, it means there is output, then package is installed
# manual check echo $? gives value 0
# 
# e.g. in case of
# flatpak list --app --columns=application|grep -i firefox
# if there is no output, then output differs from 0, then there was an error, it means no output, it means that browser is not installed
# manual check echo $? gives value 1 (usually but no matter, what number - all these are errors for IF-sentence)
#
if [ $? -eq 0 ]; then
  flatpak run $(flatpak list --app --columns=application|grep -i chromium)
  exit 0
else
...
fi
```
Same approach should be repeated in case of every supported browser and in case of every packaging system ([Flatpak](https://flatpak.org/), [Snap](https://snapcraft.io/), [AppImage](https://appimage.org/), [APT](https://wiki.debian.org/Apt), [Zero Install](https://0install.net/), [Bintray](https://bintray.com/), etc.).
In some cases it might be easy: Flatpak has own commands, AppImage files should be reside at well known folders:
- .desktop files:
  - system-wide: /usr/share/applications/
  - user-wide: ~/.local/share/applications/
-  binaries
   - system-wide: /usr/local/bin/
   - user-wide: ~/.local/bin/ or ~/bin/

You can check [Filesystem Hierarchy Standard, FHS](https://refspecs.linuxfoundation.org/fhs.shtml) to get information, where installed files could be.
I guess it should be also announced to user, where to put apps in order to ensure they could be find.

Definitely it would be good to allow also browse manually the location(s), where to search web browsers, perhaps even allow to define, which packaging formats should be searched.

Simplest way could be to allow user specify, where exact browser is installed in case of every browser, what user wants to use as an alternative. Certainly WebCatalog should be able to use that browser regardless of used packaging system. Perhaps require that user have to specify, what packaging system has been used. Then it will be ensured, that browser can be used. It could be even just compiled binary and no other fancy packaging system :)

**Comment by quanglam2807** [comment]
Supporting all these edge cases of app installations would be too much to bear with. Still:

> Simplest way could be to allow user specify, where exact browser is installed in case of every browser, what user wants to use as an alternative. Certainly WebCatalog should be able to use that browser regardless of used packaging system. Perhaps require that user have to specify, what packaging system has been used. Then it will be ensured, that browser can be used. It could be even just compiled binary and no other fancy packaging system :)

For this, you can just assign command aliases for the browsers. 

For example:
```
alias chromium-browser='flatpak run org.chromium.Chromium'
```

I'll try to update the docs.

**Comment by edmundlaugasson** [comment]
Bash aliases work in CLI and not elsewhere.

**Comment by quanglam2807** [comment]
But WebCatalog's implementation is based on Bash so I suppose it would work?

**Comment by edmundlaugasson** [comment]
sounds like so

**Comment by edmundlaugasson** [comment]
Currently it is problematic to guess, what should be the alias name to be created... E.g. _chromium_ or _chromium-browser_ didn't work... So, I would say that using bash alias is not working. Certainly I rerun _source ~/.bash_aliases_ command, checked manually whether the new alias is recognized or not and then also rerun webcatalog from same command-line session. So the alias was definitely recognized by system, but seems that not by webcatalog.
