### ISSUE TITLE
bug: Docked app icon on the taskbar changes to Chrome if the engine is Chrome

### ISSUE THREAD

**Issue by andoro** [webcatalog/webcatalog-legacy#1244]
# Bug Report
**Specifications:**
- App Version: Version v27.3.0
- OS: Windows

**Description:**
When the selected browser engine is the Webcatalog default, the app icon is good when you dock the app on the taskbar.
When I select a different like Chrome, after docking, the app icon changes to Chrome. It's not app specific and it's true for all apps and I the app icon changes to the selected browser engine respectively.

**Steps to Reproduce:**
1. Install an app like Google Maps
2. Select Chrome as browser engine
3. Right click on the taskbar icon
4. Select to dock it
5. --> App icon changes to Chrome

**Comment by quanglam2807** [comment]
Thank you for reporting, @andoro . I'm sorry but this is a limitation of Chromium-based engines and it's likely that I'd be able to fix it.
