### ISSUE TITLE
feature: geolocation API support

### ISSUE THREAD

**Issue by andoro** [webcatalog/webcatalog-legacy#1245]
# Bug Report
**Specifications:**
- App Version: Version v27.3.0
- OS (macOS, Windows, Linux): Windows

**Description:**
Google Maps, Waze would need my current location, but they can not get it when the browser engine is set to Webcatalog default

**Steps to Reproduce:**
Install app such as Google Maps, Waze, launch the app. You the message that location is not available.

**Additional Context**
none

**Comment by scottrbaxter** [comment]
I'm having a similar issue with other engines, e.g. Vivaldi and Brave on macOS. I tried using the default "Dark Sky" app in WebCatalog, and enabled geolocation in the app's Chromium/Vivaldi settings, and added Vivaldi to System Preferences/Security & Privacy/Location. Still cannot find my location on darksky.net in the WebCatalog created app(s).

**Comment by quanglam2807** [comment]
It turns out that WebCatalog Engine is currently not supporting geolocation web API. Google Chrome relies on Google API to get user location (properly from IP address). I'll try to add support for this.
