### ISSUE TITLE
Spell checker shows no suggestions in secondary languages

### ISSUE THREAD

**Issue by benjaminfrombe** [webcatalog/webcatalog-legacy#1246]
this bug seems to be back. in macOS 11.1 I have English set as main language and dutch as second. The incorrect spelling is detected but not suggestions are made on right click in dutch, only English suggestions ...

_Originally posted by @benjaminfrombe in https://github.com/webcatalog/webcatalog-app/issues/142#issuecomment-749447218_

**Comment by benjaminfrombe** [comment]
interesting observation: using webkit as a browser the right suggestions are being made, but there is no indication of a spelling error (no red line under the wrong spelled word).

**Comment by quanglam2807** [comment]
> this bug seems to be back. in macOS 11.1 I have English set as main language and dutch as second. The incorrect spelling is detected but not suggestions are made on right click in dutch, only English suggestions ...
> 
> _Originally posted by @benjaminfrombe in [#142 (comment)](https://github.com/webcatalog/webcatalog-app/issues/142#issuecomment-749447218)_

WebCatalog (through Electron) is using macOS's native spellchecker API (https://www.electronjs.org/docs/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses) so I'm not sure what went wrong. I'll try to test this more carefully to see what happens.

**Comment by quanglam2807** [comment]
> interesting observation: using webkit as a browser the right suggestions are being made, but there is no indication of a spelling error (no red line under the wrong spelled word).

Currently, Apple doesn't open up the API to enable spelling error underline in WebKit so there's not much we can do. Ref: https://stackoverflow.com/questions/57532801/swift-wkwebview-continuous-spell-checking

**Comment by benjaminfrombe** [comment]
> > this bug seems to be back. in macOS 11.1 I have English set as main language and dutch as second. The incorrect spelling is detected but not suggestions are made on right click in dutch, only English suggestions ...
> > _Originally posted by @benjaminfrombe in [#142 (comment)](https://github.com/webcatalog/webcatalog-app/issues/142#issuecomment-749447218)_
> 
> WebCatalog (through Electron) is using macOS's native spellchecker API (https://www.electronjs.org/docs/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses) so I'm not sure what went wrong. I'll try to test this more carefully to see what happens.

Hi, any update on this issue ? Because of this I'm forced to use chrome as engine, which is far from ideal for several known reasons ...

**Comment by benjaminfrombe** [comment]
ping ...

**Comment by quanglam2807** [comment]
Since the app no longer supports WebKit engine, I'll close this issue for now. If you have additional questions or feedback, feel free to contact us at https://webcatalog.io/contact/
