### ISSUE TITLE
bug: scrollbar is not clickable

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1247]
# Bug Report
**Specifications:**
- App Version: Latest
- OS macOS:

**Description:**
Can't click and drab the vertical scrollbar on Mac, it just drags the whole window.

**Steps to Reproduce:**
System Preference > General > Show scroll bars > Always

**Additional Context**
It used to work. Seems to be a similar issue to when the sidebar is showing and you can't click on areas of the web page in the left within a width area equivalent to the sidebar.

**Comment by quanglam2807** [comment]
Thank you Marcus. I fixed this by using macOS native scroll bar instead of custom one. Hope it works well for you.

**Comment by marcusquinn** [comment]
Strange, still does the same and looks the same.

Note that my setting ""System Preference > General > Show scroll bars > Always" isn't the default (it used to be but then Apple likes hiding stuff for their minimalism UI aims)

**Comment by quanglam2807** [comment]
> Strange, still does the same and looks the same.
> 
> Note that my setting ""System Preference > General > Show scroll bars > Always" isn't the default (it used to be but then Apple likes hiding stuff for their minimalism UI aims)

<img width="1392" alt="Screen Shot 2020-12-25 at 9 10 25 AM" src="https://user-images.githubusercontent.com/1548835/103114429-19ae7d00-4691-11eb-8731-6430268dc27b.png">
This is how it looks on my Mac. 

Can you check if the apps are updated to WebCatalog Engine 13.1.x, Marcus? If they are and the scroll bar still doesn't work properly, then I'll need to dig deeper into this.

**Comment by marcusquinn** [comment]
Seem to be:

![image](https://user-images.githubusercontent.com/6428977/103140810-3f647200-46e3-11eb-8dc5-edc0095c0f4c.png)


It's when you click on the actual scrollbar on the right and drag up and down, it drags the whole window too.

**Comment by quanglam2807** [comment]
Is it fixed in the latest version, @marcusquinn? It works on my Mac. Hopefully, it will work on yours as well.

**Comment by marcusquinn** [comment]
OK, sort-of fixed. With a chance experiment I tried hiding and then showing the sidebar, and then it works.

Then if I quit and restart the app that has a sidebar it happens again and have to hide & show the sidebar again to get the scrollbar click & draggable again.

I"m on a 4k/retina monitor if that might make any difference?

**Comment by marcusquinn** [comment]
Same issue if hiding and showing the app/window. the scrollbar isn't clickable then and I need to hide and show the sidebar to get it clickable again.

**Comment by marcusquinn** [comment]
This sees to be fully fixed now - I can't tell which release it was fixed but all good on the latest release - thank you again!

**Comment by quanglam2807** [comment]
@marcusquinn Awesome! Thank you for letting me know. It's likely a bug in Electron so it was fixed after I upgraded to the latest version of Electron.
