### ISSUE TITLE
not showing all apps.

### ISSUE THREAD

**Issue by haakonemil** [webcatalog/webcatalog-legacy#125]
Only showing 9 apps and not reloading and it is not possible to search for new apps. What is the problem?

**Comment by quanglam2807** [comment]
At the moment, the catalog of WebCatalog 13 only you has 9 apps. I'll add more in the future. I'm not sure what you mean by "it is not possible to search for new apps"

**Comment by haakonemil** [comment]
My friend got the same, but he can download facebook, HubSpot and everything... It looks the same but I don't know

**Comment by quanglam2807** [comment]
I'm adding back apps to the catalog. Stay tuned!
