### ISSUE TITLE
bug: Difficulty clicking stuff in discord

### ISSUE THREAD

**Issue by EggY0lk** [webcatalog/webcatalog-legacy#1254]
# Bug Report
**Specifications:**
- App Version: Version v27.4.0
- OS (macOS, Windows, Linux): Windows 10

**Description:**

Difficulty clicking stuff in discord
**Steps to Reproduce:**

1. Open discord using webcatalog.
2. Attempt to click on stuff

**Additional Context**

Video of the bug: https://files.catbox.moe/4bvbo8.mp4
Discord version: 
![Discord_8z0NjFIXCo](https://user-images.githubusercontent.com/27946481/103140857-bbcc7480-4726-11eb-8f1e-0c531e124ba6.png)

**Comment by quanglam2807** [comment]
Thank you for reporting. This is probably fixed with https://github.com/webcatalog/webcatalog-engine/pull/247 (WebCatalog Engine 13.2.0). If it's still not fixed, please let me know

**Comment by EggY0lk** [comment]
> Thank you for reporting. This is probably fixed with [webcatalog/webcatalog-engine#247](https://github.com/webcatalog/webcatalog-engine/pull/247) (WebCatalog Engine 13.2.0). If it's still not fixed, please let me know

Thx for the reply.
I have updated and it is still not fixed.
![Discord_0rdv7zWgTL](https://user-images.githubusercontent.com/27946481/103152864-f8e84380-47c6-11eb-9d15-ac1e34753517.png)

**Comment by quanglam2807** [comment]
Bug confirmed. Temporary fix: Discord > Preferences > Advanced > Use system title bar and borders > Switch on

**Comment by EggY0lk** [comment]
> Bug confirmed. Temporary fix: Discord > Preferences > Advanced > Use system title bar and borders > Switch on

Thank you. The temporary fix works. Looking forward to a patch in the future. 
P.S. Thanks for the amazing app. Helps me circumvent the lag that discord(the desktop app) gives me.
