### ISSUE TITLE
bug: GMail multisite app will crash when trying to edit current workspace after adding it

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1257]
# Bug Report
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

When adding new workspace and trying to edit it shortly after adding, the app will crash.

**Steps to Reproduce:**

* add GMail as app - will be multisite by default
* add new workspace
* open Workspaces->Edit Current Workspace from appropriate pull-down menu
* app will be closed forcibly

**Additional Context**

Plus licence was applied.
Similar crash appeared in case of self-created multisite Google Drive app, where tried to edit Preferences. Similar multiste app like current GMail, would be appreciated also in case of other apps, where could be multiple apps exist.

**Comment by quanglam2807** [comment]
Can you record a video of how to reproduce it?

**Comment by edmundlaugasson** [comment]
This happens, when you are not logged in. I can record a video, but perhaps is enough that fact.

**Comment by quanglam2807** [comment]
I honestly couldn't reproduce this.
