### ISSUE TITLE
feature: improve resize app content and fix shortcut keys

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1258]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Would be good to have ability to resize app content as these are web apps and usually websites can be resized using CTRL + mouse scroll, also CTRL + +/-. Current zoom in shortcut key is quite unusual. 
**issue 1:** Also the minus key works only as dash button next to right shift and not when choosing from numpad. 
**issue 2:** The = key is not where chosen layout says, but only as on US keyboard. In my layout there is ? key and not =...
**issue 3:** Although CTRL+0 worked to reset size when choosing from horizontal bar. When trying to use numpad, it doesn't work

**Actually, horizontal scroll would be also expected to work: SHIFT+mouse scroll.** Will not file separate feature request, but scrolling horisontally in such way is widely used among many apps. This applies also in case of viewing documents. Currently sometimes it works, sometimes not (e.g. MS Office 365 Word document preview).

**Additional Context**

Used GMail multisite app to test it.
Here could be already three bugs filed but instead of them I filed feature request to rewrite zooming in WebCatalog as it is expected usually in web browsers.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
