### ISSUE TITLE
feature: allow convert single site app to multisite (without losing single site authentication)

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1259]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently is needed to delete current app and install new one as multisite and do all the authentication. Would be good to convert via 3-dot menu the app into multisite and keep current single site authentication.

**Additional Context**

Quite often appears, that there are more accounts connected with same service. Too much hassle with deleting, installing, authenticating - it could be easily solved via the feature currently proposed.

**Comment by quanglam2807** [comment]
We probably won't work on this. But singlesite apps can work similarly to multisite apps (spaces) as well. You just need to right-click on the add button and choose Add Custom Account or choose Accounts > Add Custom Account from the menu.
