### ISSUE TITLE
feature: allow convert multisite app into single site apps, keeping its authentication

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1260]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

While proposing single site -> multisite (#1259 ), then also vice versa is useful. In such case all workspaces will be separate single site apps.

**Additional Context**

This could easily happen, when situation changes and workspaces needed to be separated.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
