### ISSUE TITLE
feature: allow combine single site apps into one multisite

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1261]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS:  Linux

**Description:**

When splitting multisite app into single site apps (#1260 ), there might be needed to combine these single site apps again into one multisite app. This differs from converting just one single site app into multisite one (#1259 ) as in current case these single site apps already exist and just needs to be combined into one multisite app.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
