### ISSUE TITLE
feature: allow search from preferences

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1262]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently is not possible to search from preferences dialog. There are quite a lot choices and would be useful to allow to search among options.

**Comment by marcusquinn** [comment]
I wish for this every time I go to Preferences. Ideally in a way that those that like to stay on the keyboard can do without needing to go to the mouse.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
