### ISSUE TITLE
feature: allow choose multi-, single site when creating app

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1263]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently GMail has nice multisite feature, where next workspaces will be added with GMail logo, URL, etc. Would be very much appreciated to allow choose in case of every app, whether it would be added as single site or multisite app.
Current workaround is to create manually multiste app, but then you need to define each workspace independently. Would be nice to allow to clone certain workspace inside multisite app - that could compensate at least some extent, that we don't have ability to create such nice multisite app with predefined options like currently GMail is.
It would be good to choose, whether multisite will be all on same chosen service (e.g. Google Drive) or there would be created each workspace by manually choosing app there. Also allowing to clone existing workspace would be appreciated.

**Additional Context**

Quite often people have multiple accounts in same service.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
