### ISSUE TITLE
feature: allow encrypted email extensions

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1264]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently is not possible to send an encrypted email.
There are many web-based apps available:
* [Mailvelope](https://www.mailvelope.com/) - best one as it is free open-source and supports also newest encryption algorithms (including ECC), also virtually any web-based email service as missing ones can be easily added manually, please [see also alternatives](https://alternativeto.net/software/mailvelope/). Integrates well also in GMail and others.
* [Flowcrypt](https://flowcrypt.com/) - GMail-specific, not fully free
* [Encipher](https://encipher.it/) - free open-source, allows to encrypt any text in any window, can be used also in case of email

Mailvelope would be most appreciated, but would be good to allow to choose, which one to use.

**Additional Context**

Unencrypted email is basically public one... So, in nowadays post-Snowden era the email encryption is a must-be basically...
This applies to any email app you have or will have.

**Comment by quanglam2807** [comment]
Currently, extension support is experimental so it doesn't work with a lot of extensions. We'll work to improve it.

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
