### ISSUE TITLE
feature: allow change app name also after adding it

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1266]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently after adding app, there is not possible to change its name. Then I need to delete it and add with fixed name. Quite often is needed to change name to be more appropriate according used account in it.

**Additional Context**

This applies to both single- and multisite apps, no matter how they are created.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
