### ISSUE TITLE
feature: SVG icon as workspace icon

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1267]
# Bug Report
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

SVG-image is not displayed when set as workspace icon.

**Steps to Reproduce:**

* create multisite app
* add SVG image as icon
* it will not be displayed

**Additional Context**

SVG requires much less space than PNG, that is currently normally displayed.

**Comment by quanglam2807** [comment]
How did you use SVG icon as workspace icon? I don't think the selection dialog allows you to do so?

**Comment by edmundlaugasson** [comment]
Just browsed the .svg picture from computer. Nothing extraordinary.

**Comment by quanglam2807** [comment]
But the dialog is supposed to disallow that. Probably a Linux’s limitation.
