### ISSUE TITLE
Creating custom app with default icon fails

### ISSUE THREAD

**Issue by hkroger** [webcatalog/webcatalog-legacy#127]
I tried to add MS teams with URL https://teams.microsoft.com/ and creation of custom app fails on macOS Mojave. 

The error is "Failed to install Microsoft."

**Comment by quanglam2807** [comment]
Thank you for reporting. It seems like you tried to create an app with the default icon and it failed. I've fixed the bug v13.0.2. Please give it a try!

**Comment by hkroger** [comment]
This fixed that problem. There are other problems why it doesn't seem to work but oh well...

**Comment by quanglam2807** [comment]
@hkroger Would you mind giving me more details? I’d love to fix the other issues as well.

**Comment by hkroger** [comment]
@quanglam2807 two main problems:
1) App wanted to access my keychain which is already a bit weird because it should be comparable to browser to sign something or so and it asked for the access multiple times and browser probably shouldn't access keychain? Anyways, I could "fix" this by always allowing it to access it which I just personally didn't like.
2) After allowing it to access keychain, the site actually never loaded fully. Authentication page and so on opened fine but when the teams app (after authentication) should have opened, I just had an empty screen / page. I don't know if this a compatibility problem or something else but for me it's a bit difficult to see what the actual problem is. Also if you don't have access to MS Teams it is probably not possible to see the problem because this happens after the authentication.

**Comment by quanglam2807** [comment]
@hkroger Thanks a lot for letting me know. I'll fix both issues ASAP. The first one happens because I forgot to set the app not to ask for signing. The second one happens because Microsoft also has an Electron app for Mac so the site mistakes the app created with WebCatalog with their own app.
