### ISSUE TITLE
feature: allow hibernate workspace/app (also schedule it)

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1270]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Currently quite often multisite apps will consume a lot of resources, even nothing happens. E.g. creating multisite app with 6 different Google Drive apps will for time to time consume 30%....50%, randomly even more CPU (8-core). The laptop fan will start working.
It would be helpful to allow to hibernate workspaces, that are not currently in use (currently only possible, when relaunching app but workspace rehibernating not possible). Also schedule it, e.g. if not used during certain amount of time, these workspaces will be hibernated automatically in certain app. This would be workaround until overall resources consuming is solved (e.g. also webcatalog/chromeless#91 ). Sounds like built-in browser causes that enormous resources consuming, but who knows. As there is an issue of using custom browsers (#1268 ), then it is not so easy, if possible at all.
This all might happen even in case of single site app. Even here would be appreciated to schedule to hibernate app if not used for certain amount of time.

**Additional Context**

Especially important in case of multisite apps.

**Comment by quanglam2807** [comment]
Thanks for the feedback. This feature is now available in current version.
