### ISSUE TITLE
feature: Use apps offline

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1271]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**
Ability to use apps offline, this is possible?

**Comment by quanglam2807** [comment]
WebCatalog is based on Chromium. So if the web app utilizes Web Workers https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers to work offline, then it will work offline in WebCatalog and most browsers.
