### ISSUE TITLE
feature: Option for add font

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1272]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**
Option for add font like inject JS and CSS code in Developers

**Comment by F50Ci37Y** [comment]
I managed to change the font by injecting this CSS code.

[font.css.zip](https://github.com/webcatalog/webcatalog-app/files/6538611/font.css.zip)

**Comment by quanglam2807** [comment]
Thank you for the feedback. But because this is achievable with current implementation, we'll not work on adding the feature.
