### ISSUE TITLE
feature: Separate proxy inputs

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1273]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**
Please separate proxy inputs: username, password, port, protocol, address

**Comment by quanglam2807** [comment]
Thank you for this. This has been implemented with https://github.com/webcatalog/neutron/pull/390

Username & Password are not supported due to technical limitation. Please use IP authorization instead.
