### ISSUE TITLE
feature: Show download progress

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1274]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**
Show download progress and speed and ability to pause, resume, cancel

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
