### ISSUE TITLE
feature: add custom block-list support

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1275]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**
Please add a section for ad-blocking and add block-list

**Comment by edmundlaugasson** [comment]
#1265 asks to support not only one add-on, but all of them...

**Comment by howyay** [comment]
I would like to see this along with #1265, but since implementing extensions would automatically enable the full feature of any extension, #1265 should be prioritized since we can then use uBlock Origin with custom block lists.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
