### ISSUE TITLE
feature: please support also running apps via CLI

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1277]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

One big need is also running apps via CLI. Not only CLI-based apps, but also GUI-based ones. As claimed at #1241 , the WebCatalog suppose to work via CLI, respecting even aliases - very good! It would act like regular *.desktop file used to. Usually we can use **x-terminal-emulator** alternative, e.g. we can check current status (which terminal is chosen):
`update-alternatives --display x-terminal-emulator`

Some examples of the need for CLI support:
* any kind of radiostation
`x-terminal-emulator -T "Radio Name" -e "mpv https://radio.com/playlist.m3u"`
... certainly instead of mpv can be used any other suitable CLI mediaplayer, that is installed in current system.
* sometimes we might need some scripting command:
sh -c "while true; do mpv --network-timeout=2 https://url.com/live/tv.m3u8; done"
* some example webcam tests
```
flatpak run org.videolan.VLC v4l2:///dev/video0
mplayer tv:// -tv driver=v4l2:device=/dev/video1
```
* run Jitsi Meet with exact address and with Flatpak version of Chromium (that was otherwise not recognized by WebCatalog)
`flatpak run org.chromium.Chromium --app=https://meet.jit.si/customname`
* run MS Windows apps via Wine or similar with appropriate profiles, environment variables, etc.
* watch or listen anything from own computer or via internet, using CLI-based mediaplayers, like mpv, mplayer, etc.
*  actually any GUI app can be run also via CLI in UNIX-like systems, so we can basically run anything from computer with specific parameters, additional files as arguments, etc.
* there are some additional services via CLI, e.g.
```
curl ipinfo.io #get current external IP
curl ipinfo.io/ip
curl ipinfo.io/hostname
curl ipinfo.io/city
curl ipinfo.io/region
curl ipinfo.io/country
curl ipinfo.io/loc
curl ipinfo.io/org
curl wttr.in/tallinn # get weather of certain city
curl v2.wttr.in/tallinn # another version of getting weather of certain city
curl v3.wttr.in/tallinn # yet another version of getting weather of certain city
```
* you can even order a pizza via CLI https://github.com/xxczaki/pizza-cli

**Definitely there should be possible to add additional environment variables BEFORE running app via CLI.** Sometimes CLI apps require specific environment variables in order to run properly. There could be just additional field for environment variables - every variable from new line. Sometimes these variables are needed just for that particular app. The rest of the app creation dialog could look like currently.
**Also there is a need to allow to define a shell with full path.** Sometimes we have multiple shells in UNIX-like systems and would like to create different apps in WebCatalog to run via different shells. Also these shells might need some environment variables before they will run properly.
**There might be need to run even script**, therefore there would be appreciated to allow to run even a script before or after the shell is started.
Result is similar as currently, just no built-in browser won't be needed. 

**Additional Context**

Quite often is running apps from CLI much easier and much more lightweight. It doesn't need built-in browser, which would consume ~218 MB per app. Anyway there could be used --incognito (or whatever else, that is appropriate for used browser) parameter to ensure private browsing, if needed. Also even WebCatalog doesn't recognize the Flatpak (or any other containerized or just binary on disk) web browser - via CLI it would be still possible to run it, even with full path if needed. As mentioned above, basically any app can be run via CLI in UNIX-like systems. Sometimes we need specific settings for apps, e.g. even custom icon, etc.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
