### ISSUE TITLE
bug: Gmail window can't be moved

### ISSUE THREAD

**Issue by Proggie** [webcatalog/webcatalog-legacy#1278]
# Bug Report
**Specifications:**
- App Version: WebCatalog Engine: 13.5.0
Electron: 11.1.1
Node: 12.18.3
Chromium: 87.0.4280.88

- OS (macOS, Windows, Linux): macOS 11.2 Beta (20D5029f)

**Description:**
Gmail window can't be dragged/moved. 

**Steps to Reproduce:**
Click on top of Gmail window and try to drag. Nothing happens.

**Additional Context**
If I first resize the window then moving/dragging the window will now work

**Comment by quanglam2807** [comment]
Thanks for reporting. This should be fixed in the latest version.
