### ISSUE TITLE
bug: occasionally app cannot be reopened due to running (crashed?) processes

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1279]
# Bug Report
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

Sometimes app cannot be opened due to running (crashed?) processes.

**Steps to Reproduce:**

* open app
* after using some time, close it
* try to reopen - it won't

**Additional Context**

It happened, when WebCatalog updated apps. Then some apps didn't open afterwards. Not sure, whether it is related with multisite apps or not, but current one was multisite one.
It is hard to always reproduce, but it happens. That prevents me to use WebCatalog for regular users, who cannot handle processes. Mostly and usually regular users don't know anything about processes and it is overwhelming to explain all this. Also it is not normal behaviour, that for time to time I need to close processes manually in order to reopen certain app. For me it is a bug, also for regular users. Actually there are many processes opened related to certain app, especially when it is multisite one. Currently signal 15 has been enough to close processes nice way.

**Comment by quanglam2807** [comment]
This is probably fixed in the latest version. If it still occurs, feel feel to contact us at https://webcatalog.io/contact/
