### ISSUE TITLE
feature: audio icon overlay

### ISSUE THREAD

**Issue by nblackburn** [webcatalog/webcatalog-legacy#1280]
# Feature Request

**Description:**
Show a overlay icon for workspaces that are playing audio. This makes it easier to identify where the sound is coming from.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
