### ISSUE TITLE
feature: view link before clicking it

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1281]
# Feature Request
**Specifications:**
- App Version: 27.4.0
- OS: Linux

**Description:**

For security reasons (but not only) it would be good to see the link before clicking on it.

**Additional Context**

Sometimes links can contain hidden redirections, etc., it would be good to discover it BEFORE clicking on it.

**Comment by quanglam2807** [comment]
when you hover on a link, the link is displayed a right bottom corner.
