### ISSUE TITLE
*HIGH PRIORITY* bug: WebCatalog deletes content of existing app support folders on macOS

### ISSUE THREAD

**Issue by leventeszmolka** [webcatalog/webcatalog-legacy#1284]
# Bug Report
**Specifications:**
- App Version: v27.4.0
- OS (macOS, Windows, Linux): macOS
- **Priority: HIGH**

**Description:**
WebCatalog clashes with the contents of existing app support folders in `~/Library/Application Support` and deletes them when adding and then removing a matching webapp.

**Steps to Reproduce:**

- For example if you have Chrome installed, Chrome stores its settings, profile, history, etc in the following folder: `~/Library/Application Support/Google/Chrome`
- Now, when I **install and then uninstall** the _Google_ webapp in WebCatalog, it removes the existing content of `~/Library/Application Support/Google`. This way I lost my complete Chrome profile, thankfully I was able to partially restore it from an earlier backup.
- The same thing happened when I installed and uninstalled the _Apple_ webapp. The content of the existing `~/Library/Application Support/Apple` folder has been deleted.

**Additional Context**

A possible solution would be to store WebCatalog related app support folders in a dedicated place, like `~/Library/Application Support/WebCatalog/`

**Comment by leventeszmolka** [comment]
@quanglam2807 After updating to v28.0.1 the issue reappeared. But this time it happens when I update an existing webapp, not when adding a new.

**Comment by quanglam2807** [comment]
By design, the new paradigm only applies to newly installed apps. It was a bug that this was applied to updated apps in the previous version.

**Comment by leventeszmolka** [comment]
I see, thanks for the explanation. Just tried adding a new webapp. It behaves almost like expected, but still creates a folder directly in `~/Application Support` with a single `Dictionaries` folder in it.
