### ISSUE TITLE
bug: Double-clicking on Google Drive.app doesn't bring it to the foreground 

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#1285]
# Bug Report
**Specifications:**
- App Version: Version 87.0.4280.141
- OS (macOS, Windows, Linux): Catalina

**Description:**
Just installed Google Drive (tabbed) and I was able to launch the app fine. However, if I open the WebCatalog Apps folder and double click "Google Drive.app" inside it, nothing happens. Doing this should bring the already open app to the forefront.

**Comment by quanglam2807** [comment]
Same as https://github.com/webcatalog/webcatalog-app/issues/1286
