### ISSUE TITLE
bug: No audio in VC and videos.

### ISSUE THREAD

**Issue by EggY0lk** [webcatalog/webcatalog-legacy#1291]
# Bug Report
**Specifications:**
- App Version:  Version v27.5.2
- OS (macOS, Windows, Linux): Windows 10

**Description:**

How the bug manifests: No audio when playing videos(this includes videos from links such as youtube/streamable). Cannot hear anyone in Voicechat nor can I hear the joining sound.

What the behavior would be without the bug: Able to hear sounds from videos and vc.

**Steps to Reproduce:**
1. Open discord with webcatalog.
2. Play a video that has audio/join vc.

**Additional Context**

Webcatalog discord version: 
![image](https://user-images.githubusercontent.com/27946481/104806222-f2227e80-5810-11eb-93cd-547836c7d441.png)

Discord webcatalog not found in windows volume mixer.

https://user-images.githubusercontent.com/27946481/104806331-a3291900-5811-11eb-8e9b-154d0c50225f.mp4

**Comment by quanglam2807** [comment]
@EggY0lk Can you check if the app has been muted accidentally? You can check it by going to "Hamburger button > Discord > Unmute/Mute". If you see "Unmute" menu item, it means the app is muted.

**Comment by EggY0lk** [comment]
> @EggY0lk Can you check if the app has been muted accidentally? You can check it by going to "Hamburger button > Discord > Unmute/Mute". If you see "Unmute" menu item, it means the app is muted.

Oh, they fixed it. It was muted this entire time and I did not notice haha. Thanks a lot.
