### ISSUE TITLE
bug: No icon

### ISSUE THREAD

**Issue by trentwiles** [webcatalog/webcatalog-legacy#1298]
# Bug Report
**Specifications:**
- App Version: v28.0.0-rc.2
- OS (macOS, Windows, Linux): Linux Mint 20

**Description:**
No icon.

**Steps to Reproduce:**
Install the app on Linux Mint 20.

**Additional Context**
![image](https://user-images.githubusercontent.com/59586759/104851844-73d3e400-58c5-11eb-8b29-79053046ed6f.png)

**Comment by quanglam2807** [comment]
Thanks for reporting. Does it happen with the main app or apps generated by WebCatalog?

**Comment by quanglam2807** [comment]
I can't reproduce the bug on Linux Mint 20 Cinnamon. What desktop environment are you using?
