### ISSUE TITLE
App uninstallation doesn't work correctly on Linux

### ISSUE THREAD

**Issue by sirweazel** [webcatalog/webcatalog-legacy#13]
I'm finding this application interesting. It's pretty cool. Thanks for the quick fix on the other issue (web links).  I've noticed that when you remove an added app (either custom or one from the list selection) it removes it from the webcatalog-lite GUI, but not from the desktop environment GUI (in my case gnome).  The files stay in the the /home/username/bin directory.

**Comment by quanglam2807** [comment]
Oops, I haven't written the code to uninstall on Linux. My bad.

https://github.com/quanglam2807/webcatalog/blob/master/public/libs/uninstall-app-async/index.js#L6

**Comment by sirweazel** [comment]
Thanks, works good. Great Job!
