### ISSUE TITLE
AppView uses too much resources 

### ISSUE THREAD

**Issue by JerzyRajkow** [webcatalog/webcatalog-legacy#130]
Hello, after installing the last version on macOS, webcatalog takes 60-70% of my CPU causing my computer to run awfully slow - the helpers for each app created inside webcatalog take approximately 14%of the CPU.

**Comment by quanglam2807** [comment]
Thank you very much for the feedback. I'll try to improve this ASAP.

**Comment by JerzyRajkow** [comment]
Have you already resolved the "too much resource" issue? I switched back to
the old version to be able to work until you sort this out so please tell
me when the new version will not be so resource hungry.


Wszystkiego dobrego / All the best,

**Comment by quanglam2807** [comment]
This is addressed partly with #186. But because of resource-consuming nature of Chromium and Electron, I cannot do anything further. I'll close this issue at the moment.

**Comment by dave-redfern** [comment]
@quanglam2807 The 13.4.0 update has much lower resource utilisation. I just updated and rebuilt the apps I have, and what was previously running around 30% CPU is at idle now most of the time. Maybe there was an issue in a specific build of Chromium you were referencing? At any rate; it's much improved! 😁

**Comment by quanglam2807** [comment]
@dave-redfern Thank you for letting me know. I think it was because I let the loading animation to run indefinitely in background. It also might be because of improvements in Electron and Chromium. Nevertheless, if it works, it works :) I'm glad.
