### ISSUE TITLE
bug: Apps detected as threat by Windows Defender

### ISSUE THREAD

**Issue by randomarno** [webcatalog/webcatalog-legacy#1300]
# Bug Report
**Specifications:**
- App Version: v28.0.0
- OS (macOS, Windows, Linux): Windows 10

**Description:**
Since update to v28, I can't launch or create apps, they are detected as threats by Microsoft Windows Defender.

Report in Windows Defender : 
Threat detected : Behavior:Win32/Execution.IF!ml
Details : This program is dangerous and it executes commands from an attacker.
(translated from French).

![image](https://user-images.githubusercontent.com/77626973/104927517-d3072680-59a1-11eb-9105-5343d721cc98.png)

**Comment by randomarno** [comment]
![image](https://user-images.githubusercontent.com/77626973/104927499-cc78af00-59a1-11eb-97a8-ab275d76d75a.png)

**Comment by quanglam2807** [comment]
Thank you for reporting. Have you resolved the problem?

**Comment by randomarno** [comment]
No, I tried installing previous version, but it does not allow me to create new apps (must be updated first). No solution for now.

**Comment by quanglam2807** [comment]
I'm sorry for this. I'll try to investigate this and fix it ASAP.

**Comment by quanglam2807** [comment]
I just tested the app on Windows 10. It seems like everything still works normally. WebCatalog 28 didn't change the way the app works significantly so I think it must be something else that causes this.

Indeed, the folder showed in the screenshot is what WebCatalog creates when creating new app. It's likely that Windows Defender's machine learning model mis-detects WebCatalog as malicious. 

Reference: 
- https://reddit.com/r/rust/comments/kn67xu/windows_defender_detects_virus_in_rust_crate/
- https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Behavior:Win32/Execution.A!ml&ThreatID=2147735815

Is it possible for you to whitelist the app? If possible, can you submit the case to Microsoft for reviewing?

**Comment by randomarno** [comment]
I can whitelist the created app, but it needs to be done for every new app. Workaround is ok, but complicated to generalize.

**Comment by randomarno** [comment]
Issue is no longer present in v28.0.1. Thanks !
