### ISSUE TITLE
bug: 28.0.0 update wiped out self-created multisite apps, othes logged out

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1303]
# Bug Report
**Specifications:**
- App Version: 28.0.0
- OS: Linux

**Description:**

Lots of apps were resetted after upgrading WebCatalog

**Steps to Reproduce:**

- have installed some prior version of WebCatalog than 28.0.0
- have configured some manually multisite apps, e.g. Google Drive with multiple accounts
- upgrade to WebCatalog 28.0.0
- when opening logged in apps - these are logged out; multisite apps are just empty and all sites needs to be added, configured again..

**Additional Context**

It happened right away after WebCatalog update was done.

**Comment by quanglam2807** [comment]
It was a bug in WebCatalog Engine. Please update all your apps to WebCatalog Engine v14.2.1. All your app data will be recovered.
