### ISSUE TITLE
feature: Hotkey to activate app

### ISSUE THREAD

**Issue by d4hines** [webcatalog/webcatalog-legacy#1312]
# Feature Request
**Specifications:**
- App Version: 28.0.2
- OS (macOS, Windows, Linux): All platforms

**Description:**
I'd like to be able to activate WebCatalog apps with hotkeys (e.g. Ctrl+Alt+R for Roam or Ctrl+Alt+S for Slack). I tried to do this with AutoHotKey but it wasn't trivial (at least not for a novice in AHK like me). Such a hotkey should be easy to set up with Electron's built-in API though: https://www.electronjs.org/docs/api/global-shortcut

**Additional Context**

**Comment by d4hines** [comment]
For any interested, I created a (really ugly) workaround in AutoHotkey for this purpose. In preferences, scroll down to the bottom and check "Use System Titlebar and boarders" and then run some code like in this commit: https://github.com/d4hines/home/commit/af4da0ebf39d2b6a5c7f28643f8a8ff01754c1f4

It disables the close button entirely, at which point `WinActivate` works normally.

**Comment by d4hines** [comment]
Oh, I just noticed you can enable Node/Electron API's in the custom javascript. A much better solution would be just run some custom Javascript that uses the API I linked. I'll post that later if/when I go that route.

**Comment by quanglam2807** [comment]
Thanks for the feedback. This is now possible. You just need to go to Preferences > Window & Menu Bar >  Define a keyboard shortcut to open the app quickly
