### ISSUE TITLE
bug: App Icon does not update when changing for custom app

### ISSUE THREAD

**Issue by eitch** [webcatalog/webcatalog-legacy#1318]
# Bug Report
**Specifications:**
- App Version: v28.2.0
- OS (macOS, Windows, Linux): Pop-OS/Ubuntu

**Description:**
Changed the icon/image for a custom app. The menu bar icon does not get updated. Even after a repair it does not change. In the WebCatalog App under Installed list, the Image is changed.

**Steps to Reproduce:**
Change Image of a custom app

**Additional Context**
None

**Comment by quanglam2807** [comment]
For the icon to change, you need to restart the custom app. Have you tried that?
