### ISSUE TITLE
bug: Not open app from pinned icon on windows task panel

### ISSUE THREAD

**Issue by restructor1** [webcatalog/webcatalog-legacy#1320]
# Bug Report
- App Version: 28.2
- Windows 10

**Description:**
When i set run in background and show tray icon, i can not open the app from pinned (!) icon on windows task panel.

**Steps to Reproduce:**
Pin app to windows task panel, close the app, then try to open in from windows task panel. It is no reaction.

**Comment by quanglam2807** [comment]
This app is probably fixed now.
