### ISSUE TITLE
bug: Unable to install anything

### ISSUE THREAD

**Issue by CStafford-14** [webcatalog/webcatalog-legacy#1322]
# Bug Report
**Specifications:**
- App Version: 28.2.0
- OS (macOS, Windows, Linux): macOS

**Description:**

When trying to install anything, I keep getting an error saying "Failed to install (app)". Also, when I click install, what I assume is a progress circle that doesn't do anything. Hovering over it gives a tooltip that says "Checking requirements..."
**Steps to Reproduce:**

Click "Install" on any app
**Additional Context**

Tried this with the following apps:
https://webcatalog.app/catalog/messages
https://webcatalog.app/catalog/cloudflare
https://webcatalog.app/catalog/the-church-of-jesus-christ-of-latter-day-saints

**Comment by quanglam2807** [comment]
I'm sorry for the problem. Can you check if there's a folder called WebCatalog Apps in your home directory?

**Comment by CStafford-14** [comment]
The issue was probably something to do with my network. Other apps started following suit after a reboot, so I just shut it down and left it for a while.I come back and everything is normal, and it works now...On Feb 1, 2021 6:03 PM, Quang Lam <notifications@github.com> wrote:
I'm sorry for the problem. Can you check if there's a folder called WebCatalog Apps in your home directory?

**Comment by quanglam2807** [comment]
That's great! Thank you for letting me know.
