### ISSUE TITLE
feature: swipe back and forth with Magic Mouse?

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1323]
# Feature Request
**Specifications:**
- App Version: 28.2.0
- OS: macOS 10.13.6

**Description:**
Hello, I am a simple user of WebCatalog. I like so much about this app, but one thing is very annoying: I cannot swipe back and forth with my Magic Mouse like in Safari (in installed/created apps). Each time I have to go the menu to click the commands for Back & Forward.

Is it possible to add a normal one-finger-mouse-swipe feature to this nice app?
Best wishes
Jens

**Comment by quanglam2807** [comment]
Hi Jens,
Currently, two-finger swiping navigation is not possible because of this https://github.com/electron/electron/issues/2683.

For now, you can navigate with three-finger swipe instead.
<img width="872" alt="Screen Shot 2021-01-31 at 12 37 42 AM" src="https://user-images.githubusercontent.com/1548835/106363732-f4322480-635c-11eb-8b33-de378ad18bbe.png">

I'll close this issue because it's a duplicate of https://github.com/webcatalog/webcatalog-app/issues/966

**Comment by ghost** [comment]
Oh, that's not what I meant. I know, that swiping with trackpad is possible.

I meant swiping with MOUSE does not work – neither with one, two nor three fingers.
How come?

**Comment by quanglam2807** [comment]
> Oh, that's not what I meant. I know, that swiping with trackpad is possible.
> 
> I meant swiping with MOUSE does not work – neither with one, two nor three fingers.
> How come?

I'm not sure if this is related to the trackpad issue or not. But if this is related to mouse behavior, please wait for https://github.com/webcatalog/webcatalog-app/issues/1324 to be resolved. It might make navigation work with Magic Mouse as well.

**Comment by ghost** [comment]
That would be wonderful – thank your for your support!!

**Comment by ghost** [comment]
Hello Quang,

I would like asking you, if swiping back and forth via Magic Mouse will come in the near future?
I miss this feature very much – thanks.

Best wishes
Jens

**Comment by quanglam2807** [comment]
Hi Jens,
Thank you for reminding me about this. I'm sorry but the other change doesn't seem to work with Mac at all. We'll try to find a way to support Magic Mouse ASAP (currently, it's not possible as we couldn't find the APIs).

Best,
Quang

**Comment by ghost** [comment]
Hi Quang,
thanks for sharing your thoughts. Hopefully Magic Mouse support is coming in the future. Switching online content back and forth within WebCatalog without a trackpad is very annoying (with mouse – going to Menubar, clicking back/forward; keyboard-commands seem not to work).
Best wishes
Jens

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
