### ISSUE TITLE
feature: Add mouse AppCommand navigation support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1324]
See https://www.electronjs.org/docs/api/browser-window#event-app-command-windows-linux

**Comment by d4hines** [comment]
This would be a nice feature. If anyone is on Windows, I have a workaround in AHK that remaps the buttons to the respective shortcuts in Web Catalog, filtering out Brave (which still needs the normal functionality from the buttons). Replace `brave.exe` with your browser.
```
#IfWinNotActive ahk_exe brave.exe
XButton2::^]

#IfWinNotActive ahk_exe brave.exe
XButton1::^[
```
