### ISSUE TITLE
bug: failed to load applications list on webcatalog

### ISSUE THREAD

**Issue by skydiver** [webcatalog/webcatalog-legacy#1325]
# Bug Report
**Specifications:**
- App Version: v28.2.0
- OS (macOS, Windows, Linux): macos Big Sur

**Description:**
Failed to load applications list on webcatalog and multiste apps.

**Steps to Reproduce:**
Open webcatalog, goto disover tab.

**Additional Context**
In WebCatalog app:
![Screen Shot 2021-01-31 at 16 54 47](https://user-images.githubusercontent.com/578784/106396161-08b9ff80-63e5-11eb-8c59-ab9c0e2d5c2d.png)
In a multisite electron app: 
<img width="420" alt="Screen Shot 2021-01-31 at 16 53 34" src="https://user-images.githubusercontent.com/578784/106396171-153e5800-63e5-11eb-84d0-40587f8b9f7f.png">

I was trying to manually open the url to fetch the apps (and see if it's my netwokr), but i cannot find on the source code.

**Comment by skydiver** [comment]
UPDATE: looks like the problem is that needs to access to an url ending in`swiftype.com` which was blocked as a "recognized tracking service"

**Comment by quanglam2807** [comment]
The only thing I can suggest to unblock swiftype.com. WebCatalog is using it as the backend. You can learn more about it here: https://swiftype.com/

**Comment by skydiver** [comment]
Thanks @quanglam2807 

Yes, it how i've resolved, just wanna let a note in case someone else has similar troubles.
