### ISSUE TITLE
bug: Microsoft To Do requires re-login upon launching every time

### ISSUE THREAD

**Issue by Gowee** [webcatalog/webcatalog-legacy#1326]
# Bug Report
**Specifications:**
- App Version: Version v28.2.0
- OS (macOS, Windows, Linux): Linux

**Description:**

When launching the Microsoft To Do app, it asks for signing in even if an account has been signed in previously.

**Steps to Reproduce:**

1. Install Microsoft To Do from the WebCatalog app.
2. Launch the Microsoft To Do app and click the "Get Started" button to log in with a MS account.
3. Close the app.
4. Re-launch the app. 

**Expected behaviour:**
The app automatically goes to the actual web app.

**Actual behaviour:**
The app launches to the welcome page where a re-login is required.

**Additional Context**

N/A

**Fix:**
Replace the app URL https://todo.microsoft.com with https://to-do.live.com/tasks/?app .

(Not actually a bug about the WebCatalog app. But I cannot find a more suitable place to submit the issue.)

**Comment by quanglam2807** [comment]
Thank you, @Gowee. I've updated the URL.
