### ISSUE TITLE
Unable to identify app data dirs by app IDs

### ISSUE THREAD

**Issue by MacAppSuggestions** [webcatalog/webcatalog-legacy#1327]
Webcatalog introduced a mega downgrade feature with no interest to revert it

For more information check https://perma.cc/WF89-H5WA

**Comment by quanglam2807** [comment]
I understand.

Feel free to let me know if you have any other questions or feedback.

Best,
Quang
Founder | WebCatalog Ltd

**Comment by quanglam2807** [comment]
Reddit URL: https://old.reddit.com/r/appledatahoarding/comments/lb0uzw/if_you_are_using_webcatalog_for_your_hoarding/?rapplestyleroadtopetabytebackup

**Comment by quanglam2807** [comment]
With v28.3.0, app name will be appended to app id if app name is shorter than 17 characters (technical limitation). If app name is longer than that, number will be used.
