### ISSUE TITLE
Allow WebCatalog to remain pinned

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#1337]
Per the title of this post. Right now it's not possible to leave WebCatalog window open if you switch to another app. I don't know about other users but there are times when this would be helpful—and less annoying.

Please consider this.

**Comment by quanglam2807** [comment]
Thanks for the feedback. You mean when the window is attached to menu bar on macOS? If so, you can enable this behavior in Preferences > General > Keep attached window always on top.

**Comment by project-guru** [comment]
I cannot find any setting that says "Keep attached window always on top".

If the intention is for this single setting to do both, then that would be a bad idea. Maybe you can add "Keep attached window always on top" as a separate setting. This way, users can control both separately.

Thanks!

**Comment by quanglam2807** [comment]
<img width="872" alt="Screen Shot 2021-02-07 at 11 59 28 PM" src="https://user-images.githubusercontent.com/1548835/107153517-8f9c4880-69a0-11eb-8dfe-4e1a42b83b21.png">

> If the intention is for this single setting to do both, then that would be a bad idea. Maybe you can add "Keep attached window always on top" as a separate setting. This way, users can control both separately. 

May you clarify this? I'm a bit confused.

**Comment by project-guru** [comment]
I'm confused too. Your preferences window looks different than mine. I just did a "check for updates" and I have the latest (28.4.0)

![2021-02-07_11-13-36](https://user-images.githubusercontent.com/18504294/107153920-aa85a300-6935-11eb-8de5-09e845baf3f9.png)

Maybe that feature is only available in the Pro version?

**Comment by quanglam2807** [comment]
Ah I see, you meant the main WebCatalog app. I got it :D. Thank you for taking time to explain it to me.

I'll add the option in the next update.

**Comment by project-guru** [comment]
Great Thanks. You're the best!
