### ISSUE TITLE
bug: unable to op app based on chromium engine from dock

### ISSUE THREAD

**Issue by benjaminfrombe** [webcatalog/webcatalog-legacy#1338]
# Bug Report
**Specifications:**
- App Version:28.4.0
- OS (macOS, Windows, Linux): OSX 11.2

**Description:**
when trying to start an app in the OSX dock I get a chrome error 6.
Starting the app from the applications folder or within the WebCatalog app (not from the dock) DOES work.

**Steps to Reproduce:**
create a chrome-based app, start it, right-click keep in dock. Close it. click the dock icon.

**Additional Context**

<img width="656" alt="image" src="https://user-images.githubusercontent.com/5367552/107152301-73c88080-6967-11eb-8a1c-ea1286ec63ab.png">

**Comment by quanglam2807** [comment]
Thank you for reporting, @benjaminfrombe. I'm sorry but this is a limitation of Chromium-based engines and it's likely that I'd be able to fix it.
