### ISSUE TITLE
Add setting to custom installation process to choose browser engine

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#1339]
There are times when changing the browser engine is needed. It is cumbersome to go into preferences every time in order to change the browser engine when creating a custom app.  

Kindly consider allowing this setting to be changed during custom app installation.

**Comment by quanglam2807** [comment]
Thanks for the feeback, @project-guru. This is already available.

<img width="712" alt="Screen Shot 2021-02-08 at 8 07 47 AM" src="https://user-images.githubusercontent.com/1548835/107165211-cb590180-69e4-11eb-926b-23479170269f.png">

**Comment by project-guru** [comment]
Missed that one. Thanks and sorry for overlooking it!
