### ISSUE TITLE
Google Drive doesn't load file lists properly

### ISSUE THREAD

**Issue by JaminZ22** [webcatalog/webcatalog-legacy#134]
Google drive app will load menus and search bar, but will not populate files/folders. Executing a search will display files, but they will not open on click.

Occurs in Webcatalog 13.0.2 and 12.8.1 (both pre-defined app and custom app instances)

![screen shot 2019-01-30 at 4 43 03 pm](https://user-images.githubusercontent.com/47034131/52014734-532edb80-24ae-11e9-85bb-7735b467641d.png)

**Comment by JaminZ22** [comment]
@quanglam2807 - This issue seems to have popped back up for me. Drive forced me to log in again and upon login I got the same behavior as I had before.

**Comment by quanglam2807** [comment]
It seems like there were some changes on Google side. It'll be fixed in the next update. https://github.com/electron/electron/issues/16587#issuecomment-461806009

**Comment by rohanraviyadav** [comment]
Following , I am also facing same issue from 8th Feb 2019, Google drive file list is not opening with Chrome with selenium.

**Comment by quanglam2807** [comment]
@rohanraviyadak Would you mind checking which version of Google Drive app you’re running?
