### ISSUE TITLE
Google Chrome tabbed applications keep displaying [Setup automatic updates]

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#1340]
Every time I launch a Google Chrome tabbed application I click the blue button to allow automatic updates. However, if I quit the app and launch again,  the [Setup automatic updates] button appears again. This never ends.

![2021-02-07_10-53-55](https://user-images.githubusercontent.com/18504294/107153635-3ac2e880-6934-11eb-9d73-45c3f1f14c6c.png)

Any Idea why?

- App Version: Implementation 2.6.0
- OS (macOS, Windows, Linux): Mac OS

**Comment by quanglam2807** [comment]
Thank you for reporting, @project-guru . I'm sorry but this is a limitation of Chromium-based engines and it's likely that I'd be able to fix it.
