### ISSUE TITLE
bug: JavaScript error when opening sidebar or navigation bar

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#1341]
# Bug Report
**Specifications:**
- App Version: v28.4.0
- OS (macOS, Windows, Linux): Windows

**Description:**
When trying to view sidebar or navigation bar (menu -> view -> show sidebar / show navigation bar), a javascript error displays in a popup:
![image](https://user-images.githubusercontent.com/12695083/107499663-24fc3000-6b8d-11eb-8120-0c8477f44dcc.png)

**Steps to Reproduce:**
menu -> view -> show sidebar / show navigation bar

**Additional Context**
no related issues found

**Comment by quanglam2807** [comment]
Thanks for reporting, @floriandierickx. Does this bug occur when you change other app preferences?

**Comment by floriandierickx** [comment]
No, other menu items work as expected (preferences, notifications, ...). It is only the sidebar and navigation bar at first sight. Most of the apps seem to have the problem, except one (Gmail).

**Comment by quanglam2807** [comment]
Thank you for info, @floriandierickx. I'll try to test this out. It's pretty strange because the function used by that menu item is widely used across the app so I still don't know why it only breaks for sidebar/navigation bar.

**Comment by quanglam2807** [comment]
Btw, have you tried switching on sidebar/navigation bar in the app preferences window? Does it work?

<img width="872" alt="Screen Shot 2021-02-10 at 6 26 31 PM" src="https://user-images.githubusercontent.com/1548835/107504292-a83d7600-6bcd-11eb-9db9-038b3531456f.png">

**Comment by floriandierickx** [comment]
It gives the same error when switching the levers, but they do switch. After restarting ('restart for changes to take effect'), the sidebar/navigation bar is not visible.
