### ISSUE TITLE
bug: Update or installation of new apps fails with error

### ISSUE THREAD

**Issue by jottr** [webcatalog/webcatalog-legacy#1342]
# Bug Report
**Specifications:**
- App Version: Version v28.4.0
- OS (macOS, Windows, Linux): 

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H512
```

- Intel chipset

**Description:**

After upgrading Webcatalog to the most recent version it is impossible to update nor install new apps.

![image](https://user-images.githubusercontent.com/2744198/107580215-85738780-6bf6-11eb-83f7-93817e460f09.png)

The same issue occurs when trying to create a custom app.

**Comment by thejudge22** [comment]
This seems to be happening with the WebCatalog engine.  Trying to install an app with one of the browser engines (tested with Firefox and Chrome) works as expected.

**Comment by quanglam2807** [comment]
I'm sorry for the problem. The bug has been resolved (it was a server-side bug).
