### ISSUE TITLE
feature: option to select default browser for external links

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#1343]
# Feature Request
**Specifications:**
- App Version: v28.4.0
- OS (macOS, Windows, Linux): Windows

**Description:**
It looks like most apps do open external links in the default browser (selected within Windows settings), but some apps (example: tt-rss) do open links inside the WebCatalog-framework in an external screen (without url-bar). Would there be an option to override these settings, and choose which browser to use from within WebCatalog?

**Additional Context**
[https://github.com/webcatalog/webcatalog-app/issues/5](https://github.com/webcatalog/webcatalog-app/issues/5)
[https://github.com/webcatalog/webcatalog-app/issues/467](https://github.com/webcatalog/webcatalog-app/issues/467)

**Comment by quanglam2807** [comment]
Thanks for the feedback. This is now possible with the Internal URLs and Externals URL settings.
