### ISSUE TITLE
feature: Paying with cryptocurrencies for a license

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1353]
# Feature Request
**Specifications:**
- App Version: 28.7.0
- OS (macOS, Windows, Linux): macOS, Windows, Linux

**Description:**
This is not really related to the app itself but to the license (WebCatalog Plus).
Would it be possible to add a purchase option with cryptocurrencies like XMR?

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
