### ISSUE TITLE
feature: Dark Mode everywhere.

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1354]
# Feature Request
**Specifications:**
- App Version: 28.7.0
- OS (macOS, Windows, Linux): macOS, Windows, Linux

**Description:** 
### There are some browser extensions that allow to use dark mode everywhere so would it be possible to add an option to switch on dark mode on every single website?
**Additional Context**
\--/

**Comment by quanglam2807** [comment]
Thanks for asking. This feature is already available:
<img width="872" alt="Screen Shot 2021-02-20 at 2 09 29 PM" src="https://user-images.githubusercontent.com/1548835/108587269-5216c280-7385-11eb-942c-fe473a1af31e.png">
