### ISSUE TITLE
Screen time / Digital wellbeing feature

### ISSUE THREAD

**Issue by grumphus** [webcatalog/webcatalog-legacy#1361]
Hello. First of all, thanks so much for the continued development. Really impressed with the features and how stable the current versions are.

I was wondering if it's possible to implement a feature where you can optionally assign a time period (example 2 hours) or a time frame (example Every 8:00am to 5:00pm) where the app is disabled. iOS uses a similar feature called Screen Time. Then you can override the block using the already existing App Lock feature. Thought it would be a nice complement to that feature.

Should be great for work at home folks who want to avoid distractions.

Thank you!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
