### ISSUE TITLE
Can't download attachment from Gmail app

### ISSUE THREAD

**Issue by Proggie** [webcatalog/webcatalog-legacy#1368]
# Bug Report
**Specifications:**
-WebCatalog Engine: 15.13.2
-Electron: 11.3.0
-Node: 12.18.3
-Chromium: 87.0.4280.141

**Description:**
When I click on the arrow to download an attachment when viewing an email (when hovering over the attachment icon, or when viewing the attachment), the attachment does not download and instead a sound is heard (like when an error occurs). There is no obvious error visible though. In addition the app's icon shows a progress bar, filled to 100%.

**Steps to Reproduce:**
1. Open an email containing an attachment, such as a PDF.
2. Hover over the attachment's icon/previous
3. Click on the arrow icon to download the attachment.

**Additional Context**
When opening gmail in Safari and clicking on the download icon, it opens a modal asking to confirm that you want to allow downloading from this site.

**Comment by quanglam2807** [comment]
Thank you for reporting this. The bug has been fixed with https://github.com/webcatalog/webcatalog-engine/pull/368
