### ISSUE TITLE
bug: Webex add-on in Google Calendar does not authenticate

### ISSUE THREAD

**Issue by boris-bc** [webcatalog/webcatalog-legacy#1373]
# Bug Report
**Specifications:**
- App Version: v29.0.0
- OS (macOS, Windows, Linux): macOS

**Description:**
WebEx add-on in the Google Calendar app cannot authenticate. It opens a pop-up window where I need to allow it in my google account. I do that, the pop-up is closed and the Webex plugin is not authenticated. The add-on is already allowed for the account and works just fine in Safari. 

**Steps to Reproduce:**
- Install Google Calendar with the WebCatalog Engine.
- Login into the Google Account (mine already has the Webex add-on installed)
- Open the Webex add-on - it shows as not authenticated
- Press the "Get Started" button - it opens a pop-up to allow the add-on (which is already allowed for this account)
- Allow the add-on - the pop-up closes but the Webex add-on does not authenticate

**Additional Context**
To me it looks like some issue with cookies.

**Comment by quanglam2807** [comment]
Currently, extension support is experimental so it doesn't work with a lot of extensions. We'll work to improve it.

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
