### ISSUE TITLE
feature: API Call to reset badge count from inside tab?

### ISSUE THREAD

**Issue by PolCPP** [webcatalog/webcatalog-legacy#1375]
I'm seeing that some apps don't reset its badge count due to its title not being (N) - Text. I did try to manually set up an event to change the title to (0) + document.title to reset the badge whenever i tab in or out into it. It does not seem to work. Is there any way to reset the badge from inside each app/container?

**Comment by quanglam2807** [comment]
Let's move the discussion to https://github.com/webcatalog/webcatalog-app/issues/1425
