### ISSUE TITLE
Application can't be opened + Failed to update

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#1376]
# Bug Report
**Specifications:**
- App Version: Version v29.0.0

- OS (macOS, Windows, Linux): macOS Catalina 10.15.7

**Description:**
For some reason today I restarted my computer. All applications I had open before I restarted automatically launched upon restart (normal Mac behavior). However, I had to quit one of the applications that I created using WebCatalog but when I tried to relaunch it I kept getting errors. I tried the usual spotlight method as well as double-clicking directly on the app in the hard drive, as well as try to launch it directly within WebCatalog. None worked. I keep getting error: 
![2021-03-10_11-45-54](https://user-images.githubusercontent.com/18504294/110673277-3178a600-8196-11eb-840b-1aac873cb221.png)

Interestingly, the icon on the HD looks different: 
![image](https://user-images.githubusercontent.com/18504294/110669851-64209f80-8192-11eb-9777-9527c5ea7678.png)

When I try to repair the app in WebCatalog: 
![2021-03-10_11-48-07](https://user-images.githubusercontent.com/18504294/110673513-7d2b4f80-8196-11eb-83b4-5a4cc3b979ea.png)

The thing is, this is not the first time I see this happen. I didn't report this before because I wasn't sure if I was doing anything wrong. 

Also, in case it matters:
- The app in question here was created as a clone and with Google Chrome Tabbed as the engine.
- I am not sure but I think yesterday I might have clicked on DO NOT ASK AGAIN when I launched the app in question here. Here's a screenshot of what I am referring to: 
![2021-03-10_11-19-53](https://user-images.githubusercontent.com/18504294/110670170-b497fd00-8192-11eb-951c-99c026ce2127.png)

Additional Question: Why when I quit and relaunch do the apps I create don't reopen all the tabs I had open in the previous session? 

Sorry for the long post.

Thanks!

**Comment by project-guru** [comment]
UPDATE: I just created a new app to replace the one not working (as indicated in my original post) and that one also has problems.  How to reproduce:
1. Create app using Chrome Tabbed
2. open a couple of tabs
3. install my chrome extensions 
4. Quit the app
5. Relaunch the app
6. App unexpectedly quit and no longer launches.

**Comment by quanglam2807** [comment]
I'm sorry but this is a limitation of Chromium-based engines. I can't do anything to fix this.

**Comment by project-guru** [comment]
So there's no way to create a tabbed app that supports chrome extensions?

**Comment by quanglam2807** [comment]
I’m afraid not. I’m sorry.
