### ISSUE TITLE
bug: Stuck at checking update

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1379]
# Bug Report
**Specifications:**
- App Version: version v30.0.0
- OS (macOS, Windows, Linux): Linux ElementaryOS 

**Description:**
I stuck at checking update 
![stuck](https://user-images.githubusercontent.com/68975726/111076365-fcb67700-8526-11eb-97d2-3d8039510ff8.png)

**Comment by quanglam2807** [comment]
I'm sorry for the problem. But I couldn't reproduce it at all on Ubuntu 20.04. Would you mind restarting the computer and trying again, please?
