### ISSUE TITLE
bug: Some Installed Apps No Longer Have Title Bar

### ISSUE THREAD

**Issue by progkix** [webcatalog/webcatalog-legacy#1382]
# Bug Report
**Specifications:**
- App Version: WebCatalog 30.1.0
- OS (macOS, Windows, Linux): Fedora 32 X64

**Description:**
Normally, apps will open with a title bar allowing preferences to be set and minimize/maximize/exit buttons

**Steps to Reproduce:**
Installed latest AppImage, installed apps with updates and opened Google Hangouts. No title bar.

**Comment by antailyaqwer** [comment]
Confirm, have the same problem on Manjaro Linux (arm64) with KDE.
