### ISSUE TITLE
feature: add window.prompt() API support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1387]
See https://github.com/electron/electron/issues/472

**Comment by pjebs** [comment]
If you want consistency across different OS's, just use https://electron.guide/electron-alert/

It's powered by SweetAlert2.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
