### ISSUE TITLE
feature: Discord Stream in 1080/60fps

### ISSUE THREAD

**Issue by Pedrw** [webcatalog/webcatalog-legacy#1393]
# Feature Request
**Specifications:**
- App Version: 30.2.1
- OS (macOS, Windows, Linux): Windows

**Description:**
I have Nitro and i just changed to this application, but after trying it for a few times, i can't seen to find any Screenshare settings to change from 720p to 1080p and 60fps, so i would recommend adding

**Comment by quanglam2807** [comment]
Thanks for reporting. This seems like a limitation of the Electron framework which WebCatalog is based on. So for now, the only thing we can do is to wait for Electron to be improved.
