### ISSUE TITLE
bug: Discord screenshare doesn't detect fullscreen applications

### ISSUE THREAD

**Issue by Pedrw** [webcatalog/webcatalog-legacy#1394]
# Bug Report
**Specifications:**
- App Version: 30.2.1
- OS (macOS, Windows, Linux): Windows

**Description:**
When you try to screenshare a program, it doesn't show any fullscreen applcations, i tried using other programs, but it simply doesn't detect them

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
