### ISSUE TITLE
feature: I would love to see the possibility to change app icons to my own costumer icons

### ISSUE THREAD

**Issue by johnnysrubin** [webcatalog/webcatalog-legacy#1396]
# Feature Request
**Specifications:**
- App Version:
- OS (macOS, Windows, Linux):

**Description:**

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for suggesting this. You can already do this with custom apps: https://help.webcatalog.app/article/21-can-i-create-custom-app. You can also clone any apps in the catalog to make custom apps and customize the icons.

**Comment by johnnysrubin** [comment]
wow I can't believe I missed that. Thank you very much
