### ISSUE TITLE
bug:  Udemy app does not play videos.

### ISSUE THREAD

**Issue by George-Anton-Tarazi** [webcatalog/webcatalog-legacy#1398]
# Bug Report
**Specifications:**
- App Version: 16.5.1
- OS : Windows 10

**Description:**
As soon as you open the app and go to any course the video player does not work, you will be prompted to download the video, but the quality you get from the download is 144p and you can't possibly see anything.

**Steps to Reproduce:**
Play any video.

**Additional Context**
Works fine if you use the Chrome engine.

**Comment by George-Anton-Tarazi** [comment]
I found out that some videos work and others don't, for example there is a course called " Flutter & Dart - The Complete Guide [2021 Edition]" by Maximilian Schwarzmüller, where on lesson 15 for example everything works fine, but on lesson 17 the videos don't work, if you look at the HTML for both lectures you will notice that the src link for lecture 17 is missing from the video tag and it's the same for the rest of the course, hope this helps you more in dealing with it, is there anything I can do to help you debug it? 

Note: all lectures in that course work fine on the chrome engine / any web browser

**Comment by quanglam2807** [comment]
Thanks for reporting this, @TheRealGio. This is probably because WebCatalog doesn't support WidevineDRM on Windows (technical limitation). We'll try to find a solution for this ASAP.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
