### ISSUE TITLE
bug: After several days additional account tabs in an app stop functioning

### ISSUE THREAD

**Issue by timm-mwp** [webcatalog/webcatalog-legacy#1406]
# Bug Report
**Specifications:**
- App Version: 31.2.1 (a versions prior to this)
- OS : MacOS 10.15.4

**Description:**

I have several Web Applications  (Jira, Confluence, Outlook) - which are configured to have multiple tabs in the sidebar (you seem to call them accounts). In most cases I have 5 or 6 of these so I can see multiple Jira project or multiple email mailboxes. I notice that after a few days (possibly even a week), that if I leave the application open and suspend/unsuspend my laptop eventually the 3,4th account stops working (normally the first 2 seem to function).  By not working - they go blank and a refresh won't work, neither will pasting a new url in the enabled url bar. The first 2 tabs normally work, and if I create a new tab it works, but the existing ones are dead. However - if I restart the application, those tabs will start working again.

**Steps to Reproduce:**
Create a Jira app, and add 4 or 5 tabs, and then use it for several days

**Additional Context**
![image](https://user-images.githubusercontent.com/65404874/114735691-589a3880-9d3d-11eb-9f25-3fdbd2e56d51.png)

I also notice that the about window opens blank when this happens (in fact the first time it doesn't open at all), as does the notifications window. The devTools window also doesn't work either. Possibly this is some sort of memory leak?

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
