### ISSUE TITLE
feature: widevine support to use apps like Spotify

### ISSUE THREAD

**Issue by gingerr** [webcatalog/webcatalog-legacy#1407]
# Feature Request
**Specifications:**
- App Version: 31.2.1
- OS: macOS

**Description:**
First of all, thank you very much for realizing and offering this OpenSource alternative to Apps like Unite which can't be used in an enterprise context. I'm currently evaluating Webcatalog for my work use to improve the struggle with many tabs from different contexts. Ive seen you have removed widewine apps from the catalog when removing the other browser engines going from v30 to v31. Are you planning to support widewine with the electron approach so apps like Spotify can be used?

Thank you!

**Comment by gingerr** [comment]
Never mind. Found this subject in your FAQ and read through the linked material. What a struggle, thanks for linking that.

**Comment by quanglam2807** [comment]
Widevine DRM is now supported in the latest version 🍡

**Comment by gingerr** [comment]
Oh what, what a suprise, I did not expect this. Ive updated right away, added Spotify and it works like a charm! Thank you for making this possible!! 🚀  

This help article is then outdated now 👍 
https://help.webcatalog.app/article/11-does-webcatalog-support-paid-streaming-services

**Comment by quanglam2807** [comment]
Thank you, @gingerr! I've removed the article.

**Comment by gingerr** [comment]
You got an new lifetime customer 😀
