### ISSUE TITLE
bug: Dark Reader for Google Chat is broken after the latest update

### ISSUE THREAD

**Issue by boris-bc** [webcatalog/webcatalog-legacy#1414]
# Bug Report
**Specifications:**
- App Version: 31.4.0
- OS (macOS, Windows, Linux): macOS 10.15.7

**Description:**
I was using the Dark Reader switch with the Google Chat app and it looked great. After the update of WebCatalog to 31.4.0, the option is unusable, it puts dark fonts on dark background and the chat windows remain unchanged (white background). System theme is dark.

**Steps to Reproduce:**
Switch on the Dark Reader setting in Appearance for Google Chat app.

**Comment by boris-bc** [comment]
![image](https://user-images.githubusercontent.com/63061368/116894235-1c6a4180-ac32-11eb-86dd-dfda8ce3afa4.png)

**Comment by Ryderjj89** [comment]
Can confirm that this is broken on Windows as well, even on version 33.1.0. Makes it unusable for those who prefer dark mode.

**Comment by boris-bc** [comment]
> Can confirm that this is broken on Windows...
I only run it on macOS. For macOS I can confirm it still happens with version v33.1.0 on macOS 10.15.7.

**Comment by quanglam2807** [comment]
Dark Reader will be upgraded to the latest version in the next update, hopefully, that'd fix this bug. If it still occurs, please feel a bug report at: https://github.com/darkreader/darkreader
