### ISSUE TITLE
bug: Facebook app not posting sometimes

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1416]
# Bug Report
**Specifications:**
- App Version: 31.4.0
- OS (macOS, Windows, Linux): Linux Mint 20.1 Cinnamon with all updates

**Description:**

When posting in Facebook, sometimes announcing, that something bad happened and not posting at all. It will never succeed. When reloading app, even that does not help. Usually closing app will solve, sometimes even not that.

**Steps to Reproduce:**

Hard to reproduce, as it happens occasionally. But nothing extraordinary - just try to post in Facebook.

**Additional Context**

64-bit Linux Mint

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
