### ISSUE TITLE
feature: list view of apps

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1417]
# Feature Request
**Specifications:**
- App Version: 31.4.0
- OS (macOS, Windows, Linux): Linux

**Description:**

Would appreciate the list view of apps. Currently only big blocks. Especially in case of _Discover_ or _Categories_ section, there are plenty of apps. Certainly also installed apps could be long list. Would be good to have more compact overview - as list and not big blocks. I guess it would load also faster.

**Additional Context**

Even in list view there could be a small favicon in front of each site. Even in case of _Spaces_ section.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
