### ISSUE TITLE
feature: make new sidebar optional

### ISSUE THREAD

**Issue by nilswald** [webcatalog/webcatalog-legacy#1419]
# Feature Request
**Specifications:**
- App Version: 31.4.0
- OS (macOS, Windows, Linux): mac

**Description:**
I would prefer the new sidebar to be optional, at least show only icons. I only use the "updates" view, sometimes preferences (but mostly via menu or keyboard shortcut). For that I find it takes way to much screen real estate.

**Additional Context**

**Comment by quanglam2807** [comment]
Thanks for the feedback, @nilswald. I've made the sidebar more compact. Is it good enough?

**Comment by nilswald** [comment]
in 32? Can't spot the difference here.

**Comment by quanglam2807** [comment]
<img width="1552" alt="Screen Shot 2021-05-10 at 3 08 55 PM" src="https://user-images.githubusercontent.com/1548835/117626776-a883e800-b1a1-11eb-96bf-0ce4c70420a4.png">

Still not narrow enough?

**Comment by nilswald** [comment]
I am using it more like this so when I opened it the first time after the update it gave me a sidebar and two columns and I thought 'what!?'  ;). But it is really not a big deal as I only open WC for updates or creating a new app. 

![Bildschirmfoto 2021-05-10 um 11 56 27](https://user-images.githubusercontent.com/1010163/117642463-985f0f00-b187-11eb-903e-e2d1eb06bc67.png)

**Comment by quanglam2807** [comment]
<img width="1035" alt="Screen Shot 2021-05-13 at 12 55 13 AM" src="https://user-images.githubusercontent.com/1548835/118021868-e5103900-b385-11eb-8727-f88330b50b86.png">

How about this, @nilswald?

#1423

**Comment by nilswald** [comment]
Thank you, that is awesome!
