### ISSUE TITLE
Spell checker doesn't allow suggestions

### ISSUE THREAD

**Issue by JaminZ22** [webcatalog/webcatalog-legacy#142]
In previous versions, right-clicking on a misspelled word would bring up the menu allowing you to choose from a set of suggestions, add to dictionary, etc. Wondering if this feature could be added to v13.x?

**Comment by quanglam2807** [comment]
I'll need to do some investigations. The new version uses the same implementation as the old one so I don't know what went wrong.

https://github.com/quanglam2807/webcatalog/blob/master/template/public/preload/view.js#L21

**Comment by quanglam2807** [comment]
Are you still using the old version? If so, can you upload a few screenshots of how the spellchecker works in the old version?

**Comment by JaminZ22** [comment]
The spellchecker in the old version underlines the misspelled word once a space is placed after it. The new version behaves the same way. However, in the old version, you can right-click/two-finger click on the misspelled word and it will give you spelling suggestions and some other options. The screenshot below is the right-click menu from the old version. Let me know if you need more details or screenshots of anything.

<img width="250" alt="screen shot 2019-02-09 at 9 31 50 pm" src="https://user-images.githubusercontent.com/47034131/52528727-3a46d700-2cb3-11e9-8172-f59eaca717f5.png">

**Comment by YetiWalker** [comment]
I have this issue as well on MacOS 10.14.2.  Right clicking on underlined word gives no suggestions or menu.

**Comment by quanglam2807** [comment]
<img width="912" alt="screen shot 2019-02-12 at 7 17 21 pm" src="https://user-images.githubusercontent.com/1548835/52679514-f6dea980-2efa-11e9-80d6-e6ec3fd716fc.png">
I had the bug, too. I'll try to fix it this week.

**Comment by benjaminfrombe** [comment]
this bug seems to be back. in macOS 11.1 I have English set as main language and dutch as second. The incorrect spelling is detected but not suggestions are made on right click in dutch, only English suggestions ...
