### ISSUE TITLE
bug: Problem in diagrams.net file saving

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1422]
# Bug Report
**Specifications:**
- App Version: Version 17.2.0
- OS: Linux

**Description:**
in diagrams.net app when I try to save the file shows this error:
`Error saving file: The request is not allowed by the user agent or the platform in the current context.`

**Steps to Reproduce:**
Install diagrams.net app
Choose Device Storage
Try to save the diagram file

**Additional Context**
![image](https://user-images.githubusercontent.com/20030910/117996406-61d7ee80-b357-11eb-8016-d013d6c33886.png)

**Comment by quanglam2807** [comment]
Thanks for reporting. This bug will be fixed in the next update.
