### ISSUE TITLE
bug: Badge not working for Yahoo! mail

### ISSUE THREAD

**Issue by johnhcc** [webcatalog/webcatalog-legacy#1424]
# Bug Report
**Specifications:**
- App Version: 32.0.0
- OS (macOS, Windows, Linux): macOS 10.14.6 and 11.3.1

**Description:**
An 'unread badge' never appears for Yahoo! Mail unread mail.

**Steps to Reproduce:**
Set a message as unread. Badge does not appear.

**Additional Context**
This is likely just a simple regex fix. Unlike Gmail, the title bar in Yahoo! Mail is set to `(# unread) text` instead of just `(#) text`.  Using some CSS magic, I've confirmed that if Yahoo! Mail used the Gmail format, everything would work fine. Since it doesn't, WebCatalog just needs to make a change to the regex that pulls out the unread count.

**Comment by quanglam2807** [comment]
Thank you, @johnhcc. Let's move the discussion to https://github.com/webcatalog/webcatalog-app/issues/1425

**Comment by johnhcc** [comment]
For the record, the following JS injection is a temporary work-around. Looking forward to the more permanent solution in #1425.

```
setInterval(updateTitle, 5000);

function updateTitle() {
  document.title = document.title.replace(' unread','');
}
```
