### ISSUE TITLE
Only hide window when close button is clicked

### ISSUE THREAD

**Issue by JaminZ22** [webcatalog/webcatalog-legacy#143]
If reopening a "closed" window (not one that's been "quit", just "closed"), the app reloads completely as if the window was quit. In v.12.x, a closed window would reopen to its last known state and not require a full reload. Is this by design or something that can be adjusted?

**Comment by bricoleurbanism** [comment]
I'd also like to see this functionality. Ideally, I would like the window to pop back open (without reloading) right away when the app was brought back into focus.

**Comment by JaminZ22** [comment]
> I'd also like to see this functionality. Ideally, I would like the window to pop back open (without reloading) right away when the app was brought back into focus.

This is how v12 behaved. I was surprised to see a change in v13.
