### ISSUE TITLE
bug: GMail notification badges show incorrect number, and still show when disabled

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#1434]
# Bug Report
**Specifications:**
- WebCatalog Version: 32.3.0
- Neutron Version: 17.6.0
- OS (macOS, Windows, Linux): macOS 11.3.1

**Description:**
I have 1 unread in my inbox and the notification badge shows 99+. Furthermore, I've tried disabling the notification badge, and it still shows. The 99+ shows with badging enabled and disabled if I have at least 1 unread.
<img width="800" alt="Screen Shot 2021-05-18 at 3 19 42 PM" src="https://user-images.githubusercontent.com/157270/118730932-376db180-b7ed-11eb-8e9a-097129e780be.png">

**Comment by quanglam2807** [comment]
Long time no see, Stefan! So glad to see you :D.

I'll the bug with disabling/enabling badge count shortly.

For Gmail, WebCatalog now tries to extract the number from UI (the sidebar number). It seems there's something wrong with that code. 
<img width="263" alt="Screen Shot 2021-05-19 at 9 19 57 AM" src="https://user-images.githubusercontent.com/1548835/118747175-bdd4d280-b883-11eb-8468-fb8ecc61ea46.png">

Would you mind checking if the number on your sidebar is larger than 1? If it is, if you have time, can you run this code in the console log to see what returns?

```js
let count = 0;

if (document.getElementsByClassName('J-Ke n0').length > 0) {
  if (document.getElementsByClassName('J-Ke n0')[0].getAttribute('aria-label') != null) {
    count = parseInt(document.getElementsByClassName('J-Ke n0')[0].getAttribute('aria-label').replace(/[^0-9.]/g, ''), 10);
  }
}

if (typeof count !== 'number' || Number.isNaN(count)) {
  count = 0;
}

console.log(count);
```

**Comment by swrobel** [comment]
Ahh, so here's the problem - I use priority inbox, so my unread count is really high, but I really just want to see the priority unread count (what's in the second div below and shows in the UI):

<img width="249" alt="Screen Shot 2021-05-19 at 12 24 51 PM" src="https://user-images.githubusercontent.com/157270/118872296-44e27480-b89d-11eb-9bb4-d9817746688a.png">

```html
<div class="aio UKr6le">
  <span class="nU n1">
    <a href="https://mail.google.com/mail/u/0/#inbox" target="_top" class="J-Ke n0" aria-label="Inbox 14257 unread" tabindex="0" draggable="false">Inbox</a>
  </span>
  <div class="bsU">2</div>
</div>
```
<img width="843" alt="Screen Shot 2021-05-19 at 12 24 05 PM" src="https://user-images.githubusercontent.com/157270/118872310-490e9200-b89d-11eb-92d3-b412692e2202.png">

**Comment by Dino7405** [comment]
Hello, I am a new user of WebCatalog.  I just installed the WebCatalog Gmail app and pinned app to my Windows 10 taskbar and I cannot get the Unread Badge Count to show.  My taskbar only shows the app icon for Gmail but no badge, even when I have new, unread mail.  I do have the Unread Count Badge option turned on, as well as Gmail notifications.  Please advise on how to get this to work. Thanks!

**Comment by quanglam2807** [comment]
@swrobel Thanks a lot, Stefan. It'll be fixed in the next update of Neutron.

@Dino7405 Thanks for reporting this. It's a bug in the last update. It'll be fixed shortly.

**Comment by swrobel** [comment]
@quanglam2807 working perfectly now. Thanks as always! 🙌🏼
