### ISSUE TITLE
feature: show unread counter in task bar as well

### ISSUE THREAD

**Issue by zocker-160** [webcatalog/webcatalog-legacy#1435]
# Feature Request
**Specifications:**
- WebCatalog Version: 32.2.2
- Neutron Version: 17.6.1
- OS (macOS, Windows, Linux): Linux

**Description:**
It would be nice to be able to see the unread counter in the task bar as well, because currently, when minimized, it is impossible to see if and how many unread messages there are,

![image](https://user-images.githubusercontent.com/36563538/118839069-7c194b80-b8c6-11eb-9768-77cad2786a99.png)

It would be nice to have something like Rambox currently does, which looks like this:
![image](https://user-images.githubusercontent.com/36563538/118839188-98b58380-b8c6-11eb-8296-cc252ef609b7.png)

**Comment by johnhcc** [comment]
This may be a bug, actually.

Using 32.2.2 on MacOS 14.4.6, I also only see unread counts in the sidebar.  The badge does not show up on the Dock icon anymore (which is the equivalent to the Windows task bar in @zocker-160's example).
