### ISSUE TITLE
bug: Application windows cannot be moved in certain circumstances

### ISSUE THREAD

**Issue by johnhcc** [webcatalog/webcatalog-legacy#1436]
# Bug Report
**Specifications:**
- WebCatalog Version: 32.3.0
- Neutron Version: 17.7.0
- OS (macOS, Windows, Linux): macOS 11.3.1

**Description:**
Applications installed by WebCatalog cannot be picked up and moved around the screen in certain circumstances, when the title bar is hidden.

**Steps to Reproduce:**
1. Install and open an application with at least two services selectable in the sidebar (tested with Google).
2. Try dragging the window to a different part of the screen.  This should work as intended at this point.
3. If the title bar is visible, hide it.
4. Select a different service, either by clicking in the sidebar or using a hotkey.
5. Try dragging the window to a different part of the screen. This will now fail.

**Additional Context**
Can make a screen recording if necessary to demonstrate.

**Comment by quanglam2807** [comment]
Thanks for the feedback. This is something we won't be able to fix. Certain web apps' behaviors cannot be overwritten so we can't change them to make the web area draggable. If you want to drag the window around, please show the title bar.
