### ISSUE TITLE
feature: macOS: multi monitor & attached to menu bar: open on clicked monitor

### ISSUE THREAD

**Issue by gingerr** [webcatalog/webcatalog-legacy#1440]
# Feature Request
**Specifications:**
- WebCatalog Version: 33.0.0
- Neutron Version: 17.8.0
- macOS Version: 11.4

**Description:**
Iam using an Macbook and an external monitor. Currently webcatalog displays an app which is attached to the menu bar always on my external monitor, no matter on which monitor ive clicked on the menu bar icon.

First I thought it uses the display which is the main display (includes the menu bar in the macOS monitor settings), but ive tested it and it seems not to matter.

External monitor setup as main:
![image](https://user-images.githubusercontent.com/13162840/119727501-a5ac1700-be72-11eb-9115-696cf8f7b046.png)

Internal monitor setup as main:
![image](https://user-images.githubusercontent.com/13162840/119728126-616d4680-be73-11eb-9cf3-d42e9fbd2f35.png)

**Expected:**
The app gets displayed on the monitor ive clicked the menu bar icon at.

I know in macOS native code you can ask the OS which monitor includes the mouse pointer but i have no idea about the approaches in Electron.

`
static func withMouse() -> NSScreen? {
  return NSScreen.screens.first { NSMouseInRect(NSEvent.mouseLocation, $0.frame, false) }
}
`

**Comment by gingerr** [comment]
When i opened the Macbook lid after having it closed for a while (to enter a video meeting), the application will begin open on the internal monitor instead of the external one :(

*edit*
The menubar placement changed from the external monitor to the internal one in the system settings. After changing the menubar placement back to the external monitor, the application opened back on the external monitor. That contradicts my yesterdays testing experience, so iam not sure if the menubar placement always controls this.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
