### ISSUE TITLE
Cannot sign into webcatalog app

### ISSUE THREAD

**Issue by PietroFara** [webcatalog/webcatalog-legacy#1441]
Hi, I tried to Sign in to webcatalog with Google but when logged in in the browser nothing happens to the app locally.
The browser says: "Do you want to open xdg-open?
Answering yes means no results at all.

I don't know what I can add to better explain my problem, please let me know how I can help.

I'm running on Linux Ubuntu 20.10, the appimage of webcatalog is in my home folder

**Comment by F50Ci37Y** [comment]
I use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) for this problem.
This app adds `AppImage` software to main menu of Ubuntu OS.
