### ISSUE TITLE
bug: Google Calendar not showing notifications on macOS

### ISSUE THREAD

**Issue by boris-bc** [webcatalog/webcatalog-legacy#1447]
# Bug Report
**Specifications:**
- WebCatalog Version: 33.1.0
- Neutron Version: 
- OS (macOS, Windows, Linux): macOS

**Description:**
I have notifications for Google Calendar enabled both in WebCatalog app and the calendar settings. I can hear the sound of the notification, when I have an event but the notification does not appear on the screen. The notification does appear on the screen when I test it from the preferences menu.
Other WebCatalog apps on my system don't have similar problems with notifications.

**Steps to Reproduce:**
- install Google Calendar
- log in with an account
- configure notifications in app and google calendar settings
- wait for a notification

**Comment by quanglam2807** [comment]
This is because WebCatalog currently doesn't support Web Push API :( https://github.com/webcatalog/webcatalog-app/issues/1457
