### ISSUE TITLE
bug: Google Meet app asks for resource permissions after each update

### ISSUE THREAD

**Issue by boris-bc** [webcatalog/webcatalog-legacy#1448]
# Bug Report
**Specifications:**
- WebCatalog Version: 33.1.0
- Neutron Version:
- OS (macOS, Windows, Linux): macOS

**Description:**
After each app update, Google Meet requests permissions for microphone, camera and screen recording. The permissions for microphone and camera are easy but screen recording requires a restart to function again.

**Steps to Reproduce:**
- install Google Meet
- allow it to use microphone, camera and screen recording
- update the app next time it is available
- start a new meeting, enable the camera and try to share the screen

**Additional Context**
The experience is that after each update, the first meeting I join after that and I try to share my screen, I need to go to the OS settings, unset and set back the app permissions for screen recording, restart the app and join the meeting again.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
