### ISSUE TITLE
Add link preview when hovering

### ISSUE THREAD

**Issue by bricoleurbanism** [webcatalog/webcatalog-legacy#145]
I would really like the webapps to show the destinations of links when you hover over them (as chrome does, and most other browsers). For email this seems really important in helping to determine "should I click this link or not?"... If some people don't like this, at least it could be an option to display it in a status bar at the bottom that could be toggled on or off...

**Comment by quanglam2807** [comment]
v12 has this feature but because of some changes in the technical implementation of v13, it becomes more difficult for me to implement this feature. I'll need to find an alternative solution.

**Comment by quanglam2807** [comment]
In Chrome and other major browsers, when you hover a link, there will be an overlapped text in the left corner showing the URL. But at the moment, I can only manage to add a permanent bottom bar to show the text (which won't be hidden even if you're not hovering on anything).

**Comment by bricoleurbanism** [comment]
Personally, I would be happy to have a permanent bottom bar, but if many people don't want that (maybe for the looks?), the option to toggle one on and off would work just as well for me.

**Comment by quanglam2807** [comment]
Yes, it's mostly about the look. Nevertheless, I'll consider adding a permanent bar as you suggested.

**Comment by quanglam2807** [comment]
I found a solution for this. An update with this feature will be available soon.
