### ISSUE TITLE
bug: Create Custom App shows instead of existing app on Updates page

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#1450]
# Bug Report
**Specifications:**
- WebCatalog Version: 33.1.0
- Neutron Version: 17.13.1
- OS (macOS, Windows, Linux): macOS 11.4

**Description:**
I have 4 apps installed. When I went to check for updates, I noticed that this Create Custom App placeholder was there in place of one of my apps (Google Contacts). I had not noticed this previously, and just updated to WebCatalog 33.1.0 before checking for app updates today.
<img width="1022" alt="Screen Shot 2021-06-10 at 2 36 53 PM" src="https://user-images.githubusercontent.com/157270/121600832-f470b980-c9f9-11eb-90ff-a074a5dc3a36.png">

**Comment by quanglam2807** [comment]
Thank you, Stephan. It's fixed in the 33.1.1

**Comment by swrobel** [comment]
Thanks as always for the quick fix @quanglam2807. Couldn't live without WebCatalog!
