### ISSUE TITLE
feature: hago in https://play.google.com/store/apps/details?id=com.yy.hiyo&hl=vi&gl=US

### ISSUE THREAD

**Issue by tindshc** [webcatalog/webcatalog-legacy#1452]
# Feature Request
**Specifications:**
- WebCatalog Version:
- Neutron Version:
- OS (macOS, Windows, Linux):

**Description:**

**Additional Context**

**Comment by quanglam2807** [comment]
Because Hago is a mobile-only app, we won't be able to support it with WebCatalog. I'm sorry.
