### ISSUE TITLE
feature: add Web Push support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1457]
Related to https://github.com/electron/electron/issues/6697

**Comment by rtomac** [comment]
Hi @quanglam2807, does the merged PR above imply support for web push (particularly interested in Google Calendar use case), or just "related"?

**Comment by quanglam2807** [comment]
@rtomac Sadly, it's only related. We haven't figured out how to solve this.

**Comment by rtomac** [comment]
> @rtomac Sadly, it's only related. We haven't figured out how to solve this.

I see, thank you @quanglam2807
