### ISSUE TITLE
bug: can't interact with the webcatalog.

### ISSUE THREAD

**Issue by Theogtm** [webcatalog/webcatalog-legacy#1461]
I just downloaded the appimage and tried to run it, I saw the interface as usual but I can't click on anything, I can't write text in the search bar, can't navigate, can't install, can't configure and can't even close the app with the "X button" it looks like the app is just a static image for me. The version of the app is 34.0.0 and my system is x64.

**Comment by quanglam2807** [comment]
This happens whenever the app opens a dialog. On some Linux distros, somehow, the dialogs don't show up on top of the window so you will need to look for it (using the taskbar or dock) and then close it to use it the app.
