### ISSUE TITLE
Open links in same window

### ISSUE THREAD

**Issue by miguelrs** [webcatalog/webcatalog-legacy#1463]
# Feature Request
**Specifications:**
- WebCatalog Version: 35.0.0
- OS (macOS, Windows, Linux): macOS

**Description:**
When I open a link from another app in a WebCatalog app, I want to be able to open the link in the same active window.

**Additional Context**
I use a tool called Choosy (https://www.choosyosx.com/), which acts as the default browser, and lets you set other apps as browsers and create rules like "whenever you click a link that contains 'github.com' open it in the GitHub app".  
I've been trying WebCatalog for a couple of months, and it's been working like a charm with Choosy, opening the links in the correct apps, using just one window. However, at some point in the last couple of weeks, it started working differently and now the links open in new windows instead...  
Is this new behavior intended or an unexpected side-effect from a recent update?  
Do you have any plans to go back to the old behavior?

**Comment by quanglam2807** [comment]
Thanks for reporting this, @miguelrs. This is definitely a bug. Could you give us more details on how to reproduce this? (Which app does it happen with? If you a point us to the specific URLs/domains when this happens, that'd be great)

**Comment by miguelrs** [comment]
Hey @quanglam2807!

It happens in all apps I tried e.g. the built-in GitHub and Slab apps, and also a custom app I have for SumoLogic.  

The steps to reproduce are something like this (using GitHub as an example but the same happens for all apps):

```
Given I have installed the GitHub app in WebCatalog
And I have installed Choosy
And Choosy is my default browser
And I added GitHub app as a browser in Choosy
And I have a rule in Choosy that opens any link containing "github.com" in my GitHub app

When I have my GitHub app open
And I click on a link containing "github.com" anywhere in my Mac (e.g. in Slack)

Then the link URL opens in a new window in my GitHub app instead of in the existing window ⚠️ 
```

However, it used to open in the same window, and this new behavior was introduced within the last few weeks. 

Note that even if I don't have the GitHub app open already, when I click the link in Slack, 2 new windows of the GitHub app pop up, and if I keep clicking the link, new windows keep popping up. And what's worse, those new windows usually have a smaller size and get hidden behind the main original window, so you have to minimize the main window to see them...

I know there are other ways to open URLs in specific apps in macOS, and I imagine all those ways must be affected the same way, but I can't confirm because I only use Choosy for this at the moment...

Hope this helps!

**Comment by quanglam2807** [comment]
@miguelrs Thank you so much for the clarification, @miguelrs. This is indeed changed in the recent updates. We'll work to fix this behavior.
