### ISSUE TITLE
bug: Javascript error when Closing the app

### ISSUE THREAD

**Issue by KibaNoOu** [webcatalog/webcatalog-legacy#1469]
# Bug Report
**Specifications:**
- WebCatalog Version: v35.1.0 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Windows

**Description:**
When i close the Web Catalog App i get a Javascript Error.

**Steps to Reproduce:**
Close WebCatalog App from Tray

![immagine](https://user-images.githubusercontent.com/11923117/125635705-a7b54840-11f1-4395-81b9-e94cb6a6f371.png)

**Comment by quanglam2807** [comment]
Thank you for filling the issue. 

Do you use menu bar mode by any chance?

**Comment by KibaNoOu** [comment]
Where can I check if the option is enabled?

**Comment by quanglam2807** [comment]
I'm sorry, I mean did you enable "Attach to tray" in Preferences?

Also, did the bug occur with the WebCatalog app or with an app you install with WebCatalog? I couldn't reproduce the bug at all.

**Comment by KibaNoOu** [comment]
If you mean this, then yes, it's enabled.
In the main WebCatalog app.

![immagine](https://user-images.githubusercontent.com/11923117/125639879-10b5f976-37ac-4280-a871-13193b9ed796.png)

**Comment by quanglam2807** [comment]
Thank you so much, @KibaNoOu. We've fixed the bug in the latest version (v35.1.1). The update is not officially released so you'll need to join pre-release update channel (Preferences > Updates > Receive pre-release updates). 

I hope it will fix the bug for you. If not, please let us know.
