### ISSUE TITLE
Workspace keyboard shortcut jumps unexpectedly

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#148]
> The keyboard shortcuts for switching workspaces are glitchy. If I switch to one workspace using a keyboard shortcut it will switch to that workspace but then sometimes jump to another. That's frustrating. (Ian Jukes)

**Comment by ianjukes** [comment]
If you need any more information about this let me know. I'll post here.

**Comment by ianjukes** [comment]
I've noticed today that when I use a keyboard shortcut to switch to another workspace sometimes it will work as expected, sometimes it will switch to that workspace and then jump to another, and sometimes it will create a new workspace.
