### ISSUE TITLE
bug: ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jiffstudio** [webcatalog/webcatalog-legacy#1483]
# Bug Report
**Specifications:**
- WebCatalog Version: v36.0.0 (x64)
- OS (macOS, Windows, Linux): Windows 11

**Description:**
When I try to update an app or create a custom app, it fails.
I opened the developer tool and find the error output "ERR_SSL_PROTOCOL_ERROR"

**Steps to Reproduce:**
1. Open the developer tool 
2. Update an app / create a custom app
3. Find the output "ERR_SSL_PROTOCOL_ERROR"

**Additional Context**
![image](https://user-images.githubusercontent.com/65275566/128445986-3b330eb8-c1d8-43e0-8d35-30fa5fa48004.png)

**Comment by quanglam2807** [comment]
Thanks for reporting.

That error actually wouldn't break the app. It's just the optional telemetry endpoint. I'm not sure what causes this installation to fail. Have you tried using a different network? We just upgraded our server recently, so it's likely that Windows or the network hasn't got the updated configuration.
