### ISSUE TITLE
Failed to Connect to Server

### ISSUE THREAD

**Issue by ekamran** [webcatalog/webcatalog-legacy#1484]
<img width="422" alt="Screenshot 2021-08-06 at 23 07 40" src="https://user-images.githubusercontent.com/7408560/128550369-56e69dd0-4096-41e9-a2fa-3d64431edf7e.png">

From several days, I'm seeing this issue on my Intel Mac.
Version v36.0.0 (x64)

I thought updates would fix this, but I still cannot install any new apps,
Already installed ones works fine.

https://webcatalog.ent.us-east-2.aws.elastic-cloud.com/api/as/v1/engines/webcatalog-apps/search.json

Seems like this is failing.

**Comment by quanglam2807** [comment]
Would you mind opening the Dev Tools and go to Network tab to see what errors occur? 

To open Dev Tools, from the menu bar, select Help > Toggle Developer Tools.

**Comment by ekamran** [comment]
https://webcatalog.ent.us-east-2.aws.elastic-cloud.com/api/as/v1/engines/webcatalog-apps/search.json

This is getting stalled.

**Comment by quanglam2807** [comment]
What error do you receive?

**Comment by quanglam2807** [comment]
I'm not sure what is happening. The server is still running and I can still access the it. I'm not sure if there's something wrong with Amazon AWS

**Comment by ekamran** [comment]
Strange, I just opened the M1 mac and the same problem occured.
It was working fine until yesterday.

> What error do you receive?

How do I check error specifically?

**Comment by quanglam2807** [comment]
You can open the Dev Tools, go to Network tab, and check which error the endpoint https://webcatalog.ent.us-east-2.aws.elastic-cloud.com/api/as/v1/engines/webcatalog-apps/search.json returns.

**Comment by ekamran** [comment]
ERROR NAME NOT RESOLVED

**Comment by ekamran** [comment]
Response tab says: Failed to load Response Data

**Comment by quanglam2807** [comment]
Thank you so much, @ekamran. Could you take a screenshot for us, please? We'll need to contact the cloud supplier about this.

**Comment by quanglam2807** [comment]
Also, if you go to this URL: https://webcatalog.ent.us-east-2.aws.elastic-cloud.com/api/as/v1/engines/webcatalog-apps/search.json, what will happen?

**Comment by ekamran** [comment]
> Also, if you go to this URL: https://webcatalog.ent.us-east-2.aws.elastic-cloud.com/api/as/v1/engines/webcatalog-apps/search.json, what will happen?

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ekamran** [comment]
Damn it, it is now working on a VPN.
So what might be the issue at my end?

**Comment by quanglam2807** [comment]
It looks like there's something wrong with AWS DNS or your Internet provider's DNS.

**Comment by quanglam2807** [comment]
Please give it 24 hours. Also to avoid bugs like this to occur, I highly recommend you to use https://1.1.1.1/.

**Comment by ekamran** [comment]
On One Mac, it was not working since a week,
One the other one, I was using it without any issues until today.

But today, I reset my router.

I will check with my internet provider.

Thank you for all your responses.

**Comment by sicahjes** [comment]
I currently have this issue. I am using the paid version:

- I followed the above link, it asks for a username and password. I don't think I have one, I can't get past the page.
- I tried using it with my VPN provider, it did not help
- I tried with both a wifi and ethernet connection, it made no difference. 
- I downloaded and installed Cloudflare Warp, as advised. Initially it did not make a difference, but it started working after restarting the app a couple of times.

Why is this software dependent on Cloudflare?

**Comment by quanglam2807** [comment]
@sicahjes 

> I followed the above link, it asks for a username and password. I don't think I have one, I can't get past the page.
That's the correct behavior. The URL is supposed be connected by the app, not by users.

> I downloaded and installed Cloudflare Warp, as advised. Initially it did not make a difference, but it started working after restarting the app a couple of times. Why is this software dependent on Cloudflare?
Actually, the software is not dependent on Cloudflare. WARP/1.1.1.1 is an alternative DNS/VPN provider which works well, especially when the DNS/Internet connection your ISP provides is not good.

It's likely there was something wrong with the server at that time. We'll continue monitoring to see if we can find anything suspicious.

**Comment by ekamran** [comment]
Honestly without WARP, it still doesn't works for me.

Not sure what exactly the issue is here?
Coz all other services that I use that depends on AWS Endpoints seems working fine for me.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
