### ISSUE TITLE
Add WidevineDRM support for Windows

### ISSUE THREAD

**Issue by ylluminate** [webcatalog/webcatalog-legacy#1485]
Where do you enable Wildvine for video apps in the most recent release?

**Comment by quanglam2807** [comment]
It's not supported on all versions of the app due to technical limitation. If it is supported, you don't need to do anything.

https://docs.webcatalog.io/article/50-does-webcatalog-singlebox-and-clovery-support-all-w3c-web-standards

**Comment by ylluminate** [comment]
Oh gee, so Netflix, Amazon Prime, and other video services won't work on Windows 10 (x64) then, right?

**Comment by quanglam2807** [comment]
No, I'm sorry. But you can use these services with the standalone Singlebox app: https://webcatalog.io/singlebox/

**Comment by ylluminate** [comment]
That's really unfortunate - what can we do to work around this? There must be a solution. I'm not interested in using additional tools for these purposes. Your push towards WebCatalog and the lack of Chromeless support on Windows got me thinking about unification, but now with this this is a non-starter in some scenarios.

**Comment by quanglam2807** [comment]
I'm sorry but currently, it's not possible. We'll try to find a way to add WidevineDRM support to WebCatalog for Windows. 

You can also continue using the Chromeless 1.x on Windows. We stopped supporting Windows with Chromeless 2.x because we also faced technical challenges with the platform.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
