### ISSUE TITLE
question: can Neutron be used to develop a tabbed browser app like Chrome or Vivaldi

### ISSUE THREAD

**Issue by johnoscott** [webcatalog/webcatalog-legacy#1486]
Can you please give your opinion on using Neutron as the core for a tabbed browser app like Chrome ? I want to experiment with a better tab-group user experience (vertical tab groups) and want to know if I could do it starting with Neutron. I have been using web catalog which allows "accounts" as vertical tabs which made me think it might be possible.

If so, can you give me some tips on using neutron for a tabbed experience ?

**Comment by johnoscott** [comment]
can i get an answer ?

**Comment by quanglam2807** [comment]
Sorry for the delay.

Currently, we're working on proper tab support. And Neutron is not designed to work as a browser replacement. Nevertheless, you can enable Preferences > Privacy > Share browsing data & login credentials between services & accounts which makes it work almost like a browser.

**Comment by johnoscott** [comment]
cheers. thankyou
