### ISSUE TITLE
feature: Close automatically running Apps during Updates and Checks

### ISSUE THREAD

**Issue by KibaNoOu** [webcatalog/webcatalog-legacy#1490]
# Feature Request
**Specifications:**
- WebCatalog Version: 36.1.0
- Neutron Version:
- OS (macOS, Windows, Linux): Windows

Right now when you try to update a running app you get an error message saying that the app is currently running.
Would be possible to automatically close the app when updating all is launched and maybe an automatica update check for all the installed app?

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
