### ISSUE TITLE
bug: dwservice.net site does not open

### ISSUE THREAD

**Issue by edmundlaugasson** [webcatalog/webcatalog-legacy#1495]
# Bug Report
**Specifications:**
- WebCatalog Version: 36.2.0 (x64)
- Neutron Version: about doesn't show it
- OS: Linux

**Description:**

https://www.dwservice.net/ doesn't open, keeps endless loading. Closing, opening, etc doesn't help. Website works in another browser.

**Steps to Reproduce:**

Create a custom app with https://www.dwservice.net/ address and try to open it.

**Additional Context**

Here is the screenshot of endless loading page:
![DWService - DWService_001](https://user-images.githubusercontent.com/6355082/129456858-07ffe5cb-ae11-4b1f-93c5-fc1f8f2a9765.jpg)

**Comment by Chaitanya-008** [comment]
![Screenshot_20210816-064425.jpg](https://user-images.githubusercontent.com/85453619/129499180-c70b7865-9492-4083-a9cf-3776acd414d2.jpg)

**Comment by edmundlaugasson** [comment]
This screenshot seems to be done in web browser at smartphone. If you noticed, then I mentioned that in browser the site works, but not in WebCatalog. If you noticed, then issue is related with WebCatalog and not regular web browser.

**Comment by edmundlaugasson** [comment]
Sry, in phone are buttons close and accidentally tapped on close button....

**Comment by quanglam2807** [comment]
Thanks for reporting. It works on Mac for me, somehow. I'll try to see if I can reproduce this on Linux.

**Comment by edmundlaugasson** [comment]
I've been updated WebCatalog, currently v36.3.0. I also deleted my own created app and found existing app from WebCatalog - installed it and now it opens. Tested CLI and GUI for remote management (all features DWS is offering for Linux), also worked. So I close the current issue as it works now.
