### ISSUE TITLE
bug: GMail label icons display as colored squares

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#1496]
# Bug Report
**Specifications:**
- WebCatalog Version: 36.2.0
- Neutron Version: 18.4.1
- OS (macOS, Windows, Linux): macOS 11.5.2

**Description:**
WebCatalog:
<img width="69" alt="Screen Shot 2021-08-18 at 7 56 42 AM" src="https://user-images.githubusercontent.com/157270/129921473-083f2197-7175-418e-97b0-be8cf2b862e4.png">

Chrome:
<img width="72" alt="Screen Shot 2021-08-18 at 7 56 55 AM" src="https://user-images.githubusercontent.com/157270/129921480-c1b3b6fe-1e63-418f-a6da-8809a46dcc64.png">

**Steps to Reproduce:**
Load GMail in latest WebCatalog

**Additional Context**
I believe this issue is caused by https://github.com/webcatalog/neutron/pull/550 as inspecting in WebCatalog doesn't show the `-webkit-mask` rules, so my assumption is that Google withholds these when it thinks the browser is Firefox, which [supports](https://www.caniuse.com/css-masks) the `mask` rule.

WebCatalog:
<img width="552" alt="Screen Shot 2021-08-18 at 8 00 21 AM" src="https://user-images.githubusercontent.com/157270/129922077-fffdb89c-e7f3-4eab-9dd0-184057a69c9a.png">

Chrome:
<img width="324" alt="Screen Shot 2021-08-18 at 8 00 14 AM" src="https://user-images.githubusercontent.com/157270/129922100-a94ad68f-f49c-4ddf-8b9e-e8e93eddc637.png">

**Comment by quanglam2807** [comment]
Thanks for reporting the bug. It has been fixed in the latest update.

**Comment by quanglam2807** [comment]
Fixed with https://github.com/webcatalog/neutron/pull/557. Previously, Gmail forces users to use basic HTML version if UA is set to Chrome, so in order to fix it, the UA was changed to Firefox => caused the bug.

**Comment by swrobel** [comment]
Thank you for the quick fix, as always! If anyone else has this happen, I had to go to View > Reload Page to get it to display correctly, even after relaunching the app.
