### ISSUE TITLE
bug: Update not working

### ISSUE THREAD

**Issue by nilswald** [webcatalog/webcatalog-legacy#1503]
# Bug Report
**Specifications:**
- WebCatalog Version: v36.0.0 (x64)
- Neutron Version: 
- OS (macOS, Windows, Linux): macOS 10.15.7

**Description:**
No updates. 

**Steps to Reproduce:**
When I select "Check for Updates" from the menu, I get a message "There is an available update. It is being downloaded. We will let you know when it is ready." but nothing happens, zero network traffic. 

**Additional Context**
Console Log attached. Location is Germany.

[-1630346847494.log](https://github.com/webcatalog/webcatalog-app/files/7078598/-1630346847494.log)

**Comment by quanglam2807** [comment]
Thank you for reporting this, Nils. There was a bug in the `eletron-updater` (auto updater) library which broke this. It has been fixed in the latest version but you'll have to manually download the update from webcatalog.io/webcatalog/
