### ISSUE TITLE
feature: add support for extensions

### ISSUE THREAD

**Issue by sailor0703** [webcatalog/webcatalog-legacy#1504]
# Feature Request
**Specifications:**
- WebCatalog Version:
- Neutron Version: v36.0.0
- OS (macOS, Windows, Linux): Mac OS 10.15.7

**Description:**
I previously was able to use google chrome extensions in the WebCatalog apps. Now, this feature is removed. Without support for extensions, many of the websites I would use this for cannot be used at all. If possible, please add this as an option, perhaps using the Google Chrome Web Store as an a place to add extensions from, or the previous method of adding from extensions installed to Google Chrome works as well. Specifically, Tronscan requires use of the Tronlink extension, and others sites I've considered using have similar requirements.

**Comment by quanglam2807** [comment]
Thanks for the feedback. Extension support is under testing in the pre-release channel (WebCatalog app > Preferences > Updates > Receive pre-release updates).

**Comment by sailor0703** [comment]
Ahh, it's in the pre-release version, thanks. Perhaps I had installed a pre-release version at some point, and that's where I was previously able to install and use extensions? Then at some point it downgraded to a release version? Regardless, it's straight now, so thanks!

**Comment by quanglam2807** [comment]
We used to open the feature to stable channel but then decided to change it.
