### ISSUE TITLE
bug: Another CORS issue with Dark Reader & GMail

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#1505]
# Bug Report
**Specifications:**
- WebCatalog Version: 36.3.2
- Neutron Version: 20.0.0-alpha.5
- OS (macOS, Windows, Linux): macOS 11.5.2

**Description:**
WebCatalog is sluggish to load the page, and many icons are not darkened as they once were:
<img width="775" alt="Screen Shot 2021-09-08 at 10 11 55 PM" src="https://user-images.githubusercontent.com/157270/132626550-a460e296-6081-4197-b3f6-6f72b84211e2.png">

**Steps to Reproduce:**
Load GMail with Dark Reader enabled in dark mode

**Additional Context**
Tons of console errors like this:
<img width="551" alt="Screen Shot 2021-09-08 at 10 10 48 PM" src="https://user-images.githubusercontent.com/157270/132626445-f2073dc8-e895-46c4-9ca4-9a79a437ac9b.png">

**Comment by quanglam2807** [comment]
It seems like packaging Dark Reader into the app directly is not ideal and causes problems from time to time. Extension support is now in alpha mode so hopefully, we'd be able to get the Dark Reader extension to work with WebCatalog soon - that'd solve most of these problems.

**Comment by swrobel** [comment]
Any luck getting the Dark Reader extension to work?

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
