### ISSUE TITLE
bug: WebCatalog app doesn't update

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#1508]
# Bug Report
**Specifications:**
- WebCatalog Version: 36.4.0
- Neutron Version: N/A
- OS (macOS, Windows, Linux): macOS 11.5.2

**Description:**
WebCatalog used to update just fine. Now it notifies me that I need to update, but the only way I've been able to do it is via `brew reinstall --cask webcatalog`. I also can't update apps without updating WebCatalog itself, which is new behavior, and quite frustrating.

**Steps to Reproduce:**
Open the app menu and choose Check for Updates. I'm notified that a new update is available and that I'll be notified when I'm ready but I'm never notified. Quitting & restarting the app does not update. It never seems to download the update.
<img width="808" alt="Screen Shot 2021-09-10 at 6 41 39 AM" src="https://user-images.githubusercontent.com/157270/132862861-8650f760-adfd-4761-9ca8-fa28a2a640b7.png">

**Additional Context**
In the menu, it used to show the download progress instead of "Check for Updates."
<img width="215" alt="Screen Shot 2021-09-10 at 6 41 14 AM" src="https://user-images.githubusercontent.com/157270/132862886-a0268ccc-c240-4576-8de7-fcec94365691.png">

**Comment by quanglam2807** [comment]
I'm so sorry, Stefan. The updater library WebCatalog is using had some critical bugs preventing it from working properly on macOS (affecting v36.0.0 to v36.4.0). It has been fixed v36.4.1 but everyone would have to download the latest version manually.

**Comment by quanglam2807** [comment]
I've found a workaround. The updater should work properly now. You don't need to do anything special as it's a server-side fix.
