### ISSUE TITLE
feature: Remove border from non native bar

### ISSUE THREAD

**Issue by restructor1** [webcatalog/webcatalog-legacy#1510]
# Feature Request
**Specifications:**
- WebCatalog Version: Last
- Neutron Version:
- OS (macOS, Windows, Linux): Windows 10

When non native bar selected, then it is inconvenient to close button with X button. Look at screeshot, the coursor in top right corner but X button is not active. The window border = 0 removes this problem.
![3](https://user-images.githubusercontent.com/63119504/132885879-63b3ccf0-0774-4eaf-aac9-99eb4b22ec54.jpg)

**Comment by quanglam2807** [comment]
Currently, those buttons are not native. In the next major update, we'll move to native solution so it would work much better.

**Comment by quanglam2807** [comment]
Resolved with [5e16fd5de475e5e29b656cfcd5112172b14522ca](https://github.com/webcatalog/neutron/pull/601)
