### ISSUE TITLE
bug: Unrecognized feature: 'display-capture'.  when trying to share screen via Google Meet

### ISSUE THREAD

**Issue by xWayfinder** [webcatalog/webcatalog-legacy#1512]
# Bug Report
**Specifications:**
- App: Google Meet Version 19.0.4 (WebCatalog, x64)
- WebCatalog Version:  v37.0.0 (x64)
- Neutron: 19.0.4
- Electron: 14.0.0
- Node: 14.17.0
- Chromium: 93.0.4577.58
- OS: macOS 11.5.2

**Description:**
When I go to share my screen in google meet it fails with an error message "Can't share your screen" when I open the developer console I can see the warning `Unrecognized feature: 'display-capture'.` 

**Steps to Reproduce:**
- Install WebCatalog 37.0.0
- Install Google Meet
- Open Google Meet and create a new meeting
- Click share screen

** Additional information **
In maOS `Preferences >  Security & Privacy > Privacy` I have removed and re-added permissions to screen recording and restarted several times.

**Comment by quanglam2807** [comment]
Thanks for reporting, @ImaginateWayne. Are you using the custom User-Agent feature? To make screen sharing works with Google Meet, WebCatalog/Neutron automatically changes your User-Agent string to Safari. But if you're using custom User-Agent, that rule would be ignored.

**Comment by xWayfinder** [comment]
Hey @quanglam2807 I hadn't set any custom User-Agent. 

FYI I enable Pre-releases last night and the issue resolved itself.
