### ISSUE TITLE
Add clarification that the app is not free

### ISSUE THREAD

**Issue by SainteCelery** [webcatalog/webcatalog-legacy#165]
Given the lack of so much missing basic browser functionality, it seems a bit premature to be charging for this Beta. However, if you're going to do so, not stating up front that there is a fee for using the full functionality of what does exist is rather bait-and-switchy. I'm curious about how you plan to handle the inevitable unpaid forks...?

**Comment by quanglam2807** [comment]
I'll add a clarification to README.md that this is a paid app. Still, I don't understand what you mean by "handle the inevitable unpaid forks". The app is free if users only install up to 2 apps (with all features unlocked). And for me, personally, many users would find it's acceptable enough as a single web wrapper app sometimes costs up to 10 USD on the Mac App Store.

**Comment by boticello** [comment]
I am a paying user of WebCatalog 12. That app has told me that it is unsupported, and I should upgrade. Do I need to pay again for WebCatalog 13? The purchase page tells me "WebCatalog has permanent licenses, which have no time limit. In other words, the license never expires". Does that apply to WebCatalog 13 but not WebCatalog 12? What happens with WebCatalog 14? I am confused. I only purchased it a few months ago.

**Comment by quanglam2807** [comment]
@boticello You can use the same license for WebCatalog 13. If WebCatalog 14 is a huge update, I might ask users to pay to upgrade. But at the moment, feel free to upgrade to WebCatalog 13 and activate using the old license. I'll try to clarify this on the website and in the app.
