### ISSUE TITLE
App view sometimes fails to quit gracefully

### ISSUE THREAD

**Issue by ianjukes** [webcatalog/webcatalog-legacy#176]
When quitting any of the Webcatalog apps, they will sometimes fail to quit gracefully and display the following error message.

<img width="455" alt="screenshot" src="https://user-images.githubusercontent.com/6738441/53008226-d51c7f80-3430-11e9-8eb7-991730a03c46.png">

**Comment by quanglam2807** [comment]
Thanks for reporting, @ianjukes! If this happens again, would you mind clicking "Report..." and posting the log here? It would help me a lot!

**Comment by ianjukes** [comment]
Will do. I haven't seen the error for a while now, which makes me think it's been fixed in a previous release. It was happening frequently. I will definitely post the error report if it happens again though.

**Comment by quanglam2807** [comment]
Thanks for the response, @ianjukes. I'll close this issue. If it happens again, please let me know and I'll reopen this thread.

**Comment by ianjukes** [comment]
Fine with me.
