### ISSUE TITLE
Netflix app view does not remain signed in

### ISSUE THREAD

**Issue by ianjukes** [webcatalog/webcatalog-legacy#177]
For some reason the Netflix Webcatalog app will not remain signed in, even if the "Remember me" checkbox is checked at sign in.

**Comment by quanglam2807** [comment]
Hopefully, this will be fixed with #185. If not, I can't do anything further as this is a problem of Electron or Netflix.

**Comment by ianjukes** [comment]
I can confirm this wasn't fixed with #185. There are other Electron apps out there on GitHub that have been written as containers for Netflix, e.g. https://github.com/oscartbeaumont/Netflix-Desktop Even if it is a Netflix/Electron issue, is there a workaround? Would love to see this fixed.

**Comment by quanglam2807** [comment]
@ianjukes It's pretty odd. Because I also use Netflix and it doesn't log me out. So I really don't know what went wrong. Would you mind checking the console.log to see if there's anything suspicious?

**Comment by ianjukes** [comment]
@quanglam2807 Sure. How do I access the console.log?

**Comment by ianjukes** [comment]
@quanglam2807 That is odd. I literally get logged out every single time using WebCatalog, but never when I'm using Safari or Chrome. I wonder if it's a UK/US thing?

So I get these errors **Developer Tools > Console** when I log into Netflix. The 'DevTools failed to parse SourceMap: ... Observable.js.map' warning repeats 136 times and then stops.

<img width="564" alt="console" src="https://user-images.githubusercontent.com/6738441/53863752-de861a00-3fe2-11e9-9903-847eb094531b.png">

There is nothing suspicious in the system console.

**Comment by ianjukes** [comment]
@quanglam2807 Hmmm... it gets more mysterious! I also get this error reported by Netflix in the app when trying to play any content:

<img width="587" alt="netflix" src="https://user-images.githubusercontent.com/6738441/53864702-12623f00-3fe5-11e9-8701-2b58134b341b.png">

Can you play Netflix content? It seems there is a deeper issue.

I have opened this as a new issue — see #205
