### ISSUE TITLE
App views failed to update

### ISSUE THREAD

**Issue by bradowatson** [webcatalog/webcatalog-legacy#183]
I can't seem to update any apps in the latest update. They just hang and hang and eventually I got an error as you see below.

![image](https://user-images.githubusercontent.com/6272147/53364516-f5ef4400-390c-11e9-9b84-4213ec944a2f.png)

**Comment by quanglam2807** [comment]
Thank you very much for letting me know. This is a serious bug. I'll try to fix it ASAP.

**Comment by quanglam2807** [comment]
Please update to the new version to see if it is fixed. 

I've added some tools to help tracking bugs like this. If this bug still persists in the new version, it will be reported automatically and I'll fix it.
