### ISSUE TITLE
WebCatalog -> Check for Updates always returning no internet connection

### ISSUE THREAD

**Issue by dave-redfern** [webcatalog/webcatalog-legacy#195]
With 13.3.0 and 13.4.0 the app update check launched from the Apple menu bar "WebCatalog" seems to be always returning "Failed to check for updates. Please check your Internet connection.". My connection is fine, no VPN is in use. The app is not blocked by firewall. The "Check for Updates" on the installed apps tab does work fine.

**Comment by quanglam2807** [comment]
Thank you very much for noticing, I didn't cut the release well. I'm fixing it.
