### ISSUE TITLE
Updating multiple installed apps at the same time fails

### ISSUE THREAD

**Issue by dave-redfern** [webcatalog/webcatalog-legacy#196]
If the apps need updating and you hit "update" on all of them one after the other without waiting; the update will randomly fail and remove the app from the "Installed" tab. The app is still present on the system and can be listed again on "Installed" but you have to navigate to Home and then back again. Updating each app individually and waiting for it to finish, always works; just the case of multiple update requests.

The update requests should probably be queued after the first is triggered to avoid this and not result in all CPU resources being used during the update process.

**Comment by quanglam2807** [comment]
This is probably related to #183.
