### ISSUE TITLE
WhatsApp Needing Update Again

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#199]
WhatsApp was working, but now shows same "Update Google Chrome" window as before.

MacOS Mojave

**Comment by Woafmann** [comment]
I cleared the browser data and reset preferences to their original settings. Seems to have done the trick. I don't see any issue now.

**Comment by quanglam2807** [comment]
Thank you for letting me know! If it happens, please let me know.

**Comment by Woafmann** [comment]
Thanks! I really appreciate the way you're staying on top of this app. Glad to see a developer who takes their project to heart. I'm glad to be a supporting licensee!

**Comment by quanglam2807** [comment]
Thanks a lot!! I’m really appreciated.
