### ISSUE TITLE
"Failed to install" when downloading in parallel

### ISSUE THREAD

**Issue by wiiiimm** [webcatalog/webcatalog-legacy#200]
If I do any combination of install / update in parallel, they will fail.

A "Failed to install {app name}" message will show up.

**Comment by JaminZ22** [comment]
I'm getting this error with independent installs/updates as well. I'm currently not able to install any new apps or update any existing ones.

**Comment by quanglam2807** [comment]
Thank you for letting me know. This has been fixed with #197. Please wait for the next update.
