### ISSUE TITLE
Dragging windows from the top instead of dragging from sidebar

### ISSUE THREAD

**Issue by hotr11vn** [webcatalog/webcatalog-legacy#204]
I saw the navigation way of Getcatalog very similar to Slack, with Slack user can drag the windows easier from the top as usual instead of holding the left side of the windows.

**Comment by quanglam2807** [comment]
Thanks for the suggestion. But this feature requires custom code for each app so I don't have enough resources to add it to WebCatalog. You can the JS Injection feature and CSS property webkit-app-region to do it on your own. https://developer.chrome.com/apps/app_window. Feel free to let me know if you need help.

**Comment by Naatan** [comment]
@quanglam2807 is there more to it than just setting the CSS property? I've tried it on two apps (Asana and Github) and I cannot get it to work :\

**Comment by quanglam2807** [comment]
Thanks for bringing this back. This bug is related to https://github.com/electron/electron/issues/21621#issuecomment-605394949. I'll fix it soon.

**Comment by Naatan** [comment]
Thanks @quanglam2807 , glad to hear you're on top of it :) Is there any way to work around this issue for now? I read your comment and am looking into the BrowserWindow API but this is all new to me. Happy to wait of course, just wondering if there's a low effort work around you can share.

**Comment by quanglam2807** [comment]
@Naatan Thanks for asking. You'd have to wait for the next update as `BrowserWindows` is only accessible to the app. 

I've merged the change to Singlebox (https://github.com/atomery/singlebox/pull/256) and will merge it to WebCatalog soon. There're also some pending major changes for WebCatalog so you'll have to wait a bit longer for the update (ETA: next week)

**Comment by quanglam2807** [comment]
Resolved with https://github.com/atomery/juli/pull/3
