### ISSUE TITLE
WidevineCdm doesn't load properly

### ISSUE THREAD

**Issue by ianjukes** [webcatalog/webcatalog-legacy#205]
When attempting to play any Netflix content I get the following error reported:

<img width="595" alt="screenshot" src="https://user-images.githubusercontent.com/6738441/54092177-ee09b800-4380-11e9-9853-dd7f2b7803fe.png">

**Comment by quanglam2807** [comment]
It seems like there's a bug in Electron@4+ https://github.com/electron/electron/issues/16285

**Comment by ianjukes** [comment]
@quanglam2807 I can also confirm that this has fixed #177 as well. Excellent!

**Comment by quanglam2807** [comment]
@ianjukes thanks for letting me know!!
