### ISSUE TITLE
Add option to share browsing data between workspaces

### ISSUE THREAD

**Issue by project-guru** [webcatalog/webcatalog-legacy#206]
I agree that workspaces may offer a productivity boost. But they are not ideal for situations where for example I want to right click on a link [quickly] open it on a new tab (just like a browser). 

Right now, in order to achieve something similar, I have to:
1.  Create a workspace 
2. Log in again
3. Navigate to the page I need

That is way too much work compared to simply being able to right-click and open in new tab.

Any plans of adding tabs **or** allowing the ability to right-click and open in new workspace?

Other than this Web Catalog is pretty cool!

Thanks!

**Comment by quanglam2807** [comment]
Thank you for the suggestions! I think I can add an option to share cookies between workspaces and an option on the right-click menu to open in a new workspace :)

**Comment by project-guru** [comment]
That would be great. For some reason my original email wasn’t included in
your reply. Can you:

a. Give me an estimated time when the requested features can be
implemented? (No rush. I’d just like to have an idea)

b. When you reply to me if possible please include my original message.

Thanks!

(Edited by quanglam2807 to remove private contact info)

**Comment by project-guru** [comment]
I see you enabled some of the menu items that were disabled before. That’s
great.

Now we only need to be able to allow tabs.

Hope this happens soon.

Thanks! Xavier


From: xavier paredes <sir.paredes@gmail.com> <sir.paredes@gmail.com>
Reply: xavier paredes <sir.paredes@gmail.com> <sir.paredes@gmail.com>
Date: March 13, 2019 at 10:53:28 PM
To: quanglam2807/webcatalog
<reply@reply.github.com>
<reply@reply.github.com>
Subject:  Re: [quanglam2807/webcatalog] Workspaces not productive. Please
implement Tabs (#206)

That would be great. For some reason my original email wasn’t included in
your reply. Can you:

a. Give me an estimated time when the requested features can be
implemented? (No rush. I’d just like to have an idea)

b. When you reply to me if possible please include my original message.

Thanks!

Xavier Paredes
Project Manager
Visual Interactive Studios
Cell: 917-463-8350
www.visual2go.com
https://www.linkedin.com/in/xavier-paredes/


On March 13, 2019 at 10:11:17 PM, Quang Lam (notifications@github.com)
wrote:

Thank you for the suggestions! I think I can add an option to share cookies
between workspaces and an option on the right-click menu to open in a new
workspace :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quanglam2807/webcatalog/issues/206#issuecomment-472687933>,
or mute the thread

**Comment by quanglam2807** [comment]
@project-guru Awesome! It would take roughly 1-2 weeks to add these features. :)
