### ISSUE TITLE
How can i add the Sidebar/Workspaces?

### ISSUE THREAD

**Issue by zensudo** [webcatalog/webcatalog-legacy#207]
I bought the App but there is no Sidebar function....

**Comment by quanglam2807** [comment]
Thank you for asking! After you install and open an app. On the menubar, go to App Name > Preferences (Command + Comma). There you can find an option to turn it on.

**Comment by zensudo** [comment]
![Bildschirmfoto 2019-03-14 um 09 50 37](https://user-images.githubusercontent.com/32953933/54343222-a3b55f00-463e-11e9-9270-85dfc3f9f036.png)

Im sorry to tell you, but there is no Option....

**Comment by quanglam2807** [comment]
Hi @JSG01. That's the preferences for the WebCatalog app. Each installed app would have its own preferences page. For example, after installing Gmail, open it and then go to Gmail > Preferences from the menubar.

**Comment by valiant66** [comment]
This does not appear to be the case if using the Chrome engine. When going to Appname > Preferences it takes you to the chrome://settings/appearance page. There is no option to turn on the Sidebar option, and no way to get to a different set of prefs.

In light of that situation, how do I create a second app of the same kind? In this case I have two Dropbox accounts, but I can't figure out how to add the second account.

This will also apply to e.g. multiple gmail accounts etc.

**Comment by quanglam2807** [comment]
@valiant66 I'm sorry but sidebar is only available with Electron engine.  Chrome engine lacks many features so I recommend using Electron.

To create multiple Dropbox apps, at the moment, you can use the "Create Custom App" feature. I'll try to make it easier to the upcoming updates.
