### ISSUE TITLE
Add option to pick notification sound

### ISSUE THREAD

**Issue by bricoleurbanism** [webcatalog/webcatalog-legacy#215]
Is there a way that we could select the notification sound on an app-by-app basis (or at the least for all Webcatalog apps). I can't find anywhere that this can be changed - I can't even figure out where webcatalog is getting its sound from (the notification sound does not seem to be in the list of standard system sounds). Is there some way a preference could be added for this or could you provide instructions to change the sound if is possible already?

thanks!

**Comment by quanglam2807** [comment]
Thank you for asking, @bricoleurbanism. Actually, the sounds of the notifications are determined by the developers of the apps you use. So I cannot do anything to change it. You can contact the developers of these apps to ask them directly.

**Comment by bricoleurbanism** [comment]
actually, I'm only trying to use it for Gmail. When using in Gmail in
Chrome browser, there are no sound notifications - sound is not supported,
so there's no way to select the sound. But when using gmail in a webcatalog
app all of a sudden there is a sound notification, but nowhere to change or
select the sound! Where is it coming from? It sounds like the sound you
would get when you finished burning a CD or DVD.

**Comment by quanglam2807** [comment]
I think you can go to macOS Preferences > Sound > Sound Effects > Select an alert sound to change it. Please let me know if it works.

**Comment by bricoleurbanism** [comment]
No, that Sound effect preference is for alerts, not notifications. I have
it set to a different sound, but the gmail app is using a totally different
one from what I chose.

**Comment by quanglam2807** [comment]
I'm sorry but the technical details of WebCatalog make it difficult to implement this feature so I will move forward with it. I'm sorry.
