### ISSUE TITLE
WebCatalog with Firefox engine -- Userstyles, Extensions, Profile?

### ISSUE THREAD

**Issue by Bmuse21** [webcatalog/webcatalog-legacy#216]
Hello! New to WebCatalog, it looks great. 

I want to add Trello. I use Firefox, and have FF extensions and a Stylish userstyle modifying Trello. I'd like Trello in WebCatalog to be the same as I see in Firefox. So, two questions:

1. When I try to select Firefox as the engine, it shows the default FF profile, then gives an error that it's already in use. (Firefox is indeed running; I need it open.) Do I need to create a new FF profile? Duplicate my current one?

2. Can WebCatalog display a site with Firefox extensions and Stylish userstyles? Is that tied to my FF profile?

Sorry for the basic questions, but I appreciate any help!

Thanks very much!
Bmuse

**Comment by quanglam2807** [comment]
I'm sorry, @Bmuse21 but WebCatalog 13 no longer supports Firefox engine. Are you using WebCatalog 12 on Linux or Windows?
