### ISSUE TITLE
Messenger doesn't load

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#218]
I'm not sure if it only happens on my Mac but Messenger (messenger.com) doesn't load with WebCatalog. Can you guys test this? @dave-redfern @ianjukes.

**Comment by dave-redfern** [comment]
@quanglam2807 I was able to create an app and open it but I don't use Messenger and can't say if it works after logging in.

**Comment by quanglam2807** [comment]
@dave-redfern Thanks a lot for testing! But it does load when you open it, right? It doesn't load at all on my Mac.

**Comment by dave-redfern** [comment]
Yes, it loads. I've tried using the Messenger pre-built app and as a custom app too and both worked. I took a screen shot of it running, but not sure how to upload it to github.

Are you running a VPN or site blocker? Or maybe you have bad settings left over in your ~/Library folder? You could try adding a new User on your Mac and creating a new app under that User. That would rule out something in your main profile.

**Comment by quanglam2807** [comment]
Thanks a lot, @dave-redfern. Probably, there’s something wrong with my machine.

**Comment by ianjukes** [comment]
@quanglam2807 I know I'm late to the party, but Messenger works fine for me too. 😊
