### ISSUE TITLE
WebCatalog 12 doesn't load catalog properly

### ISSUE THREAD

**Issue by emailalinda** [webcatalog/webcatalog-legacy#222]
i had an earlier version of web catalog (12. something) which didnt allow me to install new apps anymore - got an error saying i wasn't connected to the server, although i was. 
I tried updating to a later version, hoping that will resolve the problem. however, i got errors with that as well. 
so i went to your website and downloaded the latest version, 13.5.2 for mac. 
I put that one into the applications folder and removed th previous version.
however, now it looks like there are no apps installed in the new version, even though I do have some, which are actually running! 
and i cannot install any new ones, still - it just keeps saying "installing" but never gets installed. 

what to do? I don't want to delete all and start from scratch - i had installed tons of apps already!

**Comment by quanglam2807** [comment]
Hi @emailalinda. I'm sorry but the server for WebCatalog 12 has been shut down. You can still install custom apps with the old version. Your installed apps in WebCatalog 12 will continue to work normally but they won't show up in the new version. You can find them at Home directory > Applications > WebCatalog Lite Apps (and you can remove them if you want to)

WebCatalog 13 takes quite long to install an app so please give it some time!

**Comment by emailalinda** [comment]
Thanks Quam but it is not installing at all on the Webcatalog 13. I mean how long is it supposed to take -  hours??? It hasnt installed since yesterday. Something is not right. I have a paid license, I'd like to have my WebCatalog working. Not very happy with you just dropping the 12 without informing either. I'll move over to the 13 but need to get it working first obviously...


![image](https://user-images.githubusercontent.com/34095565/54914572-2b2b8980-4eed-11e9-8a33-17ac2274b7bc.png)

**Comment by quanglam2807** [comment]
@emailalinda This is probably a bug with the new version. I'll try to fix it ASAP.

I'm sorry for not handling the transition smoothly so if you'd like to have a refund, feel free to let me know.

**Comment by emailalinda** [comment]
hi quam. i managed to install the apps now. thanks! 
well, i do love webcatalog!

**Comment by quanglam2807** [comment]
@emailalinda Thank you very much for letting me know! I'm glad it works for you now! Feel free to contact if you need any help.
