### ISSUE TITLE
WhatsApp app asks users to update Google Chrome

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#240]
**Issue:**
Every time WhatsApp is closed, upon relaunch, it is inoperable with the "Update Google Chrome" error page. 

**Steps to replicate problem:**

- Launch WhatsApp and set up via mobile phone QR code as normal. Program operates normally.
- Terminate program and relaunch.
- Displays "Update Google Chrome" error. Cannot use program.

**Temporary workaround:**

- Go into preferences and clear browsing data. Close and relaunch.
- Go through QR code set up again. Works as normal.

Clearing of browsing data and subsequent QR code set up must be done every time the program is closed before it can be used.

**Comment by quanglam2807** [comment]
Related to #182, #199.

**Comment by Woafmann** [comment]
WhatsApp appears to be working correctly after update to Version 13.9.1 (13.9.1.317). Further testing should be done, but this issue does appear to be fixed. I've relaunched several times without needing to clear the browser data. Will report if the situation changes.

Thank you for the regular updates! I appreciate your dedication to this app!

**Comment by quanglam2807** [comment]
@Woafmann Thanks a lot for reporting! It's properly because the last update updates Electron 4.2.0 and it's related to this PR: https://github.com/electron/electron/pull/18094. Anyway, I'll close the issue. If it doesn't work again, please let me know.

**Comment by Woafmann** [comment]
Will do and thanks again!
