### ISSUE TITLE
Make app cards smaller

### ISSUE THREAD

**Issue by macdaddy1944** [webcatalog/webcatalog-legacy#246]
Open to the installed pages rather than the main one. Also, make the tiles smaller or allow different sizes as after a while it gets hard to navigate.

**Comment by quanglam2807** [comment]
Thank you very much for the feedback. But I’m sorry that I won’t move forward with those requests.

**Comment by macdaddy1944** [comment]
Unfortunately the current version of the app is not terribly end-user friendly. I will have to look for alternatives for my clients.

**Comment by quanglam2807** [comment]
@macdaddy1944 I'm sorry that the app doesn't work well for you. I'll try to improve it in the upcoming releases.
