### ISSUE TITLE
App installation from directory in name fails

### ISSUE THREAD

**Issue by emailalinda** [webcatalog/webcatalog-legacy#25]
nor many other apps. says 
I get the message "We're sorry. WebCatalog has failed to install Google Calendar." why would this be? 

![image](https://user-images.githubusercontent.com/34095565/37258471-d6360f66-2578-11e8-8b53-9a05d1a4342c.png)

**Comment by quanglam2807** [comment]
Only with Google Calendar?

**Comment by emailalinda** [comment]
many other appls too, in fact cannot manage with any i have tried...
i have been using an older version of Webcatalog which allowed me to install some apps, version 9.2.1, but at some point it stopped working to install new apps and some of the ones installed stopped working. so i now installed this version, 1.2.1, but with this one its not working to install anything. 
i have not uninstalled the 9.2.1 version yet, because at least some apps are working with it and i dont know what I would do without it, i just love webcatalog! it saves me tons of time.

**Comment by quanglam2807** [comment]
@emailalinda It's a bug on the server. It'll be fixed in about 15 minutes 👍

**Comment by emailalinda** [comment]
Wow, thank you so much, its working now!!!
Awesome, this is such a great app.
