### ISSUE TITLE
notion.so google oauth login not working

### ISSUE THREAD

**Issue by jottr** [webcatalog/webcatalog-legacy#257]
Adding notion.so as a custom app, with the URL https://www.notion.so doesn't work. 
After logging in with the google account the URL redirect seems to not work, resulting in a blank page.
Please either add notion.so to the list of supported apps, or help fix this issue. 

`Version 13.10.0 (13.10.0.331)`

**Comment by quanglam2807** [comment]
This relies on Electron. So let's hope upcoming version of Electron will fix this issue. At the moment, you can use the official Notion app.

**Comment by oporpino** [comment]
It still happens to me.
