### ISSUE TITLE
Google Voice drops calls

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#258]
**Web Catalog version:**
Version 13.10.0 (13.10.0.331)

**Issue:**
Google Voice functions correctly for several minutes and then disconnects the call. Program window becomes blank (dark gray) upon call drop. Page must be reloaded or relaunched to regain functionality. 

Repeated attempts to place calls results in the same behavior.

Calls made to cell phones, landlines and VoIP phones all result in the same behavior.

**Steps taken in an unsuccessful attempt to fix Issue:**

1. Ensured Web Catalog is updated to most recent version
2. Cleared browser data/cache in Google Voice
3. Uninstalled Google Voice
4. Re-installed Google Voice
5. Logged into my account as normal
6. Made call to a cell phone in my possession. Call dropped after 2 minutes, 19 seconds.

**Comment by quanglam2807** [comment]
This bug is pretty much related to Electron. So let wait for next Electron version to see if it fixes this. If not, there's nothing I can do.
