### ISSUE TITLE
feature: Add ability to import and export workspaces info for each app

### ISSUE THREAD

**Issue by pastmaster007** [webcatalog/webcatalog-legacy#260]
use case:
on new system or on cache clear, app should reconfigure workspaces based on file. 
Workspace export file should have at least email id, home page link, customized workspace name, app name.

This workspace file could be uploaded in either individual app or webcatalog app to configure.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
