### ISSUE TITLE
Add shortcut bar with user customized links

### ISSUE THREAD

**Issue by pastmaster007** [webcatalog/webcatalog-legacy#261]
Use case:
sometimes, we need to goto other app under same account like, i use outlook and azure. If i have azure website shortcut in outlook app, that would be great. And these shortcuts could be part of workspace info export file as mentioned in #260 

Any thoughts?

**Comment by quanglam2807** [comment]
I'm not sure if I understand this request correctly. Is it like browser bookmarks?

**Comment by linonetwo** [comment]
@pastmaster007 may be you need https://github.com/atomery/singlebox

**Comment by marcusquinn** [comment]
> I'm not sure if I understand this request correctly. Is it like browser bookmarks?

I think so - either way, having the Bookmark Bar available in the Electron web app browsers would be very useful!

**Comment by marcusquinn** [comment]
And another 10-licence bounty from me if you can do this please? ;)

It doesn't need to be a full-blown bookmark manager, just a bookmark bar.

This will then mean I can eliminate all use of the non-Electron WebApp browsers that I have to use - and these Electron browsers I'm finding 5 times faster to load and much more CPU & RAM efficient than any of the full-blown browser bloatware :)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
