### ISSUE TITLE
Add .vscode/launch.json

### ISSUE THREAD

**Issue by pastmaster007** [webcatalog/webcatalog-legacy#262]
could you add `.vscode/launch.json` file? If not, what setup do you use for debugging purpose?

**Comment by quanglam2807** [comment]
I tried to add this but it's so annoying to figure out how to do it right. 

Basically, right now I just run the code with `yarn electron-dev` and use `console.log` and other methods to debug.

**Comment by quanglam2807** [comment]
I'm sorry but since the project has become much more complicated, I won't be able to work on this.
