### ISSUE TITLE
Add user defined allowed domain names

### ISSUE THREAD

**Issue by pastmaster007** [webcatalog/webcatalog-legacy#263]
Use case:
For azure website, there are lot of different types of subdomains and domains involved like `microsoftonline.com`, `azure.com`, and `visualstudio.com`, etc..
It will be great, if we can add custom domains to be allowed from preferences.
And should sync with workspace settings in file as mentioned in #260.

**Comment by quanglam2807** [comment]
Thank you for the feedback! I'm sorry for not responding to this request earlier. 

This is quite essential to the app experience. Do you guys have any more suggestions to how this should be implemented? In the recent releases, the app is much smarter in detecting internal links but indeed, in many cases, it fails to detect.

**Comment by alex-solovyev** [comment]
That could be something simple like in `Unite 3`:

<img width="562" alt="Screenshot 2020-04-23 at 17 20 46" src="https://user-images.githubusercontent.com/1556417/80149517-d793df80-85c7-11ea-9574-9ade6db99829.png">
<img width="562" alt="Screenshot 2020-04-23 at 17 20 54" src="https://user-images.githubusercontent.com/1556417/80149539-e24e7480-85c7-11ea-8abc-287f052c60d4.png">

or thorough like in `Choosy`
<img width="707" alt="Screenshot 2020-04-23 at 17 21 21" src="https://user-images.githubusercontent.com/1556417/80149611-027e3380-85c8-11ea-90cd-e1badee17bde.png">
<img width="592" alt="Screenshot 2020-04-23 at 17 21 48" src="https://user-images.githubusercontent.com/1556417/80149621-0742e780-85c8-11ea-9c27-762f770accf3.png">
<img width="600" alt="Screenshot 2020-04-23 at 17 22 01" src="https://user-images.githubusercontent.com/1556417/80149638-0d38c880-85c8-11ea-8d62-397e440d826f.png">

It would be great to move custom rules to determine internal/external url from `webcatalog` (`template/public/libs/views.js`) to the web app database, having predefined rules there.

**Comment by quanglam2807** [comment]
@alex-solovyev Thank you for the suggestions! The idea looks great and I'll try to work on it ASAP.
