### ISSUE TITLE
Add media keys support

### ISSUE THREAD

**Issue by domparry** [webcatalog/webcatalog-legacy#264]
It would be awesome if you could turn on media keys for a specific app in Webcatalog. Lots of the apps that wrap media sites could benefit.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
