### ISSUE TITLE
Creating custom apps reuse old icons from cache

### ISSUE THREAD

**Issue by JaminZ22** [webcatalog/webcatalog-legacy#278]
When attempting to change a custom app's icon by uninstalling a custom app and creating a "new" one, the new app retains the old icon. I've attempted changing the icon's file name, but this doesn't help. Creating a new app with a new name works fine, so it appears that there is some cached/historical data being retained.

**Comment by quanglam2807** [comment]
Thanks for reporting! I'll try to fix ASAP. By the way, are you using Linux or macOS?

**Comment by JaminZ22** [comment]
macOS Mojave 10.14.3

**Comment by quanglam2807** [comment]
I'll close the issue for now as I consider it's stale. Feel free to comments if the bug still occurs.
