### ISSUE TITLE
Gmail notifications don't show up

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#282]
There are two issues with the gmail app: no email count and no notification when there is a new mail. When there should be a notification, the app bounces (native OSX behavior) and gives the warning :

> Grrr! A pop-up blocker may be preventing the application from opening the page. If you have a pop-up blocker, try disabling it to open the window.

**Comment by floriandierickx** [comment]
A little clarification on this : actually there is a notification in the notification center, and when you click on it you get redirected to gmail in the default browser, and at the same time the webcatalog gmail app indicates the error described above (Grrr!... :) ). 

The issue of no email count in the OSX dock icon remains.

**Comment by quanglam2807** [comment]
I also started to encounter this bug recently. I'll see what I can do to fix this.
