### ISSUE TITLE
Spell checker doesn't detect language correctly

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#288]
> Good morning  Currently, the latest versions do not work spell checking in the default language that is configured in the macOS system.  Regardless of the system language, spelling checks only work for English.  For this reason, I am forced to use the 12 version, which works correctly in spell checking.  Best regards, Karol M__

**Comment by nilswald** [comment]
plus: disabling spell checker in the preferences has no effect.

**Comment by quanglam2807** [comment]
> plus: disabling spell checker in the preferences has no effect.

This will be fixed with #306.

**Comment by andoro** [comment]
Hi, is this live in the current version? I even can't find the option to turn off totally spell cheching. It's very very annoying. Thanks!

**Comment by quanglam2807** [comment]
<img width="912" alt="Screen Shot 2019-11-07 at 3 17 42 PM" src="https://user-images.githubusercontent.com/1548835/68428441-d08c2880-0171-11ea-85f6-3dc36d975770.png">
@andoro Yes, there's an option called "Use spell checker" in app's Preferences.

**Comment by andoro** [comment]
Oh thanks, I searched it in the Webcatalog preferences...

Andor

**Comment by quanglam2807** [comment]
Related to https://github.com/electron-userland/electron-spellchecker/issues/85

**Comment by quanglam2807** [comment]
Electron now supports spellchecker natively: https://github.com/electron/electron/pull/20692

**Comment by quanglam2807** [comment]
Fixed with #611.
