### ISSUE TITLE
Distinguish single-page apps from ordinary websites

### ISSUE THREAD

**Issue by Erudition** [webcatalog/webcatalog-legacy#29]
Hi! New contributor here - great project.
# Problem
Although SSBs can be used for browsing any old website, even one that has an app-like aesthetic, users such as myself (and I assume many others) just want them for actual _Web Applications_ - typically a single, JS-heavy page.

**Example of a true Web App**
Messenger.com

**Example of a... web site**
Kickstarter.com

While these both have Material design feels, the former is clearly a single-page web app (just like its native mobile counterpart) while the latter is a live listing of projects on a website that all have dedicated pages.

# Rationale
I personally would never really want to containerize the latter not just because I wouldn't see as much of a need to leave it open all the time,  but also because the lack of browser chrome is actually a hindrance in that case - and the isolation of the app conveys little benefits. 

### Examples
On Kickstarter you are highly likely, for example, to encounter external links. In a browser you would simply open a new tab without launching another application (annoying to do a lot) because it belonged there in the first place. You would likely want to browse multiple projects at a time, which is what the browser's tab interface was made for. On Messenger, though, the only "tab-able" content is already in a conveniently tabbable format. There is little reason to have multiple instances of it (which can cause issues anyway). There is an obvious reason to leave it open indefinitely.

# Solutions
## Tags and filters
I'm sure some people will disagree with me so rather than ditching these allegedly non-app items altogether what if we could hide them from the catalog? In this case I would suggest a tagging system and an option to filter the catalog by tags.

**Comment by quanglam2807** [comment]
Thanks a lot for the idea, @Erudition! Actually, it's possible. The directory itself is open source: https://github.com/quanglam2807/webcatalog/tree/master/directory/apps so we can add a tag to distinguish the apps. But there are a few hundreds apps so it would be challenging to test and categorize every website.

**Comment by nblackburn** [comment]
I am with you here, i don't think websites should be wrapped, only applications.

**Comment by quanglam2807** [comment]
@nblackburn It's possible but to add the tag for the whole directory would be very time-consuming. :(

**Comment by nblackburn** [comment]
@quanglam2807 how would you want to structure this?

```yaml
name: 'Amazon Drive'
url: 'https://www.amazon.com/clouddrive'
category: Productivity
tags:
  - app
```

**Comment by quanglam2807** [comment]
@nblackburn What about this?
```yaml
name: 'Amazon Drive'
url: 'https://www.amazon.com/clouddrive'
category: Productivity
pwa: true
```

**Comment by nblackburn** [comment]
@quanglam2807 With you refering to them as tags, i made it an array but a single property works too which is what i originally thought. I would however be hesitent to name it `PWA` as not all apps meet that criteria. Instead i would simply call it app as it covers a wider area.

**Comment by quanglam2807** [comment]
@nblackburn OK, I agree! But what are the criteria to decide whether an URL is an app or a traditional website?

**Comment by nblackburn** [comment]
@quanglam2807 That is a tricky one that i think more than 1 person needs to answer until we come to some sort of agreement.

> The primary purpose of a website is to convay information where as a application is there to interact with information.

**Comment by Erudition** [comment]
Let's decide based on some concrete examples.
Definitely a webapp:
**Messenger.com**
Definitely not a webapp:
**Amazon.com**
Hopefully we can agree on these extremes.

## What makes Messenger such a webapp?

- Everything in a single page, by design.
- All navigation is ajax
- Browser's Back/forward buttons are not assumed nor needed
- Handles incoming information and updates without page refresh
- Logic to notify of changes in connectivity
- Fully responsive, smallscreen-first design
- Buttons on interface - not links
- Icons on buttons (not text)
- Any links always open in new window
- Layout attached to viewport - no scrollbar for page (scrollbars in smaller elements)
- Clear indication of "where you are" in the app without assuming browser title or address bar
- Notifications are timely and useful. An app you might want to keep open, and check often.

Am I missing something? 
Not every webapp has all of these, but most do (including Google apps such as Maps, Calendar, etc).

## Now, what makes Amazon so clearly _not_ a webapp?

- Navigation in header
- links everywhere
- millions of pages, with the assumption you'll be jumping between them (no ajax)
- static pages - with the assumption the same thing will always be found in the same place
- Entire page scrolls down, (!) layout of items rarely stuck to viewport
- page stays the same when disconnected, next navigation simply fails
- Few non-urgent notifications, most might as well be emails
- No reason you'd need to leave it open to check back often for updates

That's off the top of my head. Not exactly sure what the golden criterion would be, but it could also be a small checklist. 

All in all, it's usually pretty intuitive to discern whether a given online experience was designed app-like or not. We only need to separate the grey areas - "apps" such as Google search. Google is shipped as a dedicated app on Android, and all links open externally, but:
1) launching other sites externally is its whole purpose, rather than a feature, and
2) It's not something you'd really need to check back on often (the results page is static) except to look something else up (meaning no need to leave it running), and
3) It's centered around navigating the web - which is what a browser is for.

I'd be in favor of a stricter policy, rather than a more inclusive one - drawing the line somewhere _before_ a search engine counts as a webapp.

**Comment by nblackburn** [comment]
@Erudition There are some good pointers on here but i don't agree with all of them. I think the main ones are...

- No page refreshes (single page, routing is done on the client, use of push state).
- Data is requested and updated behind the scenes (use of XHR, sockets and other protocols).

I think it is safe to say we eliminate ecommerce platforms and search engines.

You can also look for hints like in the URL for `app.domain.com` as an indicator of what the developers consider their project to be.

**Comment by MichaelTunnell** [comment]
I agree with @nblackburn that the list provided by @Erudition has good points but is likely over-the-top. For example, I don't think it really matters how buttons are designed or whether or not the webapp is responsively designed. I want this for integrating with my desktop so responsiveness isn't really that important to the implementation.

I think a webapp classification should be basically what @nblackburn defined. Self-Contained Interfaces that don't rely on traditional browser paradigms.

**Comment by Erudition** [comment]
@MichaelTunnell That's fine too, but to defend my point about responsiveness a bit, a desktop app is exactly where you'd want responsive layout. On mobile you almost always have an app full-screen, so the only changing to consider is rotating the screen. But on Desktop people use windows that aren't always maximized, especially for multitasking. The best desktop apps are responsive: they are still useful even when you resize the window to something small.

I have Messenger always in the top corner of my screen, for example. It's shrunk down considerably, so messenger collapses the list of contacts into profile pictures only, and tucks away the sidebar, so that there's more room for what counts: the conversation view. it's perfect. Same thing with Todoist, in the other corner of my screen.

Indeed, some of the things I listed may not be _what makes a webapp_ so much as _what makes a good webapp_. But I was never trying to say that each characteristic alone would qualify something as a webapp by itself - merely saying that holistically, these are _signs_ that the page is a webapp. Of course many webapps break one or more of these paradigms.

@nblackburn I agree. ecommerce and search engines are definitely out.
