### ISSUE TITLE
JS Code injection doesn't work correctly

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#290]
Looks like JS Code injection is not working. I used this simple javascript:

```
window.onload = function(){
  alert('hello world');
  document.getElementById('username').value = 'hello world';
};
```

But nothing happens when I reload the entire app.

**Comment by quanglam2807** [comment]
@martijnbeets This is odd. What version are you using? I just tested it with Messenger on my Mac and it works.
