### ISSUE TITLE
No notifications at all for Gmail

### ISSUE THREAD

**Issue by Nerioth11** [webcatalog/webcatalog-legacy#296]
No notifications in OS X when receiving an email in your inbox and Sidebar doesn't hide at all for Gmail (Calendar for example works perfectly).

**Comment by quanglam2807** [comment]
Thank you for the feedback! 

- **No notifications in OS X when receiving an email in your inbox:** Have you turned on desktop notification in Gmail settings: https://support.google.com/mail/answer/1075549?co=GENIE.Platform%3DDesktop&hl=en.
- **Sidebar doesn't hide at all for Gmail:** Have you turned off sidebar in the app preferences (Cmd+,)?

**Comment by mmcnl** [comment]
Hi @quanglam2807, I am having the same issue with no notifications popping up (despite having turned on desktop notifications in Gmail). I am using the built in version of Gmail from the latest version of Web Catalog (Version v4.6.2). There are no related notifications in Notification Center at all.

**Comment by quanglam2807** [comment]
I'm using WebCatalog + Gmail myself and it works for me. So I'll close this issue for now. If it still doesn't work for you guys, please let me know.
