### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by nblackburn** [webcatalog/webcatalog-legacy#3]
Add support for Windows.

**Comment by quanglam2807** [comment]
I don't think I have time to work on this. Also, there're a few reasons not to resolve this issue:
1. Microsoft will start to support Progressive Web Apps on Windows 10 soon: https://blogs.windows.com/msedgedev/2018/02/06/welcoming-progressive-web-apps-edge-windows-10/
2. It's time-consuming to maintain the app on Windows. Personally, I'm a Mac user. And macOS & Linux both use Unix while Windows doesn't.
3. It costs nearly 200 USD every year to pay for a win32 certificate.
