### ISSUE TITLE
Changing the workspace in Asana opens link in default browser

### ISSUE THREAD

**Issue by nilswald** [webcatalog/webcatalog-legacy#315]
When I select a different workspace using the account menu, it gets opened in Safari. In v4.4.1. this was not an issue.

**Comment by quanglam2807** [comment]
Is this fixed in the latest version, @nilswald?

**Comment by nilswald** [comment]
Unfortunately not. Web Catalog version is v17.8.2, Asana app shows v5.5.2

**Comment by quanglam2807** [comment]
@nilswald Thanks for the fast reply! Would you mind providing the URL opened in the browser? You can remove private info from the URL if needed. :)

**Comment by nilswald** [comment]
it seems to go straight to https://app.asana.com/0/home/***************

**Comment by quanglam2807** [comment]
@nilswald  Oh well, I see the problem. Can you change the custom workspace home URL to `https://app.asana.com` to see if it fixes the bug?

**Comment by nilswald** [comment]
Now it opens a new window in the Asana app.

**Comment by quanglam2807** [comment]
Thanks a lot, @nilswald. It'll be fixed completely in the next update.

**Comment by quanglam2807** [comment]
I've released the update yesterday. Please let me know if it fixes the issue.

**Comment by nilswald** [comment]
I am happy to confirm – Thanks!
