### ISSUE TITLE
Cannot open new link in google calendar

### ISSUE THREAD

**Issue by FLXT-Qi** [webcatalog/webcatalog-legacy#321]
If an event has a description which contains the link, the latest version of webcatalog can not open the link in the default browser, just stuck at this.
![image](https://user-images.githubusercontent.com/52406244/65473665-8a7f3d80-de2d-11e9-92b7-ed1d59087792.png)

**Comment by mshick** [comment]
Same here. It seems limited to links in Google Calendar, and happens on both links in event notes, and other UI elements that would spawn an external browser, like the Google Account button under the user icon in the upper-right.

**Comment by mshick** [comment]
I should also note, it's limited to the Electron-built app for me. In a Chrome-built app links work.
