### ISSUE TITLE
Workspace switching icons too sensitive to movement

### ISSUE THREAD

**Issue by mshick** [webcatalog/webcatalog-legacy#333]
I've noticed in the GCal and Gmail Electron-packaged apps that switching workspaces via clicking is highly sensitive to mouse / trackpad movement in a way that leads most clicks to fail, with the click registering instead as an attempt to drag the icon. There are no issues using the keyboard shortcuts, and if I'm very careful clicking I can get the workspace to switch, but it takes a concerted effort. I never have issues like this with other apps, and Slack, for instance, follows a very similar UI pattern.

**Comment by quanglam2807** [comment]
Thank you for the feedback. I set the `pressDelay` to `100ms` and it doesn't seem to be too responsive on my Macbook. Anyway, I'll increase it to `250ms` to see if it works better.
