### ISSUE TITLE
Add dock badge support

### ISSUE THREAD

**Issue by madeleineostoja** [webcatalog/webcatalog-legacy#34]
One of the neat features [Nativefier](https://github.com/jiahaog/nativefier) has is passing a `--counter` flag that will attempt to parse notification-looking titles (eg: `(3) Facebook`) and turn them into notification dots on the app icon. Would be great for Webcatalog to automatically attempt something similar.

**Comment by quanglam2807** [comment]
WebCatalog Lite relies on Chrome which is hard to make this possible. 

Let's wait for the release of Juli github.com/quanglam2807/juli which is built on Electron and supports dock badge.

**Comment by madeleineostoja** [comment]
👍 No worries. Will Juli have a shared runtime or bundle up each app with its own copy of Electron? Biggest benefit of Webcatalog IMO is the shared/always up to date runtime, Chrome or otherwise

**Comment by quanglam2807** [comment]
@seaneking Yes, it will. Each Juli app takes about 15 MB.

**Comment by madeleineostoja** [comment]
Nice! Will keep an eye on it

**Comment by madeleineostoja** [comment]
Juli is amazing, insta-purchased a pro license. Thanks!
