### ISSUE TITLE
Window loses drag capabilities after switching workspaces

### ISSUE THREAD

**Issue by mshick** [webcatalog/webcatalog-legacy#354]
With the most recent update I've noticed a regression where Electron-built apps are losing their ability to be dragged after switching workspaces. Same situation using the sidebar, top navigation bar, and standard top bar. 100% reproducible on my system — macOS 10.14.6.

**Comment by quanglam2807** [comment]
Thank you for reporting this! This bug is so strange

**Comment by quanglam2807** [comment]
Honestly, I don't know where to start with this one. It's really really odd. I'm not sure if it has something to do with `electron@7` or not.

**Comment by quanglam2807** [comment]
It's an `electron@7` bug, I have reported it :)

**Comment by mshick** [comment]
Thanks for the thorough investigation! Any chance you can release a downgrade until they resolve this? Very difficult to work with, and that Electron issue doesn't seem to be moving.

**Comment by quanglam2807** [comment]
Sure, @mshick! After this incident, I won't rush to update Electron in the future. The update with Electron 6'll be available in about 3 hours. :) Thanks a lot for reporting this bug as it is so critical to the app.
