### ISSUE TITLE
Facebook Messenger notification badge is blinking

### ISSUE THREAD

**Issue by andoro** [webcatalog/webcatalog-legacy#358]
There is a flickering when I get notifications, I mean the number of messages is blinking.

**Comment by quanglam2807** [comment]
Thanks for reporting. The badge is based on the page title. For example, if the page title is **(5) Facebook Messenger**, then the badge would show 5. But whenever there're new messages, Messenger blinks the page title which leads to the badge to also blink. So I don't know what would be the best way to fix this at the moment.

**Comment by quanglam2807** [comment]
Let's move the discussion to https://github.com/webcatalog/webcatalog-app/issues/1425
