### ISSUE TITLE
App installation fails on Linux when ~.local/share/applications is not created

### ISSUE THREAD

**Issue by JairLeBentz** [webcatalog/webcatalog-legacy#37]
Hi guys,
I tried the last version of webcatalog and I never had any problem.
Now with this new version I can't install any software.
when I tried to install I become this: "We're sorry. Webcatalog has failed ton install...."

I wanted to purchase the payed version but with this problem I won't do it.
Thanks

**Comment by quanglam2807** [comment]
Actually, I'll make the app completely free soon.

Can you go open View > Developer Tools and check what it says in the Console? It would help me a lot.

**Comment by JairLeBentz** [comment]
Thanks for your answer.
I did this: right click mouse and "run in Konsole"
I got this:
Checking for update
Update for version 1.3.2 is not available (latest version: 1.3.2, downgrade is disallowed.
Nothing else.
Hopping that could help you

**Comment by quanglam2807** [comment]
@JairLeBentz I think it didn't give you a clear instruction. I mean, on the menu bar of the app, you'll see View > Developer Tools. It'll open a Developer Tools window with a Console tab on it. Something like this:

<img width="988" alt="screen shot 2018-03-24 at 3 10 10 am" src="https://user-images.githubusercontent.com/1548835/37861870-e5c6410c-2f10-11e8-88b2-a60b0ab3f2f0.png">

**Comment by JairLeBentz** [comment]
Hi again. yeah that is what I thought at the first sight but I didn't find this option.
On the menu bar of the pp I get only:
-Activate
-Change browser
-Help
-About

No further options

**Comment by quanglam2807** [comment]
@JairLeBentz Actually, you can just use `Ctrl+Shift+I` and it'll show up.

**Comment by JairLeBentz** [comment]
Thanks, that was helpful.
I tried to install **Ivoxx**, that is the Console text:

```
> _Error: Command failed: /tmp/.org.chromium.Chromium.lmK0ue iVoox https://www.ivoox.com ivoox /tmp/tmp-9817Lc1CHiu375xb/webcatalog-1521880896818.png AudioVideo;Music chromium
> /tmp/.org.chromium.Chromium.lmK0ue: line 38: /home/jairo/.local/share/applications/webcatalog-ivoox.desktop: No such file or directory
> 
>     at ChildProcess.exithandler (child_process.js:282)
>     at emitTwo (events.js:125)
>     at ChildProcess.emit (events.js:213)
>     at maybeClose (internal/child_process.js:921)
>     at Socket.stream.socket.on (internal/child_process.js:348)
>     at emitOne (events.js:115)
>     at Socket.emit (events.js:210)
>     at Pipe._handle.close [as _onclose] (net.js:549)
> actions.js:51 Error: Installing failed.
>     at EventEmitter.t (install-app-async.js:21)
>     at emitThree (events.js:140)
>     at EventEmitter.emit (events.js:216)_
```

or maybe **instagram**:

```
> Error: Command failed: /tmp/.org.chromium.Chromium.lmK0ue Instagram https://instagram.com instagram /tmp/tmp-9817Nrz732jvGC6n/webcatalog-1521881020257.png Other chromium
> /tmp/.org.chromium.Chromium.lmK0ue: line 38: /home/jairo/.local/share/applications/webcatalog-instagram.desktop: No such file or directory
> 
>     at ChildProcess.exithandler (child_process.js:282)
>     at emitTwo (events.js:125)
>     at ChildProcess.emit (events.js:213)
>     at maybeClose (internal/child_process.js:921)
>     at Socket.stream.socket.on (internal/child_process.js:348)
>     at emitOne (events.js:115)
>     at Socket.emit (events.js:210)
>     at Pipe._handle.close [as _onclose] (net.js:549)
> actions.js:51 Error: Installing failed.
>     at EventEmitter.t (install-app-async.js:21)
>     at emitThree (events.js:140)
>     at EventEmitter.emit (events.js:216)
```

**Comment by quanglam2807** [comment]
Nice.  Can you manually create a folder at ‘~.local/share/applications’ and
try again?

**Comment by JairLeBentz** [comment]
yeah, that help.
I could install instagram
Thanks!!
