### ISSUE TITLE
feature: Focus webview on initial load

### ISSUE THREAD

**Issue by lightheaded** [webcatalog/webcatalog-legacy#398]
# Feature Request
**Describe the Feature Request**
Set focus to the WebView upon opening the app. 

**Describe Preferred Solution**
Whenever opening a WebCatalog app, I would like to start using the app's own shortcuts, e.g. J and K to switch periods in Google Calendar or C in Gmail to compose a message. Currently I have to first click into the app and only then I can use shortcuts. This is especially disturbing when working with multiple calendars and switching between them with Cmd+1/Cmd+2 etc.

**Describe Alternatives**
Only current alternative to automatically setting the focus is clicking inside the window.

**Comment by quanglam2807** [comment]
Thanks a lot for the feedback! This would be a quick fix. It's strange that nobody has reported this until now.
