### ISSUE TITLE
feature: Add tabs for apps

### ISSUE THREAD

**Issue by Kuvesz** [webcatalog/webcatalog-legacy#438]
Feature Request
**Describe the Feature Request**
I love the app and to me it seems it's the only one to include Firefox support, thanks guys! I would just really like to see an option to open apps in tabs inside the WebCatalog window instead of new windows.

**Describe Preferred Solution**
Something like what Rambox or Franz does.
Take a look at the icons on the top here for example: 
https://www.omgubuntu.co.uk/wp-content/uploads/2016/06/Screen-Shot-2016-06-29-at-19.02.20.png

**Describe Alternatives**
I'm not sure of there are any.

**Additional Context**
The only other issue concerning anything similar to this was #62 but it's not really the same.

**Comment by quanglam2807** [comment]
Thanks for the feedback, @Kuvesz. Have you tried the workspace feature of WebCatalog? If you install an app using Electron, you can turn on Preferences > Show side bar to switch between workspace easily. 

If you mean something different, just let me know.

**Comment by Kuvesz** [comment]
Sorry, I didn't recieve and e-mail about you replying for whatever reason. I'll check it out. :)

**Comment by quanglam2807** [comment]
> Within a WebCatalog workspace (site), how do I open multiple tabs? I’m working in MeisterTask (similar to Trello), which allows multiple “projects” (each is a kanban board). I’d like to have multiple tabs within the MeisterTask workspace, each with a different project board. Brett

**Comment by quanglam2807** [comment]
Let's move the discussion to #684.
