### ISSUE TITLE
feature: Improved workspace memory management

### ISSUE THREAD

**Issue by grumphus** [webcatalog/webcatalog-legacy#451]
Hello. One of the issues I have encountered when adding like 5 workspaces is that certain sites like Gmail use a ridiculous amount of CPU usage and RAM when the app is launched. It's like if an app has 5 workspaces and you launch the app, all 5 of those workspaces are immediately loaded into memory even if only the first workspace is active.

What I would like to see is an option where other workspaces are put into memory upon activating so only the first workspace is loaded when you launch the app. I'd like to add so many workspaces but I will never want them all in memory at the same time. Maybe I only want workspaces 1,3 and 5 active and another day and maybe 2 and 4.

It would also be a nice extra if you can a right-click option to the workspace button called "Close Workspace" which won't delete the workspace but just release it from memory.

Thank you!

**Comment by quanglam2807** [comment]
Thanks for the feedback! This is partially resolved with https://github.com/quanglam2807/webcatalog/pull/444. And I'll try to resolve this completely in near future.

**Comment by quanglam2807** [comment]
I just released v18.0.0 with workspace hibernation feature. Please give it try :). You'll need to go to the website to download it since it's not officially released.

**Comment by grumphus** [comment]
Hi Quang. Thank you very much for all the quick support and speedy
releases :)

The hibernation feature is a good first start although not quite what I really need (would still prefer an option to hibernate all workspaces on startup but keep them in memory upon activation) but really happy to know the others will be addressed in the future. Thanks again and cheers!

**Comment by quanglam2807** [comment]
@grumphus Thank you for the response! The features you requested are now available in v18.4.0. https://github.com/quanglam2807/webcatalog/releases/tag/v18.4.0. You'll need to download it from the website since the update is not fully released.

Please give it a try and let me know if everything works correctly.
