### ISSUE TITLE
bug: Google prevents signing in because of security concerns

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#455]
# Bug Report
**Current Behavior:**

<img width="552" alt="Screen Shot 2019-12-09 at 3 44 09 PM" src="https://user-images.githubusercontent.com/1548835/70475796-f1121000-1a9a-11ea-912b-2c3a060771eb.png">

**Expected Behavior:**

Should be able to sign in with Google

**Steps to Reproduce:**

**Additional Context**

**Comment by quanglam2807** [comment]
This bug is quite critical. Does anyone have the same issue?

**Comment by quanglam2807** [comment]
At the moment, reloading the page a few times fixes the bug. So it's pretty random.

**Comment by ltishkevich** [comment]
seeing this as a persistent issue as well-- multiple refreshes is not fixing this for me.

**Comment by quanglam2807** [comment]
I'll try to upgrade the app to Electron 7/Chrome 78 this week to see if it fixes the issue.

**Comment by quanglam2807** [comment]
https://support.google.com/accounts/thread/22873505?hl=en
https://github.com/meetfranz/franz/issues/1720
https://ww.9to5google.com/2019/12/16/google-blocking-obscure-browsers-gmail/
https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/
https://www.omgubuntu.co.uk/2019/12/couldnt-sign-you-in-google-browser-error-linux
https://news.softpedia.com/news/several-linux-browsers-blocked-from-accessing-google-services-528591.shtml
https://meterpreter.org/google-prevents-certain-linux-web-browsers-from-using-its-services/
https://mashviral.com/google-blocks-some-linux-web-browsers-from-logging-in/

**Comment by quanglam2807** [comment]
Google is doing something again. A few users have reported this bug is slowly coming back.

**Comment by marcusquinn** [comment]
Is anyone using a GSuite Google ID for trying to login? If so, you need to add the App ID here:

https://admin.google.com/ac/owl/list?tab=apps

<img width="592" alt="image" src="https://user-images.githubusercontent.com/6428977/86521597-f37af380-be4a-11ea-9555-80621576cfe2.png">

**Comment by scottrbaxter** [comment]
Not the exact message, but I'm not able to log in with Google (https://mail.google.com), using the "Brave (tabbed)" browser engine.

> This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by scottrbaxter** [comment]
Got it working, though a bit hacky... [Brave](https://brave.com/) uses Chromium (just like Chrome), and it's able to use Chrome Web Store Extensions. I enabled [User-Agent Switcher](https://chrome.google.com/webstore/detail/user-agent-switcher/clddifkhlkcojbojppdojfeeikdkgiae), and set `Safari on Mac` - now able to auth successfully. Anyone with Chrome should be able to do the same.

I've yet to test out the WebCatalog user-agent, but i suspect modifying that to be more compatible may help satisfy Google's silly _security_ message.

**Comment by quanglam2807** [comment]
Thank you for info, @scottrbaxter. For what I understand, I think Google has some kind of signature check for Chromium-based browsers. So if the user-agent is changed to one from non-Chromium browsers like Firefox or Safari, the check will be ignored. 

For WebCatalog Engine (Electron), when the user go to accounts.google.com, the user-agent will be changed to legacy Microsoft Edge UA, and then switch back Chrome UA afterward.

**Comment by quanglam2807** [comment]
WebCatalog Engine automatically changes user-agent to bypass Google check. So I'll close this issue for now.
