### ISSUE TITLE
bug: External links are randomly opened in new window

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#467]
# Bug Report
**Current Behavior:**

Some users report that external links are opened in a new window.

**Expected Behavior:**

External links should be opened in the default browser

**Steps to Reproduce:**

**Additional Context**

**Comment by nirav** [comment]
This is happening to me. When I open any link from any email, it opens the in app (electron window) instead of opening in my default browser. :(

Links inside of email (for example an Amazon view order button) should open up in default browser where cookies are.

**Comment by quanglam2807** [comment]
@nirav Thanks a lot for the feedback! It happens because Gmail handles external links a bit different from other web apps. A fix will be available soon.
