### ISSUE TITLE
bug: AdGuard YouTube ad blocker is not compatible with the app

### ISSUE THREAD

**Issue by ekamran** [webcatalog/webcatalog-legacy#469]
I use AdGuard for mac which blocks the Ads on the network itself.
Works fine on Chrome.

Before the last 2 updates of WebCatalog, the Ad blocking was working well, blocking Ads on YouTube App. But it is no longer the case.

I use Google Chrome set up since the default option Electron was not supporting it.

**Comment by quanglam2807** [comment]
@ekamran Thanks for the feedback. I don't use AdGuard but I don't think it's possible to block YouTube ads at system-level. Do you use AdGuard extension for Chrome by any chance?

**Comment by ekamran** [comment]
Hi,
AdGuard blocks the Ads on YouTube.com completely including the internal Video Ads.

I still have AdGuard installed on mac and it works fine on a regular browser but not on WebCatalog.

I'm 200% sure that it use to work fine like 2-3 versions before on WebCatalog. In case you can provide me with the same, I can test it again.
No Adblockers extensions were in use.

**Comment by quanglam2807** [comment]
@ekamran Thanks for the response! You can download older version of the app here: https://github.com/quanglam2807/webcatalog/releases. Then you can reinstall your apps using the older version to test.

**Comment by ekamran** [comment]
So I downloaded v18.0.0 and YouTube is much cleaner.
I still see Ads on the Videos but the Website itself is clean.

**Comment by quanglam2807** [comment]
I think this issue happens because YouTube handles ads differently on different browser version. The older version of WebCatalog uses older version of Chromium so YouTube offers different behavior. AdGuard works at system-level so I don't think WebCatalog would have anything which prevents AdGuard from working properly.

So I'll close the issue for now. Feel free to comment if you have any new information.

**Comment by ekamran** [comment]
Quick update: This is much improved now, I see fewer ads on YouTube while using with Chrome.

However with Electron with a dedicated BLOCK ADS option shows all the YouTube Ads on the internet.

**Comment by quanglam2807** [comment]
Thank you for update. Honestly, I don't know how AdGuard only works with Chrome. I'll reopen this issue and will try to fix it in the future if possible.

**Comment by ekamran** [comment]
What is the possible reason that YouTube Ads are still visible on Electron? Especially when we’ve a dedicated Ad blocker option under it.

**Comment by quanglam2807** [comment]
The integrated ad blocker in WebCatalog doesn't support YouTube ad blocking. But honestly, I don't know what prevents AdGuard from working with Electron.

**Comment by ekamran** [comment]
If you need any assistance in testing AdGuard or need a license to try, I’ll be happy to help. 

This issue and Google Sign-in Bug just not allowing me to use WebCatalog at all.

**Comment by quanglam2807** [comment]
Thank you for the offer. It's OK, I'll try to get AdGuard on my own. I'll try to fix all these bugs ASAP.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
