### ISSUE TITLE
Add Caskroom/google-chrome support

### ISSUE THREAD

**Issue by minthemiddle** [webcatalog/webcatalog-legacy#47]
If you use [Homebrew](https://brew.sh/index_de) package manager on Mac to install Chrome and Chromium, you cannot use these engines, because the apps are not in `~/Applications` but in `/usr/local/Caskroom/google-chrome/latest` and Webcatalog does not recognize the path.

Installing Chrome again in `~/Applications` solves the problem for WebCatalog, but then you cannot take advantage of the package manager any longer.

The solution would be that WebCatalog knows the Homebrew Cask path.

**Comment by beorn** [comment]
Wasn't this done in https://github.com/webcatalog/appifier/issues/7 ?

**Comment by quanglam2807** [comment]
@beorn I just renamed the name of the issue to make it clearer. I will work on this ASAP.

**Comment by quanglam2807** [comment]
@minthemiddle I installed Google Chrome with Homebrew Cask but the installation path is `/Applications`. Did I miss anything?

<img width="558" alt="screen shot 2018-04-22 at 1 56 44 pm" src="https://user-images.githubusercontent.com/1548835/39098764-2263ceaa-4635-11e8-87e0-ac080c570653.png">

**Comment by minthemiddle** [comment]
Sorry, I fail to reproduce the error right now. If noone else has the problem, you may close the issue.
