### ISSUE TITLE
but: Google Voice unable to make calls

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#479]
**WebCatalog for Mac Version v18.3.3**

**Issue:**
Since 2 updates ago, WebCatalog's pre-made Google Voice app now requires a mobile phone to be linked in order to make outgoing calls which is a feature that can be activated but is not required for call functionality. The feature sends the outgoing call from the WebCatalog Google Voice app to the user's mobile phone number instead of placing the call directly through the computer.

**Testing:**
Accessing https://voice.google.com directly via Chrome and FireFox does not require a mobile phone to be linked and outgoing calls work correctly as expected.

Custom WebCatalog Electron app produces the same non-functioning result.

Custom WebCatalog Chrome-based app works correctly as expected.

Custom third-party Chrome-based app created with "EpiChrome" also works correctly as expected.

Official iOS app also works correctly (no mobile phone number association needed nor is a SIM card needed for that matter).

**Unsuccessful steps to resolve:**
Cleared cache.
Uninstalled and reinstalled the pre-made WebCatalog app.

Thank you for your hard work and dedication!

**Comment by quanglam2807** [comment]
@Woafmann Thank you very much for reporting! Fixed with #480!

**Comment by Woafmann** [comment]
Thank YOU for your quick fix! Tested and working!
