### ISSUE TITLE
Can't seem to launch two apps at the same time when using Juli

### ISSUE THREAD

**Issue by mattdelliott** [webcatalog/webcatalog-legacy#48]
I can't seem to have two web apps open if they both use Juli. Is this a known issue?

I get this on macOS High Sierra 10.13.4 (17E199):

<img width="532" alt="screen shot 2018-04-10 at 5 31 55 pm" src="https://user-images.githubusercontent.com/340321/38588832-14c3ce7a-3ce5-11e8-81ca-a15997be57c1.png">

**Comment by quanglam2807** [comment]
Thanks for reporting. I'll fix it ASAP.
