### ISSUE TITLE
bug: right-click does not work after being attached to taskbar in XFCE4

### ISSUE THREAD

**Issue by Bennett-Yang** [webcatalog/webcatalog-legacy#488]
# Bug Report
**Current Behavior:**

After being attached to taskbar, WebCatalog do not respond to right-click. The apps generated by WebCatalog neither. It happened when I am using XFCE4 on Arch Linux.

**Expected Behavior:**

Show me right click menu.

**Steps to Reproduce:**

Turn on "attach to taskbar" in preferences of apps.

**Additional Context**

XFCE4, Arch Linux.

**Comment by quanglam2807** [comment]
I just realize the bug is not fixed at all. I'll need to find other solution.

**Comment by quanglam2807** [comment]
Linux doesn't support right-click on taskbar item so I've add the menu options to the Preferences page. I hope it works for you.

**Comment by Bennett-Yang** [comment]
> Linux doesn't support right-click on taskbar item so I've add the menu options to the Preferences page. I hope it works for you.

It's embarrassing that I don't know right-click on taskbar is not supported on Linux. It seems works for me. Thank you
