### ISSUE TITLE
Broken certificate and email?

### ISSUE THREAD

**Issue by beorn** [webcatalog/webcatalog-legacy#49]
Hi, several of my WebCatalog apps seem to have stopped working properly (Asana, Facebook Messenger), and when I try to upgrade WebCatalog it fails, and when I manually go to webcatalog.io I get:
<img width="586" alt="screen shot 2018-04-13 at 13 01 47" src="https://user-images.githubusercontent.com/8559/38783962-36858aca-40bf-11e8-9bfd-2134126d0ea3.png">
<img width="476" alt="screen shot 2018-04-15 at 15 15 31" src="https://user-images.githubusercontent.com/8559/38783998-e5d90498-40bf-11e8-80a3-fa221d8a522e.png">

And when I try to email `support@getwebcatalog.com` I get:
```
The response was:
The recipient server did not accept our requests to connect.
Learn more at https://support.google.com/mail/answer/7720
[getwebcatalog.com 2400:cb00:2048:1::6818:6c69: timed out]

[getwebcatalog.com 2400:cb00:2048:1::6818:6d69: timed out] 
[getwebcatalog.com 104.24.109.105: timed out]
[getwebcatalog.com 104.24.108.105: timed out]
```

And it seems when I go to `webcatalog.com` the domain appears for sale.

**Comment by quanglam2807** [comment]
@beorn I'm sorry for the problem. I made many major changes in the past few months. The website is at https://getwebcatalog.com
