### ISSUE TITLE
bug: Xero internal links unexpected open in browser

### ISSUE THREAD

**Issue by wiiiimm** [webcatalog/webcatalog-legacy#499]
# Feature Request
**Describe the Feature Request**
Some sites require opening new pages as a new window. Right now it opens the new page in my default browser, but since it is a webapp requiring login, I have to re-login on my default browser just to use the new page opened.

**Describe Preferred Solution**
It would be good if a new window can pop up allowing me to interact with the new page.

**Describe Alternatives**
Currently the new page opens in my default browser and requires re-login.

**Additional Context**
I am actually using Xero, some function require a new page to be opened in a new window.

**Comment by quanglam2807** [comment]
Thanks a lot for reporting! It's actually a bug. I've fixed it in v18.7.0. Please let me know if it works.
