### ISSUE TITLE
Make links open in default browser

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#5]
I actually use Safari as my default browser, and the old Webcatalog respected that and opened links from its apps in Safari tabs.

Alternatively, Chrome would be fine if that's too difficult, except I would like it to use my default Chrome profile. Right now it seems that it creates a new Chrome profile which doesn't have any of my extensions, cookies, etc.

Side note, this is amazing 👏 
<img width="435" alt="screen shot 2018-02-28 at 12 08 59 pm" src="https://user-images.githubusercontent.com/157270/36810681-42dd6e5e-1c80-11e8-9326-f46726c11dd1.png">
definitely a huge win moving off Electron

**Comment by quanglam2807** [comment]
@swrobel Honestly, I don't know how to work on this.

**Comment by swrobel** [comment]
Ok, I figured this was probably a complexity of moving away from Electron. I suppose perhaps a Chrome extension that opens new windows in the default browser might do the trick, but #6 seems like a reasonable solution.

**Comment by quanglam2807** [comment]
@swrobel True! Temporarily, you can use the old version or install the extension for each app :)

**Comment by mr-islam** [comment]
I know that the command `open` on MacOS, (and `xdg-open` on Linux) when run with a URL, open it in the user's preferred browser. So running `xdg-open https://google.com` opens google in my default browser.

Maybe clicking on external links could call that command?

**Comment by quanglam2807** [comment]
It's not possible to customize Google Chrome. But this issue is resolved with Juli.
