### ISSUE TITLE
feature: Integrate with password manager

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#516]
# Feature Request
**Describe the Feature Request**

> I love this app it's been really helpful, the only thing I would suggest adding would be the ability to use password managers like lastpass. I'm using this WebCatalog on my work laptop and GSuite sessions expire daily so having a password manager would reduce the pain here.  Wayne

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

**Comment by macta** [comment]
Support for 1Password would be helpful too

**Comment by rthrash** [comment]
Would love to see 1Password support for sure.

**Comment by favincen** [comment]
Please also consider MacOS's integrated password manager: KeyChain . 
This is a must have for MacOS, and would be enough for most Mac users.

**Comment by favincen** [comment]
> Please also consider MacOS's integrated password manager: KeyChain .
> This is a must have for MacOS, and would be enough for most Mac users.

Hint: Keychain can be accessed and managed through API (obviously) but also through CLI (eg: https://www.aria.ai/blog/posts/storing-secrets-with-keychain.html ).

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
