### ISSUE TITLE
feature: remove workspace confirmation

### ISSUE THREAD

**Issue by skydiver** [webcatalog/webcatalog-legacy#517]
# Feature Request
**Describe the Feature Request**
Display a confirmation dialog when removing workspace.

**Describe Preferred Solution**
Show a confirmation dialog, ok/cancel buttons/

**Describe Alternatives**
An "undo remove workspace" functionality.

**Additional Context**
N/A

**Comment by quanglam2807** [comment]
Thanks for the suggestion! The reason I didn't add the confirmation is because to delete a workspace, you need right-click on the workspace icon first, so for me, it's unlikely that somebody would click the button by accident. Would you mind sharing why a confirmation dialog is needed?
