### ISSUE TITLE
feature: Go to URL on clipboard

### ISSUE THREAD

**Issue by smallhadroncollider** [webcatalog/webcatalog-legacy#527]
# Feature Request

I often get links to specific Google Docs/Sheets. As far as I can tell there's no way to get to these directly via the app.

It would be very useful if I could visit the URL on the clipboard and/or enter a URL manually if necessary.

An extra menu item in "History" called "Go to copied URL" (with a shortcut) that goes to the URL on the clipboard.

An address bar (like Fluid) would be another alternative.

**Comment by quanglam2807** [comment]
Thanks a lot for the suggestions! I'm working on the features. They'll be available in about one week.

**Comment by smallhadroncollider** [comment]
Amazing! Great little app.

**Comment by quanglam2807** [comment]
It's now available! Please give it a try: https://github.com/quanglam2807/webcatalog/releases/tag/v19.1.0.

**Comment by smallhadroncollider** [comment]
That's great. Thanks!
