### ISSUE TITLE
chromium bin is not recognized on Linux

### ISSUE THREAD

**Issue by aJesus37** [webcatalog/webcatalog-legacy#53]
### System Information

- **System:** Debian 9 Stretch KDE;
- **Kernel:** 4.9.0-6-amd64
- **Software Version:** 12.2.0-x86_64 AppImage
- **Chromium Version:** Version 66.0.3359.117 (Developer Build) built on Debian 9.4, running on Debian 9.4 (64-bit) (Installed from debian repo with apt)

### Steps

1. Download webcatalog AppImage
2. Run AppImage
3. Choose Chromium Engine

### Explanation

In the first use of webcatalog in my OS, it ain't recognize my Chromium installation (version above), showing "To continue, please install Chromium", but it's actually installed already.
Tested it in another debian 9 installation with XFCE, same problem.
 Please tell me if you need more info, or if I'm mistaking something.

**Comment by quanglam2807** [comment]
@JesusFromHellz Can you try to call `google-chrome` or `chromium-browser` from Terminal?

**Comment by aJesus37** [comment]
@quanglam2807 I can call `chromium`, not `chromium-browser`, guess it's a different bin naming issue, right?
I've created a symlink named `chromium-browser` to `chromium` in the `/usr/bin/` folder and now it's working. Maybe it's a distro specific different naming?
Let me know if you need more information :)

**Comment by quanglam2807** [comment]
@JesusFromHellz Thank you!! I'll try to make an update to resolve this.

**Comment by mr-islam** [comment]
On Solus, I have Google Chrome installed, but its bin is called `google-chrome-stable`. As mentioned above, symlinking that to `google-chrome` has things working now

It seems like across distros, there are different names being used for the same packages…

**Comment by quanglam2807** [comment]
As there're too many distros to support, instead of supporting all these namings, I'll add a note to the app linked to this issue for instructions.

How to create symlink: https://askubuntu.com/questions/56339/how-to-create-a-soft-or-symbolic-link
