### ISSUE TITLE
feature: in-app PDF reader

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#542]
# Feature Request
**Describe the Feature Request**

> Dear support,  I have found these issues with the app: - when a page wants to show a pdf, the app created with webcatalog asks for downloading it instead to show it - when a click to open in a new window, anything is loaded - tabs support is a must (I've seen in github that is a future in development)  My apps are Gmail, Zoho Books, Clickup.  Thanks Best regards / Fabio

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

**Comment by linonetwo** [comment]
mozilla/pdfjs

**Comment by quanglam2807** [comment]
https://stackoverflow.com/questions/52844135/how-to-view-a-pdf-in-an-electron-browserwindow

PDF Reader is disabled by Electron team. It'll be available with Electron 10 release. https://github.com/electron/electron/pull/21794

**Comment by quanglam2807** [comment]
Blocked by https://github.com/electron/electron/issues/22178
