### ISSUE TITLE
bug: Webview is not resized automatically when window is maximized

### ISSUE THREAD

**Issue by Gowee** [webcatalog/webcatalog-legacy#561]
# Bug Report
**Current Behavior:** The webview is not resized automatically when the window is maximized.

**Expected Behavior:** The webview is resized to fill the whole window automatically when the window is maximized.

**Steps to Reproduce:**

Maximize the app window via clicking the control button or the keyboard shortcut (Super + Up on GNOME).
Screen record: https://imgur.com/a/kwI5zxm

**Additional Context**

This behavior only exists on applications created by WebCatalog while the WebCatalog app itself works well.
WebCatalog Version: v19.3.3
DE: GNOME 3.43.3 GTK: 3.24.13

**Comment by quanglam2807** [comment]
Thanks for reporting! This is an Electron bug which only affects Linux but I managed to find a solution. The fix'll be available in the next update.
