### ISSUE TITLE
bug: unable to verify the first certificate

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#567]
# Bug Report
**Current Behavior:**

![WebCatalog_d08SEcHmX2](https://user-images.githubusercontent.com/1548835/75121758-abf28880-565c-11ea-9bc0-dcf931c0ae20.png)

> I have problem on Windows 10. Tried to re-install, but didn’t help. What can I do? Thank you!

**Expected Behavior:**

**Steps to Reproduce:**

**Additional Context**

**Comment by SK9MM777** [comment]
Same problem on macOS 10.15.3
![screenshot](https://user-images.githubusercontent.com/3936311/77409944-6986ad80-6dba-11ea-963a-f2fd3c6217c2.png)

**Comment by SK9MM777** [comment]
Found the solution. Adguard was responsible for the error. Adguard switched off and problem no longer exists.

**Comment by quanglam2807** [comment]
@CLUB777ONE Thank you for finding the solution! Can you let AdGuard knows about the issue as well? The error happens because AgGuard blocks the app from accessing https://github.com/atomery/webcatalog/releases/download/v19.7.1/template-darwin-x64.json properly.
