### ISSUE TITLE
feature: Ability to share current url (e.g. email or msg it)

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#571]
# Feature Request
**Describe the Feature Request**
Often when browsing a site, I want to share the current url with someone - e.g. email or message it, and there is no share button to pass the current url to another application.

**Describe Preferred Solution**
Provide a share button - on osx/ios the convention is to have an Up Arrow icon, or have a menu entry - Share. 
**Describe Alternatives**
If there was an easy way to copy the current url, that would work, but its not quite as nice (or might be useful to have both)

**Additional Context**
n/a

**Comment by quanglam2807** [comment]
Thanks for the feedback! This is currently blocked by https://github.com/electron/electron/issues/6330.

**Comment by macta** [comment]
Thanks, I added an upvote to the issue as well - but I notice that its been outstanding for several years now, so I’m guessing there isn’t much energy on it sadly (perhaps one day I might know enough to contribute in that area - I’ll keep it in the back of my mind).

**Comment by quanglam2807** [comment]
Thank you for assisting, @macta! The issue has been there for a while but it doesn't look stale for me so hopefully, somebody will work on it soon. :)

**Comment by quanglam2807** [comment]
Resolved with https://github.com/webcatalog/webcatalog-engine/pull/362
