### ISSUE TITLE
feature: Ability to change icon of current app

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#572]
# Feature Request
**Describe the Feature Request**
Having created an application with the default icon it suggested, I decided to improve the icon - but have to recreate the app all over again as there doesn't appear to be a way to replace the current icon.

**Describe Preferred Solution**
Have a setting to let you specify a new icon - like when you create the app

**Describe Alternatives**

**Additional Context**

**Comment by 4yourithing** [comment]
Also, related to icon. I deleted the app and recreated the app with a new icon. The new icon shows in installed apps but it shows the old icon in mac launcher and, when the app runs, it shows the old icon in the dock.

**Comment by quanglam2807** [comment]
I'll close this as the feature has been added some time ago
