### ISSUE TITLE
bug: failed to update apps

### ISSUE THREAD

**Issue by skydiver** [webcatalog/webcatalog-legacy#580]
# Bug Report
**Current Behavior:**
Using v19.4.0.
When trying to upgrade an app, i get `Failed to update Gmail. (Forked script failed to run correctly.)`

**Expected Behavior:**
App should be updated without problems.

**Steps to Reproduce:**
Goto installed tabs, click update on an outdated app.

**Additional Context**
macOS
![image](https://user-images.githubusercontent.com/578784/76028899-42069880-5f12-11ea-81c5-250ee7120a77.png)

**Comment by quanglam2807** [comment]
Thanks for reporting! It's fixed in v19.4.2

**Comment by quanglam2807** [comment]
The bug still persists if user hasn't configured proxy settings. Ref: https://github.com/atomery/webcatalog/issues/537#issuecomment-596408670

**Comment by skydiver** [comment]
@quanglam2807 the problem was solved
thanks 👍

**Comment by quanglam2807** [comment]
Thanks a lot, @skydiver. Resolved with #594.
