### ISSUE TITLE
feature: Localization

### ISSUE THREAD

**Issue by KovalevArtem** [webcatalog/webcatalog-legacy#591]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by quanglam2807** [comment]
Thanks for the suggestion! I'll add localization support in the future (probably this summer). At the moment, as I'm still bootstrapping the project so there're other priorities to work on.

**Comment by mccoy88f** [comment]
Hi... i add another feature request like this... Any news?

**Comment by quanglam2807** [comment]
@mccoy88f You mean in the Chromeless repo?

**Comment by mccoy88f** [comment]
It also can be good. But i bought pro version so i like to have it in italian. I can also help to translate. :-)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
