### ISSUE TITLE
feature: Minimize apps to tray on Windows

### ISSUE THREAD

**Issue by Wesley444** [webcatalog/webcatalog-legacy#597]
# Feature Request
**Describe the Feature Request** It would be great if we have a feature like minimize an app to tray on Windows. Like if we click the close button it won't close, just minimize to tray. And if added this option to app preferences would be great! Like "If I click close button, do not close. Keep app working in the background and minimize to tray.

**Describe Preferred Solution** I think checkbox in-app preferences would be great! Especially for dropbox paper.

**Describe Alternatives** Or if we can choose tray mode for an app, but then we click on an icon it'll open as a windowed app.

**Additional Context** Like any other app on windows and Mac OS.

**Comment by quanglam2807** [comment]
Thanks for the feedback. For this feature, I'm thinking about a simpler solution. I'll add two options: "show dock/taskbar icon" and "show menubar/tray icon". You can click on either to show the app window. Would that work?

**Comment by Wesley444** [comment]
Yes, that would be awesome!

**Comment by F50Ci37Y** [comment]
Minimize apps to tray on **Linux** with **badge counter** like this:

![ksnip_20201125-012638](https://user-images.githubusercontent.com/20030910/100156085-96e1a900-2ebd-11eb-8d36-15189ca32eec.png)

**Comment by quanglam2807** [comment]
@fakhamatiaI I have add an option to show tray icon in the pre-release version of WebCatalog Engine: https://github.com/webcatalog/webcatalog-engine/pull/214

Due to system limitation, I won't able to add badge counter support. i'm sorry.
