### ISSUE TITLE
bug: Cannot read property webContents of null, uncaught exception

### ISSUE THREAD

**Issue by JordyScript** [webcatalog/webcatalog-legacy#615]
# Bug Report
**Current Behavior:**
Upon launching my electron installation of WhatsApp, the window opens, my workspaces are visible but the webapps themselves are not loading. Eventually when i click around the different workspaces this error shows up: 

![image](https://user-images.githubusercontent.com/35542866/77625623-33753500-6f44-11ea-96cf-274239e84af5.png)

I was able to use it before, but now this error comes up after relaunching the app.

**Expected Behavior:**
WhatsApp web should load in the workspaces.

**Steps to Reproduce:**
1. Install webcatalog
2. Insert product key
3. Install whatsapp
4. Open whatsapp
5. Create workspaces
6. Register phone / log in in each workspace
7. Close whatsapp
8. Open whatsapp

**Additional Context**
I'm using webcatalog on windows 10

**Comment by quanglam2807** [comment]
I'm sorry for the issue, @JordyScript. Would you mind sharing which version of WebCatalog are you running? I can't reproduce the bug with WebCatalog 20.0.1 on my machine.

**Comment by quanglam2807** [comment]
I've found the bug :) It'll be fixed in v20.0.2. Thank you for reporting!

**Comment by quanglam2807** [comment]
@JordyScript I have released the update. Please let me know if it works.

**Comment by JordyScript** [comment]
Seems to be fixed, I'm on version 20.0.5 now.

Thanks bro! You fixed that really quickly.

**Comment by quanglam2807** [comment]
That’s great! Thanks for letting me know.
