### ISSUE TITLE
bug: Google Voice Drops Calls

### ISSUE THREAD

**Issue by Woafmann** [webcatalog/webcatalog-legacy#620]
# Bug Report
**Current Behavior:**
Electron version of Google Voice: Calls drop after several minutes and then advise the user to enable microphone (even though the microphone is active and listening). Upon restart of app, microphone error message disappears and able to make call again for only a few minutes.

**Expected Behavior:**
Calls do not drop.

**Steps to Reproduce:**
Simply make a call and wait for a few minutes.

**Additional Context**
Using MacOS: Restarting app does not fix, nor upgrading to latest current build. Works perfectly fine in Chrome without dropping (even on lengthy calls). Restarting core audio does not fix.

Thanks!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
