### ISSUE TITLE
feature: hide side bar, title bar and navigation bar at the same time

### ISSUE THREAD

**Issue by nilswald** [webcatalog/webcatalog-legacy#624]
Flotato does that very nicely, e.g. with Asana.

**Comment by quanglam2807** [comment]
Thanks for suggestion. I think Flotato doesn't really hide title bar, it only changes the color of the title bar to match the page background. Is this something desirable?

<img width="894" alt="Screen Shot 2020-03-27 at 7 02 24 PM" src="https://user-images.githubusercontent.com/1548835/77754302-a6be9a00-705d-11ea-9b2c-0af303bbde94.png">

**Comment by nilswald** [comment]
screen real estate-wise it is like WebCatalog but without the the sidebar. The title bar seems to be completely hidden. The window controls are still existent but invisible - which is ok. It feels more like an app rather than a browser window.

Flotato:

![Flotato](https://user-images.githubusercontent.com/1010163/77755184-02246400-702d-11ea-8ee4-4a309bacc196.png)

WebCatalog:

![WebCatalog](https://user-images.githubusercontent.com/1010163/77755188-03559100-702d-11ea-9e0b-abbaff010745.png)

**Comment by quanglam2807** [comment]
Thanks for clarification! Flotato seems to work better when turning on `Never shows windows buttons` option. If that option is off (default), the app is quite buggy as it needs to calculate the app background and changes the top gap color accordingly. But it makes sense as Flotato needs the gap to display the windows buttons without overlapping the web frame below. 

![1](https://user-images.githubusercontent.com/1548835/77757213-62ce9380-7063-11ea-978a-a55050bacf33.png)
![2](https://user-images.githubusercontent.com/1548835/77757215-64985700-7063-11ea-81fe-1ef615c83319.png)
![3](https://user-images.githubusercontent.com/1548835/77757217-6530ed80-7063-11ea-8c9f-50799eb0784a.png)

And certainly, as this solution (visible windows buttons + fake transparent title bar) is quite buggy, I won't go with it in WebCatalog

On the other hand, if `Never shows windows buttons` is on, it works quite nicely. So if I go ahead with this feature request, it means to hide side bar, title bar and navigation bar at the same time, windows buttons would be to be hidden as well (similar to Flotato).

**Comment by nilswald** [comment]
as commands are always accessible via window menu this should be ok ux-wise. Also if you as a user decide to hide the title bar, no buttons as a result should be experienced as a logical consequence. So, as for me: thumbs up!

**Comment by quanglam2807** [comment]
one last question before I add this. If the title bar is hidden, Flotato adds a hidden bar on top of the website which allows you to drag the app window around. Is it necessary? It's easy to similar bar to WebCatalog but I guess if the web apps have buttons at the same place, that bar would prevent you from clicking them?

**Comment by nilswald** [comment]
that's a good point. But maybe you can just add a small area for dragging, this should work for the majority of sites/apps. In case there is an app where this does not work one is still free to not hide the title bar. Not being able to drag a window seems not desirable - for instance if you have a second monitor.



-- 

FMGARAGE

Typenoffene Datenbank-Werkstatt
Spezialist für FileMaker Pro®

Kastanienallee 21 · 10435 Berlin

Tel. 030 609 88 89-22
Fax 030 609 88 89-32
https://fmgarage.com

FMGarage e.K. 
Amtsgericht Charlottenburg 
HRA 48653 B

**Comment by quanglam2807** [comment]
Resolve with #822. I'll cut a release soon :)

**Comment by quanglam2807** [comment]
It seems like dragging works with certain apps but doesn't with others. I'll work on a fix.

**Comment by nilswald** [comment]
Looks very nice! Thank you!
