### ISSUE TITLE
Provide access to basic browser navitation tools

### ISSUE THREAD

**Issue by mr-mmmmore** [webcatalog/webcatalog-legacy#63]
I find it frustrating not to be able to navigate in the apps like i normally do in a web app. It's neat to have a desktop-like feel when using the apps through WebCatalog, but since the content comes from the web I need the usual tools of a web browser.

The features of a web browser that I miss the more:

- Go back
- Be informed of pending page loadings with an animation
- Access the url to sometimes directly jump to the desired location using copy/paste
- Open links in tabs (already mentioned in issue #62)

With Fluid apps that I was using before, there are options to display these functionalities. It would be great if you could add these here too.

The main benefit of WebCatalog is to encapsulate a whole web app into a desktop app with all its context data, it is not necessary to "hide" the fact that it is sill the web, or at least this could be left to the user to decide.

**Comment by quanglam2807** [comment]
@mr-mmmmore This would be fixed if you use Juli as the engine.

**Comment by mr-mmmmore** [comment]
Sorry for the delay, I had missed your reply. I find that you have closed the issue too fast as your answer doesn't really solve the problems I have listed.

I have tried Juli and although it has some of the features I mention, it doesn't have all of them, especially it misses the tabs that apps have when using Chrome as the engine (although they open in a different window).

With Juli, WebCatalog apps still miss:

- Being able to open tabs (in the same window)
- Display a loading animation of pages
- Force the url by typing/pasting into a field

Although I prefer the nice UI Juli provide, I think I will stick to Chrome as the engine as long as Juli doesn't handle tabs. Do you plan to add these to Juli soon? It would be awesome!

**Comment by quanglam2807** [comment]
Thanks for the feedback. I'll try to add these features in the future!
