### ISSUE TITLE
bug: Cannot create an app for Guardian.co.uk - get error: Unsupported mime type

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#630]
# Bug Report
**Current Behavior:**

When you create a custom app for guardian.co.uk and accept the defaults, you get an error:
```
Failed to install Guardian. (Error: Unsupported MIME type: image/x-icon
    at Jimp.throwError (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/@jimp/utils/dist/index.js:35:13)
    at Jimp.parseBitmap (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/@jimp/core/dist/utils/image-bitmap.js:117:32)
    at Jimp.parseBitmap (/Applications/WebCatalog.app/Contents/Resources/app/node_modules/@jimp/core/dist/index.js:521:32)
    at /Applications/WebCatalog.app/Contents/Resources/app/node_modules/@jimp/core/dist/index.js:463:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3))
```
**Expected Behavior:**

Should create the app like for other sites
**Steps to Reproduce:**

Type in guardian.co.uk into the url box, press tab and it provided the default guardian logo (from their site)
**Additional Context**

If you reset the icon you can create the app - so there is something up with the web icon - at the very least you should catch the error and provide a default?

**Comment by quanglam2807** [comment]
Thank you for the feedback!!

This is what causes the bug: Guardian has this line of code
```<link rel="shortcut icon" type="image/png" href="https://assets.guim.co.uk/images/favicons/46bd2faa1ab438684a6d4528a655a8bd/32x32.ico"/>```
Anyway, I'll add more check to the code.

**Comment by macta** [comment]
That’s a bit naughty of them… but I guess its better if you can add an extra check as I’m sure other sites may have been sloppy too.

Thanks for this project, its very useful.

**Comment by quanglam2807** [comment]
Definitely! I'll cut a release shortly.
