### ISSUE TITLE
bug: Main app is not updated correctly if using AppImageLauncher

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#634]
# Bug Report
**Current Behavior:**

> the .appimage doesn't updated it self like on windows or macOS. is there any debug log i can see or send you?

**Expected Behavior:**

**Steps to Reproduce:**

**Additional Context**

**Comment by quanglam2807** [comment]
See https://github.com/electron-userland/electron-builder/issues/4046

**Comment by quanglam2807** [comment]
This issue occurs in AppImage distributions of all Atomery apps. At the moment, for the updater to work properly, please avoid using `AppImageLauncher` to run/install the app. 

```
chmod a+x AppName*.AppImage
./AppName*.AppImage
```

**Comment by quanglam2807** [comment]
Preventing user from running updater is a bad solution as if user runs the app "Once" using AppImageLauncher, `process.env.DESKTOPINTEGRATION === 'AppImageLauncher'` is still `true`. So there's no way for user to bypass AppImageLauncher.

**Comment by TheAssassin** [comment]
Please see https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-699743169. You can revert #642 again.

**Comment by quanglam2807** [comment]
@TheAssassin Thank you so much! I made the change.
