### ISSUE TITLE
feature: Ability to edit app url (e.g. change .com to .co.uk)

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#643]
# Feature Request
Some of the webcatolog apps are US based (e.g. amazon.com), rather than creating a localised app, could you let us edit the app url, so that the app launches to the new url and the home button uses that new url as well. A good example is amazon.com - when in the uk, I want to go to amazon.co.uk

**Describe Preferred Solution**

Provide a setting option that shows the current url, and lets you edit it.

**Describe Alternatives**

Give instructions as to where the url is located in the generated app, and we can hack it ourselves

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for the feedback. Actually, you can select Workspaces > Edit Workspace to change the URL. I’ll try to make the UI clearer in upcoming updates.

**Comment by marcusquinn** [comment]
How about having buttons:

INSTALL   CUSTOM

<img width="179" alt="image" src="https://user-images.githubusercontent.com/6428977/79514336-da2d8c80-803d-11ea-9fb6-3f2d71ade6d2.png">

(I need to reboot before doing a Photoshop job on it...)

**Comment by marcusquinn** [comment]
Maybe this? I've brightened the blue for better readability contrast too:

![image](https://user-images.githubusercontent.com/6428977/79584740-b7938600-80c6-11ea-80df-70266e15fddd.png)

**Comment by linonetwo** [comment]
<img width="576" alt="Screen Shot 2020-04-18 at 6 53 53 PM" src="https://user-images.githubusercontent.com/3746270/79635837-f4827a00-81a5-11ea-88b3-425b03cbabef.png">

Hey, this have been implemented!

**Comment by marcusquinn** [comment]
> <img alt="Screen Shot 2020-04-18 at 6 53 53 PM" width="576" src="https://user-images.githubusercontent.com/3746270/79635837-f4827a00-81a5-11ea-88b3-425b03cbabef.png">
> 
> Hey, this have been implemented!

Sure, I know that :)

Just a UI alternative option if you get more people asking that didn't spot that ;)

**Comment by linonetwo** [comment]
Maybe this should go into the documentation or FAQ. Instead of adding a short cut button to a button on the menu?

**Comment by marcusquinn** [comment]
> Maybe this should go into the documentation or FAQ. Instead of adding a short cut button to a button on the menu?

Or both?

Given that the most utility from WebCat comes from appified and containerised frequently accessed sites, perhaps making the visibility of that as a commonly use button would encourage a broader mind for usage possibilities, and turn more demo users into paying customers ;)
