### ISSUE TITLE
bug: 2/3 finger swipe to navigate is backwards ?

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#644]
# Bug Report
**Current Behavior:**

If you enable the swipe to navigate option, I have noticed that you have to swipe forwards to navigate backwards. This is the opposite from Safari and Chrome and is very confusing.

Note: I enabled the use 2 and 3 finger swipe gesture so that I could still use 2 fingers in Chrome - am I right in thinking that WebCatalog only supports 3 fingers? I wish it would support 2 like the browser).

**Expected Behavior:**

I should be able to swipe from right to left to go backwards, and left to right to go forward - however WebCatalog apps seem to do the opposite?

**Steps to Reproduce:**

**Additional Context**

**Comment by macta** [comment]
Hmmm seems to work as expected now, weird - maybe just a long day

**Comment by macta** [comment]
Actually, reopening as my BBC generated app is definitely working backwards (my Amazon one was, but then it seemed to correct itself). Something is fishy...

**Comment by quanglam2807** [comment]
Thanks for reporting! This bug seems really odd so it'd take some time before I can fix it. 

Two-finger swiping is not supported because Electron doesn't support it for some reasons. https://github.com/electron/electron/issues/2683

**Comment by linonetwo** [comment]
OH that's sad, I have already use 3-finger for selecting.
