### ISSUE TITLE
Automatic login not happening anymore

### ISSUE THREAD

**Issue by emailalinda** [webcatalog/webcatalog-legacy#65]
In the past, whenever I would open one of the apps it would log me in automatically ie to Gmail etc. but now it is requesting my password each time. What to do about this? I had 12.0, webcatalog lite, and  I have tried installing version 12.3 but it doesnt seem to make  a difference.

**Comment by quanglam2807** [comment]
@emailalinda I'm sorry for the issue. What engine are you using? Chrome or Juli?

**Comment by emailalinda** [comment]
Chrom

**Comment by emailalinda** [comment]
I don't hace a subscription but I'm thinking to get one of this gets sorted
out because I absolutely love webcatalog

**Comment by quanglam2807** [comment]
@emailalinda Please try to use Juli as the engine to see if it fixes the problem. :)
