### ISSUE TITLE
bug: The v20.1.0 release has no .exe available

### ISSUE THREAD

**Issue by Gowee** [webcatalog/webcatalog-legacy#650]
# Bug Report
**Current Behavior:**
The latest v20.1.0 release has no .exe available. The download buton on https://getwebcatalog.com/ links to a 404 not-found page.

**Expected Behavior:**
N/A

**Steps to Reproduce:**
N/A

**Additional Context**
N/A

**Comment by quanglam2807** [comment]
Thank you for reporting! Fixed with v20.1.1

a6c16ce6
