### ISSUE TITLE
feature: double click on title bar to expand

### ISSUE THREAD

**Issue by linonetwo** [webcatalog/webcatalog-legacy#656]
# Feature Request
**Describe the Feature Request**
In mac, double click on any app's title bar will make it expand (not full screen, just maximize it). But webcatalog generated app will not.

**Describe Preferred Solution**
Maybe electron have an API for this, I don't know.

**Describe Alternatives**
Drag the window to expand it by hand...

**Comment by quanglam2807** [comment]
Thanks a lot for the suggestion! This will be available in next update.
