### ISSUE TITLE
feature: delay load content at start up

### ISSUE THREAD

**Issue by linonetwo** [webcatalog/webcatalog-legacy#657]
# Feature Request
**Describe the Feature Request**
My network connection is established after MacOS start around 2-5s, so if I set an app generated by webcatalog, it will say network is bad.

This makes "open at start up" useless.

**Describe Preferred Solution**
A new config "delay loading content on start up" to delay the content loading.

**Describe Alternatives**
Click on "reload" button by hand.

Or A new config "retry after 404" to auto retry if network is bad.

Or I'm currently using following inject JS:

```js
const CHECK_ACTIVITY_INTERVAL = 1000 * 3;

let time = new Date().getTime();

const refreshTime = () => {
  time = new Date().getTime();
};

function refresh() {
    const serverNotStarted = !document || document.querySelector('.tc-site-title') === null;
  if (serverNotStarted) {
    window.location.reload(true);
  } else {
    setTimeout(refresh, CHECK_ACTIVITY_INTERVAL);
  }
}

setTimeout(refresh, CHECK_ACTIVITY_INTERVAL);
```

But it comes with overhead or maintainance.

**Additional Context**
I'm also loading a local server `localhost:xxx`'s content, and that server is fully started only after 5-10s after login.

**Comment by linonetwo** [comment]
I found `inject JS` not working after my manual refresh of window, is this a bug?

**Comment by quanglam2807** [comment]
Thanks for the feedback. #732 will automatically try to reload the websites if connection status changes. I don't expect it to resolve this issue but please give it a try first.

**Comment by linonetwo** [comment]
It works, thank you!

It works very well with a local server that started with [node-mac](https://www.npmjs.com/package/node-mac).
