### ISSUE TITLE
feature: register custom app scheme

### ISSUE THREAD

**Issue by linonetwo** [webcatalog/webcatalog-legacy#658]
# Feature Request
**Describe the Feature Request**
I'd like to open my custom app via a search from Alfred or Zazu (spotlight-like apps), so I need custom app registered a `x-my-app-scheme://foo` scheme.

**Describe Preferred Solution**
Use electron API https://www.electronjs.org/docs/api/protocol to do so.

I only know how I can do so in an electron app. But you generate child app from a master app...
I don't know the way you generate those child electron apps. So I don't know whether you can do such registration for each separate child electron app.

**Describe Alternatives**
Maybe it is similar to `Default web browser Make xxx the default web browser.`?

Or Actually, I want to open a url in that app, is it possible to do something like this?

```shell
% /Users//Applications/WebCatalog\ Apps/TiddlyWiki.app "127.0.0.1:11012/#:[regexp[\d+$]]"
zsh: permission denied: /Users//Applications/WebCatalog Apps/TiddlyWiki.app
```

note that `chmod +x /Users/linonetwo/Applications/WebCatalog\ Apps/TiddlyWiki.app` is not working.

**Additional Context**
I'd like to do this kind of search https://github.com/Jermolene/TiddlyWiki5/issues/2198#issuecomment-611431651 but I want it to be opened inside the app generated by webcatalog instead of open in the Firefox browser.

**Comment by quanglam2807** [comment]
I'll try to add protocol support! It won't be too difficult. For now you can do this:
`open -a /Users/Applications/WebCatalog\ Apps/TiddlyWiki.app "https://127.0.0.1:11012/#:[regexp[\d+$]]"`

**Comment by linonetwo** [comment]
Sadly, `#` will turn into `%23` in this way, resulting in a white screen. Very unfriendly to the SPA that uses the hash route.

And running `open -a /Users/linonetwo/Applications/WebCatalog\ Apps/TiddlyWiki.app "http://127.0.0.1:11012/#:[regexp[\d+$]]"` will not change app's url. Only if I quit the app, then this will work.

**Comment by linonetwo** [comment]
I think the only usage on the app scheme will be "open xxx hash route" since web app doesn't have a way to utilize advanced app scheme.
