### ISSUE TITLE
feature: Use the App Name in the Menubar and Activity Monitor

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#677]
# Feature Request

Use the App Name in the Menubar and Activity Monitor for the non-Electron browsers (as opposed to the browser name).

This makes it much easier to manage Keyboard Shortcuts through System Preferences and CPU usage through App Tamer.

**Additional Context**
Coherence & Unite from BZGApps does this if you need an example to see.

**Comment by quanglam2807** [comment]
Thanks a lot for the feedback, @surferking! This is now possible in v20.3.x. You'll need to update WebCatalog first and then use WebCatalog to update your Chrome-based apps.

**Comment by marcusquinn** [comment]
Brilliant - that works perfectly!

I highly recommend App Tamer too if you haven't already seen that other excellent Mac app: https://www.stclairsoft.com/AppTamer/
