### ISSUE TITLE
feature: Add password autofill support

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#678]
Add an option to save Passwords in Electron browsers - it just makes it a lot faster to continue working after a restart!

**Comment by quanglam2807** [comment]
There are many requests for this feature but storing passwords securely is a big concern for me. I'll leave this open for some time to get some more security feedbacks and do some research on this.

This is how Chrome implements it: https://security.stackexchange.com/questions/170481/how-secure-is-chrome-storing-a-password

**Comment by marcusquinn** [comment]
Sure, I understand - but that's a user choice based on their setup - it's not for us developers to judge on user preferences, just to offer the most secure defaults - as in not making saving password automatic and making confirmations not have the OK button by default.

Referring back to this also excellent Ferdi App, you'll see they offer an option App PIN feature in the settings, for those wanting both convenience and security: https://getferdi.com

**Comment by quanglam2807** [comment]
@surferking Thanks for comment! I'll probably try to store the passwords in the Keychain.

I'm also looking to add app PIN feature like Ferdi (#88). Btw, Ferdi stores the App PIN as plain text :(

**Comment by marcusquinn** [comment]
Cool - and eek on plaintext.

I have to say - of all the WebApp apps I've tried over the years, WebCatalog with Electron is by far the fastest for Apps to open, respond and least CPU & Ram usage!

**Comment by quanglam2807** [comment]
@surferking Thanks a lot for the compliments! :)

**Comment by dave-redfern** [comment]
Probably not possible but it would be great if 1Password support could be added; though not entirely sure how that would work in practice. Much like Keychain, would avoid the issue of encryption and security.

**Comment by quanglam2807** [comment]
@dave-redfern Thank you for the suggestion. We have a separate issue for password manager extension #710. But definitely, password manager integration is what I always want to integrate. But I'm afraid at the moment, it would be even more challenging than using Keychain as Electron, while supporting Chrome extensions, doesn't do it well. 

Still, storing is Keychain is totally possible and I'll work on it ASAP. Also, hopefully, Apple would release an official password filling API in the next macOS release like they did in iOS.

**Comment by marcusquinn** [comment]
Maybe of interest: https://cameronnokes.com/blog/how-to-securely-store-sensitive-information-in-electron-with-node-keytar/

**Comment by quanglam2807** [comment]
@surferking Thank you for sharing the post. `node-keytar` would definitely be used to store passwords.

The next step would be to figure out a standard way to detect password form & prompt user to save password/fill password. I'll probably use Firefox code for the purpose
https://stackoverflow.com/questions/2398763/how-does-browser-know-when-to-prompt-user-to-save-password
https://dxr.mozilla.org/firefox/source/toolkit/components/passwordmgr/src/nsLoginManager.js#626

But if you guys have better suggestions, that'd be great.

**Comment by marcusquinn** [comment]
Given that [Bitwarden Browser Extensions](https://github.com/bitwarden/browser) are open-source, maybe some ideas in that codebase?

**Comment by T0mu** [comment]
yes, please support password and cookie save.
it beats a lot of the advantage to have a dedicated webapp and then you spend more time than with a normal web page to reactivate your session.

**Comment by quanglam2807** [comment]
@T0mu Definitely, I'll work on this very soon. And actually, cookies are saved.

**Comment by T0mu** [comment]
> 
> And actually, cookies are saved.

Yes, sorry I have been imprecise.
BTW great work!

**Comment by marcusquinn** [comment]
Aside from regular bugs - I'd say this is the highest value feature need for me now.

Everything else you have done is amazing, and I recommend WebCat to everyone I know!

For me, this is the final missing piece of the puzzle.

**Comment by tblobaum** [comment]
+1

**Comment by GGORG0** [comment]
Is this discussion still active and will we get it?

**Comment by quanglam2807** [comment]
> Is this discussion still active and will we get it?

It’s still active but you’ll have to wait for some time

**Comment by halilacikgoz** [comment]
Is there any progress in that topic ?

**Comment by ylluminate** [comment]
Definitely need a Chrome/Firefox/Safari-like password save function with similar export of them. Thanks for having this on your priority list @quanglam2807.
