### ISSUE TITLE
feature: Opera browser

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#679]
# Feature Request

Opera browser as an option - allegedly the most CPU & RAM efficient of them all perhaps?

**Comment by quanglam2807** [comment]
Thanks for the suggestion! Even though Opera is based on Chrome, they made many changes and it's not possible to create a window-only Opera instance. It's possible to create Opera-based app with tabs but I'll add support for that together with other Chromium-based browser.

**Comment by marcusquinn** [comment]
Cool - Tabs (and Bookmark Bars) are still useful in WebApps, so I see that as a plus still - thank you kindly - keep up the great work!

**Comment by marcusquinn** [comment]
Loving using Opera again - making it my default main browser now!

https://forum.cloudron.io/topic/2929/rediscovering-opera

Electron is still great and preferred for my WebCat apps though 😸

**Comment by quanglam2807** [comment]
@marcusquinn 👍  Personally, I don't like Opera that much as I find its UI too clumsy. But anyway, everyone has different taste and I hope the new Opera option would be useful for you.
