### ISSUE TITLE
Chromium and Chrome is not recognized 

### ISSUE THREAD

**Issue by federicosnobohm** [webcatalog/webcatalog-legacy#68]
its not reconognize my two browsers (chromium or chrome) i dont know why, i am on manjaro cinnamon.

thanks

**Comment by quanglam2807** [comment]
@federicosnobohm I'm sorry for the inconvenience but on certain Linux distros, you need to manually create command-line symlinks. You can check this for instruction: https://github.com/webcatalog/webcatalog/issues/53
