### ISSUE TITLE
feature: Enable Tabs in Electron webapp browsers

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#684]
# Feature Request
**Describe the Feature Request**
Enable Tabs in Electron webapp browsers

**Describe Preferred Solution**
Tabs bar

**Describe Alternatives**
Workspaces are more appropriate as containers for separate logins, Tabs are more for web pages within the same login.

**Additional Context**
I often have an application, as an example, Google Analytic, open in a single window with tabs open for maybe a dozen different reports within the same account, that I can just then navigate between and refresh to see the latest data, or Xero where I can have a few different areas of work permanently open in tabs to work on multiple areas without losing the work for each while in-progress, etc, etc...

**Comment by marcusquinn** [comment]
How about another 10-licence bounty from me if you can do this please? ;)

This will then mean I can eliminate all use of the non-Electron WebApp browsers that I have to use - and these Electron browsers I'm finding 5 times faster to load and much more CPU & RAM efficient than any of the full-blown browser bloatware :)

**Comment by marcusquinn** [comment]
I found this "Min" browser on my travels to search for something Electron-based to replace Safari/Chrome for my daily Googling and browsing etc. It might contain some ideas for the Tabs interface:

- https://minbrowser.github.io/min/
- https://github.com/minbrowser/min

I also like the way they do the Preferences in a full-screen tab/window to save scrolling and that there's a list of all the keyboard shortcuts available and for customising.

Electron is the future - thank you for introducing me to it and all your brilliant work on multi-platform WebApps!

**Comment by quanglam2807** [comment]
Thanks a lot for all the information and nice words! I'm really appreciated. 

I'll definitely work on tabs soon. But because it is a big feature, I probably won't be able to get started before end of May. Implementing a feature would take quite some time as the app is not designed with tabs in mind. Also, the testing and polishing after that would take time as well. So please be patient. 

Btw, Electron is a great framework but the maintainers don't intend people to build browsers with it. Brave used to fork Electron, add extension support and build their browser with it but then it becomes too much for them to maintain so they ended up switching to Chrome. So I'm trying to move slowly to ensure WebCatalog and Singlebox won't end up in the same path (aka making the app too complicated and unmaintainable). 

Another browser built with Electron: https://beakerbrowser.com/

**Comment by marcusquinn** [comment]
Hey @quanglam2807 makes complete sense. I'm pretty sure all my tickets are all the features I could hope for and respect that it shouldn't try to be a complete full-featured browser.

I started out with using FluidApps many years ago, then Coherence and Unite for years, so I'm a long-running fan of having nicely organised WebApps.

It was only when I tried your solution I could see how slow Chrome is compare to Electron.

I definitely think you're onto being the best option for everyone, and something I will be recommending to everyone I know, so sure, happy to be patient, I've waited this long and I know development isn't always a smooth journey :)

**Comment by marcusquinn** [comment]
This would be really handy, since the point of webcatalog is having less windows in total, and it would mean less need for using other browser options.

**Comment by project-guru** [comment]
@quanglam2807 Dear Quam:

You and I chatted a couple of years ago where I had asked you about the possibility to add tabs (just like Chrome) to WebCatalog apps and you agreed that it was a good idea. 

Please tell me if this is now possible and if not, when do you think it will happen. I understand the complexity of this but it's something that I think would be extremely useful.

Thanks!

**Comment by marcusquinn** [comment]
Desperate for Tabs!

Just been using the free OnlyOffice app, which looks like Electron to me - their Tabs implementation is a great example!

**Comment by claytonolley** [comment]
I really need something with tabs support as well. I've used Coherence with mixed results, and am now trying Epichrome but it's getting shelved at the end of this year so on the hunt for another product!!

**Comment by project-guru** [comment]
I've used coherence too but had various issues as well.  I didn’t know they were discontinuing Epichrome. I like it better. Why are they shelving it and where did you hear that?

**Comment by claytonolley** [comment]
> I didn’t know they were discontinuing Epichrome. I like it better. Why are they shelving it and where did you hear that?

It's on their github page... they're looking for another maintainer... https://github.com/dmarmor/epichrome

**Comment by claytonolley** [comment]
> I didn’t know they were discontinuing Epichrome. I like it better. Why are they shelving it and where did you hear that?

It's on their github page... they're looking for another maintainer... https://github.com/dmarmor/epichrome

**Comment by project-guru** [comment]
@quanglam2807 So I guess no tabs feature for WebCatalog huh? :///

I've been using Epichrome but it's getting discontinued Dec 31st 2021. 

If WebCatalog isn't getting tabs, do you know of any other option?

Thanks!

**Comment by quanglam2807** [comment]
@project-guru Another team member is working on it. 

Also, https://webcatalog.io/chromeless/ works similarly to Epichrome so you can use it for now.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
