### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by lparsons** [webcatalog/webcatalog-legacy#7]
Would be great to see this able to use Firefox (my default browser).

**Comment by quanglam2807** [comment]
[Firefox implementation](https://www.reddit.com/r/linux/comments/7ivuit/create_firefoxbased_web_apps_for_gnome_and/) doesn't work as well as Chrome. It's still a normal Firefox UI but it runs in a different process. Should I add it?

<img width="1440" alt="screen shot 2018-02-28 at 7 37 18 pm" src="https://user-images.githubusercontent.com/1548835/36822715-0d0c5ef4-1cbf-11e8-9111-65dc467ea1a9.png">

**Comment by Erudition** [comment]
Absolutely. You can remove the GUI rather easily, even WebExtensions do that.
Looking forward to having my Firefox profile used.

**Comment by MichaelTunnell** [comment]
I am ok with not using Firefox but if I could it would be ideal. 

If you could somehow integrate with the [Container Tabs](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?src=search) system then that would be amazing!
