### ISSUE TITLE
Add support for Chrome extensions

### ISSUE THREAD

**Issue by mr-mmmmore** [webcatalog/webcatalog-legacy#70]
The title is self-explanatory...

It would be great either to benefit from the extensions already installed in Chrome, or to be able to install extensions directly in the Webcatalog app. In the latter case, the support of this feature for both apps with the Chrome and Juli engine would be awesome!

**Comment by quanglam2807** [comment]
Actually, you can install browser extensions with Chrome engine. The only limitation is that you need to install extensions for each app individually. In the case of Juli, as Electron doesn't support extensions, I can't do anything :(.

**Comment by sicahjes** [comment]
> Actually, you can install browser extensions with Chrome engine. The only limitation is that you need to install extensions for each app individually. In the case of Juli, as Electron doesn't support extensions, I can't do anything :(.

Are you able to offer some guidance on how to do this? When I navigate to the extension page, the download button is not available.
