### ISSUE TITLE
bug: default web page background color is not set correctly

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#723]
Also worth checking https://www.bbc.co.uk/news with the latest Electron version. I'm getting an unusual grey background even without Dark Reader running but could be related:

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/6428977/79403467-e571b100-7f86-11ea-9d47-7f402648cd9e.png">

_Originally posted by @surferking in https://github.com/atomery/webcatalog/issues/673#issuecomment-614355655_

**Comment by quanglam2807** [comment]
Thanks for reporting. So even with dark mode, all major browsers always use `#FFF` as default page background so this behavior needs to be replicated in WebCatalog.

**Comment by marcusquinn** [comment]
confirmed fixed
