### ISSUE TITLE
feature: add keyboard shortcut for catalog search

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#726]
# Feature Request
- Cmd/Ctrl-F to Search
- Escape-Key should clear the search and restore all results

**Comment by quanglam2807** [comment]
Thanks for the suggestion. I'm not sure if you mean something new. But WebCatalog already supports "Find in Page"

<img width="487" alt="Screen Shot 2020-04-17 at 11 16 10 AM" src="https://user-images.githubusercontent.com/1548835/79531568-fa406880-809c-11ea-8ceb-915279de0b94.png">

**Comment by marcusquinn** [comment]
I'm talking about this Algolia searchbar:

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/6428977/79587936-2b379200-80cb-11ea-9c1f-cc1097c891a5.png">

**Comment by linonetwo** [comment]
I think ctrl+F should also focus the search input.

**Comment by marcusquinn** [comment]
> I think ctrl+F should also focus the search input.

Exactly, yes please. (cmd on Mac ;)

**Comment by marcusquinn** [comment]
Once you have typed a search, cmd/ctrl-F should also then highlight all the search text for then overtyping with a new search.

**Comment by marcusquinn** [comment]
Escape key needs to clear the search too (equivalent to clicking on the X). Standardising stuff :)

**Comment by quanglam2807** [comment]
@surferking I'll add the auto highlighting. If the search input is focused, esc key should work already. So to clear search: Cmd+F then ESC

**Comment by marcusquinn** [comment]
Perfect now! One very happy keyboard warrior here 😁
