### ISSUE TITLE
bug: "This browser or app may not be secure" from Google

### ISSUE THREAD

**Issue by aakar** [webcatalog/webcatalog-legacy#729]
# Bug Report
**Current Behavior:**
Created a Gmail App with Chrome as the backend.  I receive a "This browser or app may not be secure" from Google when I try to sign in.  After doing a little bit of digging this seems to be a new thing that Google has been doing over the last year but it's become more prominent now.  
 
Installing this with the Electron browser works, but that removes the ability to use extensions like "Grammarly"

I have the most recent version of Chrome running: Version 81.0.4044.113 (Official Build) (64-bit)
Other Apps have run into this same issue but have adjusted their user-agent to say they are Firefox in which case some have had success: https://github.com/meetfranz/franz/issues/1720
  
**Expected Behavior:**
Should log me into Gmail.

**Steps to Reproduce:**
1. Install Gmail with Chrome backend
2. Try signing in

**Additional Context**
<img width="616" alt="Google_Calendar_-_Sign_in_to_Access___Edit_Your_Schedule" src="https://user-images.githubusercontent.com/337445/79515420-970bf300-8016-11ea-9b2e-9c76e7b108d5.png">

**Comment by marcusquinn** [comment]
Maybe related, maybe not: https://github.com/atomery/webcatalog/issues/714

**Comment by quanglam2807** [comment]
This is interesting. Chrome-based apps are literally an instance of Chrome so I don't know how Google can come up with this annoying detection.

**Comment by quanglam2807** [comment]
Can you try to delete this file to see if fixes the bug `~/Applications/WebCatalog Apps/Gmail.app/Contents/Resources/gmail.app/Contents/embedded.provisionprofile`?

**Comment by aakar** [comment]
Nope.  The way I've temporarily fixed it is by opening up developer tools and changing the user agent to Firefox.  That allows me to sign in 🤷

**Comment by mbierman** [comment]
I am seeing this too. I deleted the Google Voice app and recreated it and it went away though.

**Comment by quanglam2807** [comment]
Thanks for reporting, everyone. Google is actively blocking embedded browsers from logging in. We managed to find a workaround but it doesn't work all the time. :(

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
