### ISSUE TITLE
bug: unable to use .app artifact in downloaded *-mac.zip file

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#730]
# Bug Report
**Current Behavior:**
The Application can't be opened after extraction

**Expected Behavior:**
The Application can be opened after extraction

**Steps to Reproduce:**
Download "WebCatalog-20.4.1-mac.zip", and extract it, and try to open it

**Additional Context**
I think the last few builds are also broken. The ".dmg" version works. Tested on macOS 10.15.4

**Comment by quanglam2807** [comment]
Thanks for reporting! This is a bug in macOS 10.15. The OS corrupts *.zip file symlinks when extracting. I'm looking for solution. For now, you can download the .zip file through **Safari** and the app will work after extracting. 

Details: https://github.com/electron-userland/electron-builder/issues/4299

**Comment by quanglam2807** [comment]
Apple has also confirmed the bug: https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415

Apple recommends using `ditto` to extract the zip file instead of using built-in Archive Utility.

**Comment by ghost** [comment]
Based on that, they recommended to use ditto to create the zip, don't they? It indeed works if I use a different software to unpack.

**Comment by quanglam2807** [comment]
Yes, they do recommend `ditto`. But I don't know if this bug is really a bug or a "feature" as Apple doesn't fix it after 5 Catalina minor updates.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
