### ISSUE TITLE
bug: window location is not saved

### ISSUE THREAD

**Issue by artgru** [webcatalog/webcatalog-legacy#734]
# Feature Request
**Describe the Feature Request**
Whenever we relaunch an app, the window should open at the same place when it was closed earlier

**Describe Preferred Solution**
Keeping the window pos in the settings and reuse it when launching the app again

**Comment by quanglam2807** [comment]
Thanks for the feedback! Are you using Electron as the browser engine? If so, the app is supposed to save the window position. If you're using Electron and it doesn't work, please let me know.

**Comment by artgru** [comment]
I want to use all the features, so yes. Electron is my choice as the browser engine. What I can add is, I keep apps on my 2nd screen. 
They relaunch on the main screen.

**Comment by quanglam2807** [comment]
Thanks for information! Which OS are you using?

**Comment by artgru** [comment]
Win10 1909 (18363.778)

**Comment by quanglam2807** [comment]
This bug happened likely because the app crashed when exiting and failed to save the window location to disk. Since the crashing bug has been fixed, this bug is likely to be fixed as well. I'll close it for now.
