### ISSUE TITLE
feature: Type system password once to update all Apps installed in the main /Applications/WebCatalog/ directory

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#739]
Feature Request
**Describe the Feature Request**
I need to install all WebApps in the main /Applications/WebCatalog Apps folder so that they are available to the multi-user login I use on my computer for separate work/home profiles.

However, every time there is a WebCatalog update, I then need to update all WebApps and re-type the system password 25+ times.

**Describe Preferred Solution**
The ideal solution would be to type the system password once to update all Apps installed in the main /Applications/WebCatalog/ directory. Of course, I'm not even sure if that is possible but it would be great if it was.

**Comment by quanglam2807** [comment]
I find this annoying as well. But it seems like you don't need `sudo` to install app in `/Applications`. So I'll see if I can remove the `sudo` requirement altogether.

**Comment by quanglam2807** [comment]
Amazing! No need for `sudo` at all. I'll correct this ASAP.

**Comment by quanglam2807** [comment]
In the next update, if the change works correctly, you'll be prompt to give admin permission one last time for the app to correct `/Applications/WebCatalog Apps` directory owner from `root` to `$USER`. Then you'll no longer need to enter passwords to install apps.

For new user, no sudo prompt will be shown.

**Comment by marcusquinn** [comment]
Very cool!
