### ISSUE TITLE
bug: can't update the app inn v20.5.1

### ISSUE THREAD

**Issue by IBOYHK** [webcatalog/webcatalog-legacy#752]
# Bug Report
**Current Behavior:**
 can't update the electron app 

**Expected Behavior:**
.erro message 

**Steps to Reproduce:**

**Additional Context**

**Comment by IBOYHK** [comment]
this is a big bug, pls fix ASAP

**Comment by artgru** [comment]
![obraz](https://user-images.githubusercontent.com/37419387/79606731-597c9800-80f2-11ea-8a83-61c15e5446bf.png)

**Comment by quanglam2807** [comment]
Thanks a lot for reporting! A fix will be up in 10 minutes.
