### ISSUE TITLE
feature: Toggle nodeIntegration for power users

### ISSUE THREAD

**Issue by linonetwo** [webcatalog/webcatalog-legacy#754]
# Feature Request
**Describe the Feature Request**
In some hackable notebook, (TiddlyWiki, coda and Jupiter notebook...), user can create their own widgets. Sometimes they want to touch the file system by clicking a custom widget in the notebook.

Expose node to the web content will allow that happen to power users, and make the app take advantage of running in the electron, feeling really like a desktop app (compare to install a PWA to the desktop via Chrome).

**Describe Preferred Solution**
A simple toggle in the preference, that will set:

```js
      nodeIntegration: true,
      contextIsolation: false,
```

**Describe Alternatives**
Add an "Inject Preload Script" to safely inject wanted features to the web content. 

Instead of injecting it like normal "Inject JS"

https://github.com/atomery/webcatalog/blob/0cdea09e12eb82d061e3938ebd633df425aae757/template/public/preload/view.js#L61-L66

we can just eval it in the webcatalog/template/public/preload/view.js, letting it be part of preload.

**Additional Context**
I think people using this feature should know what they are doing, it will open a pandora's box, but come with great power provided for some special applications.

This can be another sell point for WebCatalog.

**Comment by linonetwo** [comment]
I think this will also enable user to modify context menu, if they expose context menu bulder to the renderer thread.

**Comment by quanglam2807** [comment]
Enabling `nodeIntegration` would be terrible for security. As it exposes all node.js API to the websites. So for example, if you go to untrustworthy site, they can trigger `require('fs')` or anything and do all kinds of naughty things. 

Instead, I'd suggest we can expose a set of selected API so user can use them in injection so user can call function like `window.webcatalog.setContextMenu(something);` or `window.webcatalog.setBadge` etc.

**Comment by linonetwo** [comment]
But actually I'd like to do `exec('shutdown -h now')`, or execute Apple Script to do Robotic process automation, only for selected trusted app.

`nodeIntegration` is bad, but expose selected API might be not enough, so maybe custom preload script it the only choice? User can use `ContextBridge` API by them self.

**Comment by linonetwo** [comment]
As long as the user doesn't expose `fs` directly to the renderer process, I think there is no danger.

**Comment by linonetwo** [comment]
https://github.com/atomery/webcatalog/pull/764

**Comment by linonetwo** [comment]
I think I can even run `execSync('path/to/an/app/server')` in Preload Script to start things like `open refine 、tiddlywiki、jupyter notebook、Jena`. And let the WebCatalog render the localhost app.

**Comment by linonetwo** [comment]
A simple example:

```js
const fs = require('fs');
const { contextBridge } = require('electron');
const homedir = require('os').homedir();

contextBridge.exposeInMainWorld('custom', {
  writeLog: (log) => fs.writeFileSync(`${homedir}/Desktop/aaa.log`, log),
  log: (log) => console.log(log),
});
console.log('ccc');
```

![IMAGE 2020-04-20 00:23:32](https://user-images.githubusercontent.com/3746270/79693433-2b878700-829d-11ea-9706-66094ac69e7e.jpg)

In the userland, there is no chance to access `fs` module, thanks to electron's context isolation.

This feature is basically not for a public website, but for companies' inner system, where they can custom the website, utilizing injected NodeJS features.

**Comment by quanglam2807** [comment]
Is this resolved with https://github.com/atomery/webcatalog/pull/764?

**Comment by linonetwo** [comment]
Yes, it works!

I'm now using it creating a plugin for TiddlyWiki, which can control the git state. I'm going to add more buttons to my wiki, make it look like VSCode.

So it is proved that this feature makes webcatalog really powerful, I'm going to write a blog about this.

The only small inconvenience is that I have to copy&paste code into it, and I can't share my configured app with my friends (since configs are not stored in the app's package). So I have to write a readme to ask my friend to do it by hand.
But this is good for security, just like the userscript manager tempermonkey will ask you to skim through the code before installing it. And sharing the configured app will reduce the chance they buy a license, which is not good for sustainable development.

Anyway, thank you for making such a powerful tool!
