### ISSUE TITLE
bug: (maybe) seems to be a longer white-screen delay on launch of WebCatalog than when I first started using

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#763]
# Bug Report
**Current Behavior:**
Just a *maybe* bug: it seems to be a longer white-screen delay on launch of WebCatalog than when I first started using.

**Expected Behavior:**
Launch as fast as the WebApps themselves.

**Steps to Reproduce:**
Restart the application.

**Additional Context**
![image](https://user-images.githubusercontent.com/6428977/79688733-20eed280-8248-11ea-81d7-653fe72536f4.png)

**Comment by quanglam2807** [comment]
I don't think I did anything that made the app slower, it's just the window is shown too early. I've made some adjustments to avoid displaying an empty window like this.

**Comment by marcusquinn** [comment]
Whatever you did in the last release seems to have made WebCatalog and the WebApps open much faster - thank you kindly!!
