### ISSUE TITLE
bug: macOS traffic light buttons are non-retina, and use old behaviour

### ISSUE THREAD

**Issue by danielcompton** [webcatalog/webcatalog-legacy#768]
# Bug Report
**Current Behavior:**

On macOS, the close buttons are non-retina and use old behaviour (coloured outlines around the buttons when application is not focused).

<img width="94" alt="Screenshot of Roam Research (20-04-20, 3-32-50 PM)" src="https://user-images.githubusercontent.com/811954/79711551-37fef480-831c-11ea-9754-7f9aa023a8f3.png">
<img width="236" alt="Screenshot of Roam Research (20-04-20, 3-32-26 PM)" src="https://user-images.githubusercontent.com/811954/79711528-2584bb00-831c-11ea-8105-22bc4fcac51d.png">
<img width="108" alt="Screenshot of Safari (20-04-20, 3-31-44 PM)" src="https://user-images.githubusercontent.com/811954/79711534-27e71500-831c-11ea-8572-14b85f53a8f6.png">

**Expected Behavior:**

Safari's buttons are sharp:

<img width="82" alt="Screenshot of Safari (20-04-20, 3-35-10 PM)" src="https://user-images.githubusercontent.com/811954/79711660-890ee880-831c-11ea-8f5a-bb3cb9757f72.png">
<img width="75" alt="Screenshot of Safari (20-04-20, 3-33-10 PM)" src="https://user-images.githubusercontent.com/811954/79711560-3f260280-831c-11ea-8f16-c329e1fb2760.png">
<img width="79" alt="Screenshot of Roam Research (20-04-20, 3-33-17 PM)" src="https://user-images.githubusercontent.com/811954/79711567-43eab680-831c-11ea-9209-395a99cd8cfa.png">

**Steps to Reproduce:**

* Create a WebCatalog app on a Mac
* Look at the titlebar

**Additional Context**

I'm running macOS 10.14.6 with WebCatalog v20.6.0.

**Comment by quanglam2807** [comment]
Thank you for the feedback! 

I tried to reproduce the bug but I can't do it?

<img width="872" alt="Screen Shot 2020-04-20 at 6 24 11 PM" src="https://user-images.githubusercontent.com/1548835/79746458-3b9e7580-8334-11ea-9041-135dbbb2ef18.png">
<img width="1306" alt="Screen Shot 2020-04-20 at 6 23 34 PM" src="https://user-images.githubusercontent.com/1548835/79746470-3f31fc80-8334-11ea-8990-08fa9f37bec0.png">

The traffic lights when unfocused look correct for me. Did I miss anything?

**Comment by danielcompton** [comment]
Which OS are you using when you run this? This is for the Roam Research all, in case that’s useful for reproduction.

**Comment by quanglam2807** [comment]
I’m using macOS Catalina. The UI/UX is supposed to be the same for all apps so I don’t think it’s because of Roam Research.

**Comment by linonetwo** [comment]
<img width="531" alt="Screen Shot 2020-04-21 at 12 07 42 PM" src="https://user-images.githubusercontent.com/3746270/79824364-b74a0200-83c8-11ea-9168-70a504c4d291.png">

It will display differently on different titlebar.

**Comment by quanglam2807** [comment]
Thanks a lot for investigating! It turns out the color of title bar is the bug. I'll need to change the color. Which one do you like better?

<img width="1347" alt="Screen Shot 2020-04-21 at 1 11 06 PM" src="https://user-images.githubusercontent.com/1548835/79831542-d00ae580-83d1-11ea-92fe-f3268128c666.png">
<img width="1347" alt="Screen Shot 2020-04-21 at 1 11 17 PM" src="https://user-images.githubusercontent.com/1548835/79831549-d26d3f80-83d1-11ea-9b64-1f3cf5271afa.png">

one is standard macOS color, one is Chrome color.

**Comment by danielcompton** [comment]
I prefer native wherever possible.

**Comment by quanglam2807** [comment]
Thank you! Fixed :)
