### ISSUE TITLE
users: A list of places to upvote WebCatalog to help our good developer friends make this App all we need it to be :)

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#772]
Upvote, leave nice comments & reviews - it's good development karma 😉 

- https://alternativeto.net/software/webcatalog/
- https://www.producthunt.com/posts/webcatalog

Add other links as I'm happy to help anything that helps the App development.

**Comment by marcusquinn** [comment]
Posted a couple of comments and links for interest too:
- https://www.reddit.com/r/discordapp/comments/ehdvkl/issues_with_updating_discord_discord_helper_on/
- https://support.discordapp.com/hc/en-us/community/posts/360055591352-Discord-is-Eating-a-lot-of-CPU-for-some-reason?page=1#community_comment_360010214371

**Comment by quanglam2807** [comment]
Thank you so much for this thread, Marcus. But I have to close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
