### ISSUE TITLE
bug: clicking "OPEN" on the installed section apps doesn't work

### ISSUE THREAD

**Issue by artgru** [webcatalog/webcatalog-legacy#773]
# Bug Report
**Current Behavior:**
Clicking OPEN gives no effect

**Expected Behavior:**
In one of the previous version, OPEN function was opening an app

**Steps to Reproduce:**
I'm using 20.7 version, go to installed apps tab and try to click OPEN any of them.

**Additional Context**
![obraz](https://user-images.githubusercontent.com/37419387/79845377-3e917880-83bd-11ea-859d-5aa2a3499982.png)

**Comment by marcusquinn** [comment]
Strange, working fine for me (Mac 10.14.6) WebCat 20.7.0)

**Comment by artgru** [comment]
bug seems to be gone after newest patch to version 20.9.0
