### ISSUE TITLE
feature: Make the Home URL editable in the WebApp Settings

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#776]
# Feature Request
**Describe the Feature Request**
Make the Home URL editable in the WebApp Settings

**Describe Preferred Solution**
Add the same Name & Home URL fields to the WebApp settings as are offered in the Workspace override settings.

![image](https://user-images.githubusercontent.com/6428977/79888959-4705a580-83f5-11ea-80e5-61a26deb666b.png)

![image](https://user-images.githubusercontent.com/6428977/79889077-6c92af00-83f5-11ea-9faa-22e0763847ee.png)

(side-note, I can't take screenshots of just these settings windows as they seem to be recognised as part of their parent window. Mac users that use cmd-shift-4 > space-bar will know what I mean.)

**Comment by quanglam2807** [comment]
> (side-note, I can't take screenshots of just these settings windows as they seem to be recognised as part of their parent window. Mac users that use cmd-shift-4 > space-bar will know what I mean.) 
I have adjusted this in the last update. You can now take screenshot of each window separately.

To avoid confusing users, I'll add an option to edit web app URL and icon in the main app instead of in each app preferences page. So let's move the discussion to #643
