### ISSUE TITLE
bug: Figma app /w Google Login does not work

### ISSUE THREAD

**Issue by wiiiimm** [webcatalog/webcatalog-legacy#785]
# Bug Report
**Current Behavior:**
After a successful login with Google, both screen went blank,

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/179761/80169210-7136ad80-8617-11ea-9aee-b8442eb327a9.png">

**Expected Behavior:**
Google login window should close, while app starts to render on main screen.

**Steps to Reproduce:**
Use Google login to login in Figma

**Additional Context**
Tried both Electron and Chrome mode.

**Comment by quanglam2807** [comment]
Thanks for reporting this! Please avoid using Google to sign in for now. When authentication is done, it crashes the Figma's website and at the moment, I couldn't figure out a way to debug it.

<img width="912" alt="Screen Shot 2020-04-24 at 4 54 14 PM" src="https://user-images.githubusercontent.com/1548835/80200955-9a723080-864d-11ea-905b-b5478adc5676.png">

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
