### ISSUE TITLE
feature: Navigation in Popup Windows 

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#796]
# Feature Request
**Describe the Feature Request**
Now that the Menu Bar is completely disabled in the pop up window (when you choose "Open in New Window for a link) there is no way to navigate forward and backward from within a popup window.  

**Describe Preferred Solution**
Ideally, the menu bar would be hidden and not disabled, so we could still have navigation.

**Describe Alternatives**

**Additional Context**

**Comment by jonsnelson** [comment]
I just noticed that in any window (main or pop up) there is "back" and "forward" _in the context menu._ That is great!! I think this issue can be closed. 

(There might be a bug with navigation through keyboard short-cut keys. I will report this separately)

**Comment by quanglam2807** [comment]
Let’s keep this open.

The keyboard shortcut at the moment would navigate the main window, not the popup. I’ll fix it ASAP.

**Comment by jonsnelson** [comment]
> Let’s keep this open.
> 
> The keyboard shortcut at the moment would navigate the main window, not the popup. I’ll fix it ASAP.

Just to be clear: the "bug" I'm experiencing is that in a **pop up window**, the usual keyboard shortcut (alt+left arrow/ctrl+{ ) doesn't go to the previous page within that _popup window._  However, the "back" button in the context menu _does_ go to the previous page in the popup window.

**Comment by quanglam2807** [comment]
Resolved with #809.
