### ISSUE TITLE
feature: User menus with custom code

### ISSUE THREAD

**Issue by macta** [webcatalog/webcatalog-legacy#798]
# Feature Request
**Describe the Feature Request**

It would be handy to be able to add some user menu's to the application window - e.g. have a User menu with some assignable menu items that you can assign custom java script too. The java script would be passed the current url (maybe even the dom) and then you could then write some custom operations to launch a new window, or put something on the clipboard - essentially a dirty plugin system for app.

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

**Comment by quanglam2807** [comment]
I and @linonetwo are working on enhance the JS injection feature. We'll try to develop a set of APIs so users can extend the functionalities of the app so stay tuned!

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
