### ISSUE TITLE
Dock icon launches Chrome instead of the app if all windows are closed

### ISSUE THREAD

**Issue by Lukas-Sturm** [webcatalog/webcatalog-legacy#8]
After I close an app for example Youtube, the Icon remains in the Dock.
If I then click on that Icon to open the App again, it just opens Chrome and not Youtube:
![screen](https://user-images.githubusercontent.com/18621002/36820764-d79dac10-1cef-11e8-8cde-ff51152bedcd.png)
Opening the app from the Drawer works fine.

**Comment by Lukas-Sturm** [comment]
I am using High Siera 10.13.3
Chrome is a completely fresh install, same goes for WebCatalog

**Comment by Lukas-Sturm** [comment]
Might have something to do with how osx keeps applications loaded even if you close the window, but I dont realy know much about how that works.

**Comment by quanglam2807** [comment]
@Lucarus I'm sure if there's a way to fix this. But temporarily, you can just right click on the dock icon to quit the app completely.

**Comment by Lukas-Sturm** [comment]
@quanglam2807 ah right (not realy used to working on mac ^^) just so its on your watch. Would be convinient to be able to reopen it. thx

**Comment by madeleineostoja** [comment]
Just chiming in to say I can repro this too - after closing all windows of an app reopening it (from dock or otherwise) launches a Chrome session rather than the app

Webcatalog 1.3.1
Chrome 65
MacOS 10.13.3

**Comment by quanglam2807** [comment]
@seaneking Let's wait for Juli :)

**Comment by collet** [comment]
@seaneking @quanglam2807 Using Juli inside WebCatalog 12.1.0, the reopening is working fine (tested with google calendar app, which is reopening chromium if using it as engine)
