### ISSUE TITLE
Custom User Agent per app

### ISSUE THREAD

**Issue by MichaelTunnell** [webcatalog/webcatalog-legacy#80]
I would really like the ability to set custom User Agents for the webapps. It doesn't have to be during creation but if editing the webapp were possible that would be great.

Example Use-case:

Instagram allows for you to upload from a web-browser but they restrict that option to "Mobile Browsers". If you can add a custom user agent to the Instagram webapp then a mobile browser user agent could be used instead which would make it possible to use Instagram as a desktop app.

This could also be applied to a lot of other stuff.

**Comment by quanglam2807** [comment]
@MichaelTunnell Actually, Juli supports this feature. Have you tried it?

**Comment by gingerbeardman** [comment]
How can I do this? 

What's Juli?

I want to default to showing the mobile version of a website. Thanks!

I workaround it in Chromeless using an Extension. But I can't do that in WebCatalog.
