### ISSUE TITLE
bug: reinstalling app reuses old icon from last installation

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#802]
Also, related to icon. I deleted the app and recreated the app with a new icon. The new icon shows in installed apps but it shows the old icon in mac launcher and, when the app runs, it shows the old icon in the dock.

_Originally posted by @4yourithing in https://github.com/atomery/webcatalog/issues/572#issuecomment-619426474_

**Comment by quanglam2807** [comment]
Thanks for reporting, @4yourithing! I'll try to fix this.

**Comment by quanglam2807** [comment]
I seems like Launchpad/Dock doesn't update the icon in its database correctly. When this bug occurs, would you mind checking if the icon file `AppName.app/Contents/Resources/electron.icns` is updated?

**Comment by marcusquinn** [comment]
This seems to be fixed for me now - anyone else?

**Comment by quanglam2807** [comment]
Since nobody else has reported this bug, I'll assume this bug is fixed and close this issue.
