### ISSUE TITLE
bug: left sidebar showing seems to stop mouseover and clicks for a width to the left of the page for that same width

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#812]
# Bug Report
Left sidebar showing seems to stop mouseover and clicks for a width to the left of the page for that same width

**Expected Behaviour:**

**Steps to Reproduce:**
The bug goes away after hiding and showing the sidebar, not sure how else to reproduce. Restarting the app seems to create the bug again. I suspect something in the order of the wrapper and the website loading that confuses where the sidebar is or the sidebar has a higher z-index, who knows?

**Comment by quanglam2807** [comment]
Thank you for reporting! I couldn't reproduce the bug on my Mac. Would you mind sharing some more information?

**Comment by marcusquinn** [comment]
Here's an example, if you rollover the image thumbnails, the page doesn't recognise the rollover but if you hide and show the sidebar it then does. If you quit and restart the browser app the issue is present again. Updated with the latest version and the issue is still present:

![image](https://user-images.githubusercontent.com/6428977/80968158-621ddf80-8e0f-11ea-8c6a-f8d82fc002e6.png)

**Comment by quanglam2807** [comment]
Thank you for the additional info! I managed to reproduce the bug. It actually doesn't affect the top part (blue highlight). I'll see what I can do to fix this.

<img width="912" alt="Screen Shot 2020-05-04 at 10 38 47 PM" src="https://user-images.githubusercontent.com/1548835/80984752-789c5900-8e58-11ea-9cf1-bc7dc06855c3.png">

**Comment by marcusquinn** [comment]
Good work! I can confirm fixed - tricky one - well done!!
