### ISSUE TITLE
bug: v20.12.0 doesn't open

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#817]
# Bug Report
**Current Behavior:**
Updated to v20.12.0, but main Webcatalog window doesn't open. I get a Javascript error. 
(Running Windows 10)
See attached:
![java](https://user-images.githubusercontent.com/34404707/80953570-79a39b00-8e04-11ea-8daa-11921da6781b.jpg)

**Expected Behavior:**

**Steps to Reproduce:**

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for reporting! I'm working on a fix :)
