### ISSUE TITLE
bug: Check for Updates... "Failed to check for updates. Please check your Internet connection."

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#844]
# Bug Report
**Specifications:**
- App Version: Version v20.14.0
- OS (macOS, Windows, Linux): Mac

**Description:**
Check for Updates... "Failed to check for updates. Please check your Internet connection."

**Steps to Reproduce:**
Check for Updates...

**Additional Context**
Internet is definitely connected. Reinstalled using Brew, issue remains.

**Comment by quanglam2807** [comment]
Thank you for reporting! This happened because I was releasing a new version and the tag was pushed first but the binaries are not. I'll see what I can do to eliminate this scenario in the future.
