### ISSUE TITLE
bug: "Zoom In" in Google Docs Pop Ups

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#848]
# Bug Report
**Specifications:**
- App Version: v20.15.1 
- OS (macOS, Windows, Linux): Windows 10

**Description:**

A Google Doc/Sheets pop up window (opened from any app, not the Google Doc app) doesn't have the usual Zoom in function. 

**Steps to Reproduce:**

Open a link to any Google Doc/Sheets file from within any app, and the usual shortcut (Ctrl+/-) does nothing to adjust the Zoom/View. There is no context menu either to help.

Sample link to try: https://docs.google.com/document/d/1DYda2fOLzvDbcXvl7OHbJUiJ86Xmwl2A0cSlppp9oio/edit?usp=sharing

**Additional Context**

**Comment by quanglam2807** [comment]
Thanks for reporting. It's fixed with https://github.com/atomery/juli/pull/4

**Comment by jonsnelson** [comment]
> Thanks for reporting. It's fixed with [atomery/juli#4](https://github.com/atomery/juli/pull/4)

Great, thank you!!!
