### ISSUE TITLE
feature: support for URIs to open links in local app

### ISSUE THREAD

**Issue by markmartian** [webcatalog/webcatalog-legacy#862]
# Feature Request
**Specifications:**
- App Version: v21.1.0
- OS (macOS, Windows, Linux): macOS

**Description:**
It would be great to have a URI built into each WebCatalog app such that a user can edit a URL so it opens in the local app instead of in their default web browser.

**Additional Context**
For example, the "Things" app on macOS supports a unique scheme they built that starts with `things:///` (though I've seen other apps simply use 2 slashes).

If I wanted to open a link in the local Trello app (from WebCatalog), it would be nice to be able to specify a URI such as: `wctrello://{URL}` where `{URL}` is the URL to my board, for example.

Things documents more of their protocol here: https://culturedcode.com/things/support/articles/2803573/

**Comment by quanglam2807** [comment]
Thank you for the feedback! This is a great feature request. Actually, I'm working on a new app which does this. It will work with all browsers and any web links (http, https and mailto) and let you open the link in your preferred app. A beta version will probably be available sometime in July or August. 

One question: For Trello, it makes sense for me to have this feature (to point trello.com link to the official app). But for Things, it is a native-only app so I don't think they would have web links at all? So Things links would open in the Things app by default? Am I correct?

**Comment by markmartian** [comment]
Hi Quang,

That’s great to hear! Looking forward to your new app.

Regarding your question:

• For Trello, where you have a web app and WebCatalog app, it would be nice if it first checks if the user has the WebCatalog app installed, and if not then it opens in the web browser.
• For Things, you are correct that it has no web app. Their links therefore don’t have an http scheme so they won’t work if the user doesn’t have Things installed. They look like: things:///show?id={GUID} where {GUID} is a long unique link to the item/list/project.

Hope this helps!

Mark

**Comment by quanglam2807** [comment]
Thank you for the clarification, Mark! So definitely, the upcoming app will support official Trello app. But is there anything I can do to improve Things URIs experience?

**Comment by linonetwo** [comment]
I think this is what I wished in the https://github.com/atomery/webcatalog/issues/658

**Comment by markmartian** [comment]
No problem Quang! I was just using Things as an example of an app that itself supports URIs. It also happens to be an app where I place URLs to other desktop apps fairly often, so I’d like to paste a Trello URI within a To-Do item and have it open in the Trello WebCatalog app.

Thanks for your work on these apps!
Mark

**Comment by quanglam2807** [comment]
Thank you very much for clarifying, @markmartian. I'll let you know when the app is available.

**Comment by quanglam2807** [comment]
@markmartian Early version of the app is now available: https://switchbarapp.com/. It's very basic and the performance is not great but I promise it'll get better over time. Feel free to contact me about the app directly through email: quang.lam@atomery.com

**Comment by linonetwo** [comment]
Interesting App, I would give it a try in my work computer.

**Comment by markmartian** [comment]
Nice! Thanks for the update Quang, will give it a go.
