### ISSUE TITLE
bug: Transparent title bar blocks clicking and sometimes gets fullscreen

### ISSUE THREAD

**Issue by linonetwo** [webcatalog/webcatalog-legacy#870]
# Bug Report
**Specifications:**
- Version v8.17.0. Powered by WebCatalog.
- Electron Version: 8.3.0
- Node Version: 12.13.0
- Chromium Version: 80.0.3987.165
- OS (macOS, Windows, Linux): MacOS 10.15.5

**Description:**
When these options are off, we get a transparent title bar. But it will block the clicking.

<img width="977" alt="Screen Shot 2020-06-04 at 10 02 38 AM" src="https://user-images.githubusercontent.com/3746270/83706615-878a4d00-a64a-11ea-9c61-ea201f5c2681.png">

Notion have a transparent title bar too, but it will normally let mouse event pass through, and if user is dragging, it let window move.

<img width="534" alt="Screen Shot 2020-06-04 at 10 01 40 AM" src="https://user-images.githubusercontent.com/3746270/83706553-63c70700-a64a-11ea-97a1-82450f02cff6.png">

And sometimes, the area of titlebar gets fullscreen, making it impossible to click anything in the app, this only happened in the first startup of "start-on-login" app with a transparent title bar, so probably hard to reproduce. I have record a video for its effect:

![Screen-Recording-2020-06-04-at-9](https://user-images.githubusercontent.com/3746270/83707134-d7b5df00-a64b-11ea-8572-570f5ed8a15d.gif)

**Steps to Reproduce:**
Just close all options in the "General" option group, and try an element on the top, for example google calendar button:

<img width="345" alt="Screen Shot 2020-06-04 at 10 13 37 AM" src="https://user-images.githubusercontent.com/3746270/83707217-0fbd2200-a64c-11ea-9f44-cb076ccb7b1d.png">

**Additional Context**
I'm doing my final project, which is about making a CPU in Virtuoso IC design system...After that I think I may have more time helping to fix this.

**Comment by linonetwo** [comment]
I can see it seems used to be both clickable and draggable, but you think it is a bug?
![Screen Shot 2020-06-04 at 10 27 22 AM](https://user-images.githubusercontent.com/3746270/83708127-13ea3f00-a64e-11ea-99f9-dd2d15f6cb24.png)

**Comment by quanglam2807** [comment]
Thank you for reporting! It didn't seem to work for me before and for other people as well: https://github.com/electron/electron/issues/21621#issuecomment-605394949

 You can refer to these issues:
https://github.com/atomery/webcatalog/issues/204
https://github.com/atomery/webcatalog/issues/624

I had the same concern that it would block users from clicking the buttons on top but I decided to go ahead with the change as the option is not enabled by default. You can check the discussion at #204 and #624. Is there a way to fix this? I honestly don't know how to workaround this issue.

**Comment by linonetwo** [comment]
I tried

```js
if ((window.process.platform === 'darwin' || window.mode === 'menubar') && !navigationBar && !titleBar) {
    console.log('ccc');
    return (
      <div
        className={classNames(classes.root, sidebar && classes.rootWithSidebar)}
        onClick={() => { console.log('aaa'); }}
        onDoubleClick={() => {
          console.log('aaabbb')
```
In fake-titlebar, seems this div is not receiving any mouse event? Even without `WebkitAppRegion: 'drag',`.

Or you disabled console.log? Seems 'ccc' is not logged out too.

**Comment by linonetwo** [comment]
I still can't understand why sometimes draggable area gets fullscreen.
This area is not selectable by developer-tool, otherwise, I can figure out what happened on the first auto open at startup.

And seems applying `-webkit-app-region: drag;` to element inside the website can't make it draggable, otherwise I can make my own draggable bar...

**Comment by linonetwo** [comment]
The true reason is that the BrowserView becomes draggable sometimes. I try to reduce its height by 100px, and the draggable region reduces 100px too.

And I tried some fixes, finally this fix works (see the link above).

**Comment by linonetwo** [comment]
https://github.com/atomery/juli/pull/88
