### ISSUE TITLE
bug: Outlook system notification doesn't work

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#874]
> Notifications stopped working in the Outlook app. I have Desktop notifications turned on both in the app and the web client. Kevin

**Comment by owenshill** [comment]
Same here. Hopefully an easy fix! Subscribing.

**Comment by quanglam2807** [comment]
So this is what happens:
<img width="403" alt="Screen Shot 2020-07-03 at 10 50 45 AM" src="https://user-images.githubusercontent.com/1548835/86430219-e57a8500-bd1b-11ea-9427-ad1c735da039.png">

Microsoft decides to use its in-house notification panels when Outlook is open and to only use standard HTML5 Notifications which WebCatalog relies on in other cases. Since they're not standard practice, at the moment, it's unlikely that WebCatalog will be able to support notifications for outlook.com. 

I'll try my best to find a workaround for this issue. Still, the best hope is to raise this issue to Microsoft directly: https://outlook.uservoice.com/forums/601444--the-new-outlook-com and wait for them to adjust this behavior.

**Comment by quanglam2807** [comment]
Btw, notifications actually still show up but are shown in the Outlook app, not in system notifications.

**Comment by dariodjuric** [comment]
By the way, Ferdi (which is similar to this app) has managed to find a workaround for this. I think they parse the page and show a notification when they detect a new email.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
