### ISSUE TITLE
bug: The Windows Menu misses Maximize and duplicates Minimize

### ISSUE THREAD

**Issue by leancode** [webcatalog/webcatalog-legacy#882]
# Bug Report
**Specifications:**
- App Version: 21.1.0
- OS (macOS, Windows, Linux): Linux version as AppImage on Ubuntu 20.0.4

**Description:**
The apps created by WebCatalog are missing the Maximize menu option in the Windows menu. The items in the menu are: Minimize Ctrl-M, Close Ctrl-W, Minimize Ctrl-M, Zoom, Bring All to Front. 

As you can see Minimize is duplicated and Maximize is missing.

**Steps to Reproduce:**
Its as easy as create any app, the all have the same flaw.

**Additional Context**
![Screenshot from 2020-06-15 09-55-22](https://user-images.githubusercontent.com/611460/84635641-c85c4e80-aef3-11ea-8313-216074f384ef.png)

**Comment by quanglam2807** [comment]
Thank you for reporting this bug, @leancode. I'm not sure if I understand it correctly, but "Zoom" is equivalent to "Maximize". If you mean something else, please let me know. I'll remove the duplicated "Minimize" menu item in the next update.

**Comment by quanglam2807** [comment]
I just did a test. It seems like "Zoom" only works on Mac. I'll work to fix this ASAP.

**Comment by leancode** [comment]
Perfect, thank you.
