### ISSUE TITLE
feature: auto-refresh interval setting

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#891]
It would be great to be able to set and auto-refresh interval for inactive browsers to help stay logged-in to annoying apps that have login timeouts.

I suggest increments like 1, 4, 9, 14, 29, 59, 119, 359 etc so that you can stay inside the typical timeout intervals.

This would be off by default to respect website security - but I would set it on for certain apps (Xero as an example) because it is a royal PITA having to login so many times a day.

Also, a good and simpler interim solution to the needs for https://github.com/atomery/webcatalog/issues/678

**Comment by quanglam2807** [comment]
Thank you for the suggestion, @marcusquinn. Would you be able to use JS injection to resolve this?

**Comment by quanglam2807** [comment]
I guess this small script with JS Injection would do the trick. 
```js
setTimeout(function() {
  location.reload();
}, 30000);
```

**Comment by marcusquinn** [comment]
Thanks, that works - but I have 54 WebApps, so quite a time-cost to set or update in all of them.

Also, it should only refresh when the browser has been inactive for say 3 minutes to avoid interruption to active work.

Ideal would be a global default and a app-by-app override.

**Comment by quanglam2807** [comment]
Thank you, @marcusquinn! I'll try to add this feature as an option soon. For now, you can use this script:
```js
let t;
window.addEventListener('focus', () => {
  clearTimeout(t);
})

window.addEventListener('blur', () => {
  t = setTimeout(function() {
    location.reload();
  }, 30000);
});
```


Your answer also reminds me to add a way for advanced users to set global default configurations for all Electron-based apps.

**Comment by marcusquinn** [comment]
Hacky workaround for regular browsers using this browser extension, which has some nice settings and you might be able to include in the Electron browser:

https://chrome.google.com/webstore/detail/tab-reloader-page-auto-re/dejobinhdiimklegodgbmbifijpppopn

https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/?src=search

https://addons.opera.com/en/extensions/details/tab-reloader/

I posted more on the subject in the Xero forum:

https://community.xero.com/business/discussion/64131#answer118809192

**Comment by quanglam2807** [comment]
Thank you, Marcus! This is now in the roadmap and will be added in 1-2 weeks.

**Comment by marcusquinn** [comment]
Nice, thanks for adding this. However, is there any way to make it so that it only happens if the window is inactive?

I suppose one way would be having a hidden duplicate/tab of a page that is refreshing so that the page being used doesn't refresh while you're using it.

Once solved I can point everyone on this Xero thread to WebCatalog:

https://community.xero.com/business/discussion/64131

**Comment by quanglam2807** [comment]
@marcusquinn Thanks for asking! Yes, it is definitely possible. ETA: a few days to one week. I still need to work on some other priorities first.
