### ISSUE TITLE
bug: Discord Context Menu doesn't show on all elements

### ISSUE THREAD

**Issue by asportnoy** [webcatalog/webcatalog-legacy#892]
# Bug Report
**Specifications:**
- App Version: v8.17.0
- OS (macOS, Windows, Linux): macOS

**Description:**

On the discord.com/app website, I am able to right click on any element and get a context menu. On the webcatalog version, right clicking on usernames, channels, and servers works, but not right clicking on messages

**Steps to Reproduce:**

1. Add the Discord app (https://discord.com/app) and log in
2a. Right click on a server on the list (very left bar). It should show a context menu
2b. Right click on a channel on the list (bar to the right of the server bar). It should show a context menu
2c. Right click on a username in the chat or on the member list (very right bar). It should show a contextmenu.
2d. **Right click on a message. It will show the native electron context menu, not the discord one.**

**Additional Context**

No problems in console.

**Comment by quanglam2807** [comment]
Thank you for reporting this! I'll try to fix this ASAP.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
