### ISSUE TITLE
feature: Add WebKit as a browser engine option

### ISSUE THREAD

**Issue by mariobrostech** [webcatalog/webcatalog-legacy#903]
# Feature Request

**Specifications:**
- App Version: 22.2.1
- OS (macOS, Windows, Linux): macOS

**Description:**
Please consider adding the option to create WebKit-based apps, which is the web framework used in Apple's Safari. Similar apps, like [Flotato](https://www.flotato.com) use WebKit, which results in much more responsive apps (at least on my admittedly under-powered hardware). I've also noticed that Flotato can hook into native keyboard functions for audio control with a music website, like in Spotify. I'm not sure if this can already be done with Electron-based apps, but WebKit would definitely be a more lightweight alternative.

Thanks in advance!

**Comment by marcusquinn** [comment]
The Mac Play/Pause/Skip keys work for me with Electron & Spotify/Souncloud/YouTube.

Otherwise this request may be useful for developer browser testing.

**Comment by mariobrostech** [comment]
@marcusquinn Yeah, I'd also like this as a lightweight alternative to something like Electron or Firefox while still having a moderate amount of privacy. WebKit, as I said, runs much faster on my machine compared to Electron, Chrome, and Firefox. It'd also make a useful case for developers, as you said. Hopefully the team considers adding this!

**Comment by quanglam2807** [comment]
Thank you for this suggestion. This is definitely possible. But as there're many other planned improvements, you'd probably have to wait for at least a few months before this is implemented.

**Comment by mariobrostech** [comment]
@quanglam2807 Thank you! Even if I have to wait a few months, it would still be nice to have the option. I just want some kind of guarantee that this will be implemented at some point before I make my purchase.

**Comment by marcusquinn** [comment]
The original Webkit webapps were somewhat pioneered by FluidApps. Seems a bit dated now bit it might work in the meantime if only for experimentation while you wait: https://fluidapp.com

**Comment by mariobrostech** [comment]
@marcusquinn Thanks for the tip! I've actually been using it for a little bit, but I'd definitely prefer something more polished to do the job, and that's why I opened this issue. I'll be happy to pay as soon as it's implemented!

**Comment by marcusquinn** [comment]
> @marcusquinn Thanks for the tip! I've actually been using it for a little bit, but I'd definitely prefer something more polished to do the job, and that's why I opened this issue. I'll be happy to pay as soon as it's implemented!

Also a (sort-of competitive) option: https://www.bzgapps.com/unite although I stopped using Chrome & Webkit apps since finding Electron tends to be faster and lighter on my setup. YMMMV. Just good to see this whole space evolving and growing in awareness because WebApps are definitely better than single-browser multi-tab chaos!
