### ISSUE TITLE
bug: Dark Mode stopped working in the latest update

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#904]
# Bug Report
**Specifications:**
- App Version: Latest
- OS (macOS, Windows, Linux): macOS 10.14.6

**Description:**
Dark Mode stopped working in the latest update. Opening prefs and switching it to off and on again temporarily fixes but then it happens each time the webapp is quit and restarted.

WhatsApp & Messenger are reproducible

**Comment by quanglam2807** [comment]
Thank you for reporting this, Marcus. I'll try to fix this ASAP.

I couldn't reproduce the bug on my Mac. Is it possible for you to record a video of how to reproduce it? If it's private, you can email me directly. quang.lam@atomery.com

**Comment by marcusquinn** [comment]
Seems to be OK now - thanks!
