### ISSUE TITLE
bug: Count bage does not show in Yandex Mail (Electron engine)

### ISSUE THREAD

**Issue by restructor1** [webcatalog/webcatalog-legacy#908]
![3333](https://user-images.githubusercontent.com/63119504/87612156-74bb6b80-c712-11ea-8bd3-8ce258ec05c5.jpg)

# Bug Report

**Specifications:**
- App Version: 22.3.0.0
- OS Windows 10 last update (previous version has same bug)

**Description:**
Count bage does not show on icon in task bar with Browser engine Electron (Chrome also). 
NO windows notifications are also.

P.S Blue arrow on the pic is showing the bage in another same app like webcatalog.

**Steps to Reproduce:**
Get the email via yandex.com (or .ru)

**Additional Context**
No

**Comment by quanglam2807** [comment]
Thank you for reporting the bug. I'll fix it ASAP.
