### ISSUE TITLE
bug: app (Electron engine) prevents Linux from switching workspaces

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#913]
I'm using two workspaces on my linux machine (cinnamon desktop). When I open any of the WebCatalog apps at desktop one and try to switch to desktop two the screen blinks short and switches back to desktop one. Additionally, the App is in the focus all the time and minimizing impossible.
Not sure how to describe better

_Originally posted by @zyexal in https://github.com/atomery/webcatalog/issues/905#issuecomment-659505552_

**Comment by quanglam2807** [comment]
@zyexal This bug sounds very critical. I'll try to fix it ASAP.
 
At the moment, there's no simple way to downgrade Electron-based apps to earlier version. But I don't think this bug is caused by recent updates as even though these updates introduce many changes, they don't touch the core logic of the app. 

It'll take me some time to resolve this as I'd need to set up Cinnamon on my machine.

**Comment by zyexal** [comment]
I was updating regularly. And it came with the last one I did. Are there any logs which I could provide for you?

**Comment by quanglam2807** [comment]
When you switch between Cinnamon workspaces, are the apps in fullscreen mode or are they exiting fullscreen mode by any chance?

**Comment by zyexal** [comment]
I'm not sure I got it. 
I can not switch the workspace with any open App anymore. That's regardless of having them in full screen or partially screened. They also do not change their state when I try to change the workspace. It looks like the force focus on themself all the time.

**Comment by quanglam2807** [comment]
Thank you! The question is mostly to help me investigating what causes the bug. I'll try to fix this ASAP.

**Comment by quanglam2807** [comment]
@zyexal I've fixed the bug in the latest version. Please let me know if it works.

**Comment by zyexal** [comment]
> @zyexal I've fixed the bug in the latest version. Please let me know if it works.

Works beautifully, thanks a lot. Your support is awesome and I will continue to recommend WebCatalog.
