### ISSUE TITLE
feature: "Pin to Task bar" with "Attach to task bar".

### ISSUE THREAD

**Issue by restructor1** [webcatalog/webcatalog-legacy#914]
![111](https://user-images.githubusercontent.com/63119504/87775400-b4777580-c82e-11ea-9d9c-5aeaf6f29270.jpg)

# Feature Request
**Specifications:**
- App Version: Last
- OS: Windows 10 last

**Description:**
When i turn on "Attach to task bar" i can not open the app from pinned icon. It is about all apps. It whould be better if it may hide to tray but may be opened from pinned icon also! 

**Additional Context**

**Comment by restructor1** [comment]
Hi. It has not been implemented in 32.1.0?

**Comment by quanglam2807** [comment]
Preferences > General > Show tray icon

**Comment by restructor1** [comment]
If i turn on Show tra icon only, pin icon and then close app, the app does not run in background after close. 
When i turn on run in background, then i can not open from from pined icon.

![1](https://user-images.githubusercontent.com/63119504/118133317-5cd37780-b409-11eb-98e0-5d1b2f6065a6.jpg)
![2](https://user-images.githubusercontent.com/63119504/118133320-5d6c0e00-b409-11eb-95a6-071bc77a4e16.jpg)
![3](https://user-images.githubusercontent.com/63119504/118133323-5e04a480-b409-11eb-8a19-ecd3f8c808ba.jpg)

**Comment by quanglam2807** [comment]
Please create a new issue for the bug, @restructor1

**Comment by restructor1** [comment]
The task is for example, run Whatsapp in background after closing (X) app and possibility to open it from task bar. 

![4](https://user-images.githubusercontent.com/63119504/118133882-fd299c00-b409-11eb-9487-18ec520df5ab.jpg)
