### ISSUE TITLE
bug: The cursor doesn't seem to show in input fields

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#915]
# Bug Report
**Specifications:**
- App Version: Latest
- OS (macOS, Windows, Linux): macOS
- Dark Mode everywhere

**Description:**
I don't see the cursor.

**Steps to Reproduce:**
Try Discord chat in Dark Mode, don't see the cursor in the text input boxes.

**Comment by marcusquinn** [comment]
Seems to be fixed now - not sure if there was a recent update but I can check back again in a few days to confirm again or you can close and I'll ping this ticket again if I see it happen again

**Comment by marcusquinn** [comment]
Still good - probably safe to close this now - thanks!

**Comment by quanglam2807** [comment]
Awesome! Thank you
