### ISSUE TITLE
bug: Electron-based app for Google Drive - "paste without formatting" doesn't work

### ISSUE THREAD

**Issue by hellostacy** [webcatalog/webcatalog-legacy#916]
**Bug Report**
Specifications: **Electron-based app for Google Drive - _paste without formatting_ doesn't work**

App Version: **Version v22.3.0**
OS (macOS, Windows, Linux): **macOS Catalina 10.15.5**
Description: 

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/63239199/87867213-282e9500-c98b-11ea-9742-28ce6eba5584.png)
![image](https://user-images.githubusercontent.com/63239199/87867319-14cff980-c98c-11ea-8590-5a47d1839ebd.png)
![image](https://user-images.githubusercontent.com/63239199/87867370-7b551780-c98c-11ea-9fce-73a61ad43ca1.png)
![image](https://user-images.githubusercontent.com/63239199/87867408-c8d18480-c98c-11ea-849a-4281249cd7ed.png)

Additional Context

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
