### ISSUE TITLE
feature: keep notification service running when the app is closed

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#942]
> Is there any way to keep the notification service on even if the app is closed and i want this service always on from the machine startup. Pritam

**Comment by restructor1** [comment]
It is very necessary enhancement. The apps should work in background by selecting switch on/off.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
