### ISSUE TITLE
feature: Sync apps

### ISSUE THREAD

**Issue by restructor1** [webcatalog/webcatalog-legacy#948]
# Feature Request
**Specifications:**
- App Version: All
- OS (macOS, Windows, Linux): Any

**Description:**
Create account, and sync apps bettwen some PC.

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for the suggestion! I'll consider adding this feature in the future but at the moment, I'm sorry as it's not the top priority.

**Comment by quanglam2807** [comment]
We're working on this! :D

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
