### ISSUE TITLE
feature: add ability to create apps for other platforms

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#952]
> SHORT Is there a way to download mac and linux electron versions of webapp using windows webcatalog LONG Hi, I'm in love with your app. I have bunch of web apps i really love and would like to keep them in my harddrive archive for future offline purposes. Currently I'm only able to download windows electron webapps. Is there a way to download mac and linux electron versions of webapp using windows webcatalog, so that if i use mac os/ linux in the future, i would be able to use the webapps offline (in case the webapps get discontinued and i cant use webcatalog to install them at that time) Ahmed

**Comment by ghost** [comment]
Hi, https://youtu.be/kN1Czs0m1SU?t=2957
Is there a way you could incorporate this in your app which will allow the app to install versions for windows, mac and linux without using that corresponding OS?

**Comment by quanglam2807** [comment]
@AhmedThahir I'm sorry that while it's possible, as WebCatalog is a consumer app (not designed as an app creator for developers), I have to decline the feature request. You can learn from the video, check out https://www.electron.build/ and play with WebCatalog's source code at https://github.com/atomery/juli to accomplish what're looking for.

Still, FYI, Atomery is currently developed new product built for developers which might be a good suite for your goal. So stay tuned!

**Comment by quanglam2807** [comment]
@AhmedThahir I'll write a blog post about this soon. 👍  Hope that would work for you.
