### ISSUE TITLE
bug: error when clicking link in TT-RSS : {"error":{"code":6,"message":"Request not authorized."}}

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#955]
# Bug Report
**Specifications:**
- App Version: 23.1.1.0
- OS (macOS, Windows, Linux): macOS

**Description:**
When clicking on an external link within the TT-RSS app ([TT-RSS demo link](https://demos5.softaculous.com/Tiny_Tiny_RSS68nek3tclp/)) I get the following error code in a pop-up screen:

`{"error":{"code":6,"message":"Request not authorized."}}`

**Steps to Reproduce:**
Clicking on a headline post link in TT-RSS.

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for reporting! The bug fix will be available in the next update.
