### ISSUE TITLE
feature: Group workspaces

### ISSUE THREAD

**Issue by nblackburn** [webcatalog/webcatalog-legacy#958]
# Feature Request
**Describe the Feature Request**
Add the ability to group apps together into collections. It might be that you have a work one and a home one that you want to keep seperate.

**Describe Preferred Solution**
Drag one app over another to start a group.

**Describe Alternatives**
Have an additional menu system for managing collections.

**Comment by quanglam2807** [comment]
Same as https://github.com/webcatalog/webcatalog-app/issues/960
