### ISSUE TITLE
feature: Add Quick Switch

### ISSUE THREAD

**Issue by nblackburn** [webcatalog/webcatalog-legacy#959]
# Feature Request
**Describe the Feature Request**
There is a problem at the moment in that if you have more than 9 apps then you will only be able to use shortcuts for the first 9. Instead i was wondering if replacing a jump to menu triggered by the usual "Ctrl + P" which allows you to search and switch to another app.

**Describe Preferred Solution**
A floating menu which is triggered by "Ctrl + P" which brings up a search field and the active apps allowing you to filter down and switch to another app.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
