### ISSUE TITLE
feature: Add profile instance support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#960]
# Feature Request
**Describe the Feature Request**

@nblackburn My idea is adding the ability to merge instances of the same app under a single icon for that instance (saving space and creating a logic group of the same app).  The way this would be managed is via a enchanced context menu when right clicking on an instance which will give you the usual options for editing and deleting but also new ones for creating additional and switching instances.

@quanglam2807 Thank you very much for all of your ideas! For this idea, is it similar to Google Chrome’s profile feature? Like you can have independent profile for each window? If so, I’d love to add the feature but it won’t happen anytime soon as it’d require many changes to the architect of the app.

@nblackburn Essentially what i was imagining was being able to group multiple workspaces of the same type together which will display the icon of the active (if it was modified from the default). You could also right click on the active instance to bring up the usual options (edit, delete) but also kill and switch to other instances.

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

Ref: https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DDesktop&hl=en

**Comment by quanglam2807** [comment]
@nblackburn Because it's now possible create multiple multisite apps, we can just that to organize apps into context, profile (Work, Life, School) so I think this feature is no longer necessary. If you still think it is, please let me know.

**Comment by quanglam2807** [comment]
Same as https://github.com/webcatalog/webcatalog-app/issues/960

**Comment by nblackburn** [comment]
@quanglam2807 The recent updates appear to address this indirectly so am happy for this to be closed.
