### ISSUE TITLE
bug: help menu options lead to broken urls

### ISSUE THREAD

**Issue by rotu** [webcatalog/webcatalog-legacy#971]
# Bug Report
**Specifications:**
- App Version:
- OS (macOS, Windows, Linux): Linux

**Description:**
Help menu options are broken.
![Screenshot from 2020-08-11 13-19-39](https://user-images.githubusercontent.com/119948/89933962-7c691580-dbd5-11ea-878d-934e46e9b1aa.png)

**Steps to Reproduce:**
Use the menu Help -> WebCatalog Website or Help -> WebCatalog Support

These bring me to `https://atomery.com/webcataog`, `https://atomery.com/webcataog/support` respectively, both of which are 404 pages

Should be `https://atomery.com/webcatalog/` and `https://atomery.com/support/webcatalog`

**Comment by quanglam2807** [comment]
Thank you for reporting this.

**Comment by rotu** [comment]
Thanks for getting to it so fast! One more missed link in the main app window Help -> WebCatalog Support
