### ISSUE TITLE
feature: App Update Alerts attached to the window to be easier to dismiss

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#973]
At the moment I get App Update alerts behind App windows. This is difficult to find and dismiss.

I suggest if possible to attach update alerts to the window to be show in front to be easier to dismiss.

I'm not even sure they are needed at-all given that Webcatalog itself shows updates available on the Install tab.

Right now the user-experience for update alerts is more disruptive to workflow than helpful. Somehow I'm sure there's a way to make them either easier to dismiss or less obtrusive.

**Comment by quanglam2807** [comment]
Thank you for the feedback @marcusquinn. Please see https://github.com/atomery/webcatalog/issues/975
