### ISSUE TITLE
bug: right-click context menu missing/can't choose to open links in popup window 

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#992]
# Bug Report
**Specifications:**
- App Version:  Version v24.1.0
- OS (macOS, Windows, Linux): Windows 10

**Description:**
Previously I could right-click on a link within any app and choose to open in a pop up window or in the browser.  Now, right clicking doesn't open the context menu.

**Steps to Reproduce:**
 Right-click (in app/on link) and nothing happens.

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you very much, Jon! It seems like this bug only affects pre-release channel of the app. I'll try to fix it ASAP.

For now, you can go to Preferences page of WebCatalog to switch off "Receive pre-release updates". Still, you won't be able to downgrade updated apps.

**Comment by jonsnelson** [comment]
Thanks for the clarification!!!! As always, you're the best.

**Comment by quanglam2807** [comment]
@jonsnelson Thank you! I'll issue an update for pre-release version soon. You'll need to switch on "Receive pre-release updates" to receive the update.
