### ISSUE TITLE
bug: Dark Reader isn't inverting GMail icons (and possibly others)

### ISSUE THREAD

**Issue by swrobel** [webcatalog/webcatalog-legacy#993]
# Bug Report
**Specifications:**
- App Version: 24.1.0
- OS (macOS, Windows, Linux): macOS 10.15.6

**Description:**
After a long absence, I'm back to using Webcatalog, and I'm impressed with how far it's come. Amazing work, @quanglam2807!

As for the small bug, GMail icons aren't inverted. Here is how they look in Webcatalog:
<img width="153" alt="Screen Shot 2020-08-26 at 9 30 49 PM" src="https://user-images.githubusercontent.com/157270/91384438-7719e680-e7e3-11ea-8a02-3aef3f53f8c2.png">

And Chrome with the Dark Reader extension:
<img width="141" alt="Screen Shot 2020-08-26 at 9 30 57 PM" src="https://user-images.githubusercontent.com/157270/91384446-7f722180-e7e3-11ea-8b1f-f92f405d5cae.png">

**Steps to Reproduce:**
Enable Dark Reader in GMail

**Additional Context**
I see many similar log messages in the Webcatalog developer console:
```
Error: Embedded Dark Reader cannot access a cross-origin resource https://www.gstatic.com/images/icons/material/system/2x/arrow_drop_down_black_20dp.png Overview your URLs and CORS policies or use `DarkReader.setFetchMethod(fetch: (url) => Promise<Response>))`. See if using `DarkReader.setFetchMethod(window.fetch)` before `DarkReader.enable()` works.
    at VM748 darkreader.js:208
    at step (VM748 darkreader.js:70)
    at Object.next (VM748 darkreader.js:51)
    at VM748 darkreader.js:44
    at new Promise (<anonymous>)
    at __awaiter (VM748 darkreader.js:40)
    at throwCORSError (VM748 darkreader.js:206)
    at VM748 darkreader.js:231
    at step (VM748 darkreader.js:70)
    at Object.next (VM748 darkreader.js:51)
```

**Comment by quanglam2807** [comment]
Hi Stefan! It's great to see you back. I hope everything's going well with your startup.

Btw, thank you for the bug report. I'll try to fix this ASAP.
