### ISSUE TITLE
bug: Microsoft Word & Excel Document Links opening externally

### ISSUE THREAD

**Issue by pahansen95** [webcatalog/webcatalog-legacy#996]
# Bug Report
**Specifications:**
- App Version: v24.2.0
- OS macOS: 10.15.6 (19G2021)

**Description:**

In Microsoft Word & Microsoft Excel, when opening documents from `*.sharepoint.com` or `*.live.com` it opens the document in my default web browser outside the Context App (or App). 

Expected behavior is for the Document to open in the Context App's workspace (or App's) window like when creating a new document.

**Steps to Reproduce:**

Create Microsoft Word as an App or a workspace within a Context App. Attempt to open a document whose link is to `*.sharepoint.com` or `*.live.com`.

**Additional Context**

`sharepoint.com` links correspond to a OneDrive Account managed by an organization such as a business or a school. `live.com` links correspond to a personal (Microsoft Managed) OneDrive Account.

Is it feasible or realistic to provide a selection option to either open document (links) in the App's Window or in an external browser? I imagine in some cases (like concurrently editing multiple documents) it makes more sense to open externally so you can tab between them.

**Comment by quanglam2807** [comment]
Thank you for reporting this. I'll try to fix this ASAP.
