### ISSUE TITLE
bug: seems to be very high CPU usage with the latest version

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#998]
# Bug Report
**Specifications:**
- App Version: Latest
- OS (macOS, Windows, Linux): Mac

Version v10.0.0-alpha.5.
Electron Version: 10.1.0
Node Version: 12.16.3
Chromium Version: 85.0.4183.87

CPU is at 90% for Discord, it was for some others but Discord in particular I need all day every day for work.

Have you seen any issues? Any ideas?

**Comment by quanglam2807** [comment]
Thank you for reporting this, Marcus. I'm not sure what causes this but it's probably because of Electron 10. 

For now, you can opt out of the pre-release channel in WebCatalog's preferences page and reinstall Discord to see it fixes the bug. 

Btw, I'll continue to release new features to both stable and prerelease channels. The only major difference is that stable channel uses Electron 9 and prerelease channel uses Electron 10.

**Comment by marcusquinn** [comment]
I might have fixed by deleting and clearing all preferences. Could be a Discord issue. so I don't know that you can do anything other than that - but at least this thread is here if anyone else has a similar issue.

**Comment by quanglam2807** [comment]
Thank you Marcus. Do you use DarkReader with Discord by any chance?

**Comment by marcusquinn** [comment]
> Thank you Marcus. Do you use DarkReader with Discord by any chance?

I use Dark Reader with everything that doesn't have it's own Dark Mode. Discord does, so no need for Dark Reader.

I've gone back to the native Discord app for a bit as I need to get through some other work but will try this again soon and report back.

Thanks, as always, for the swift replies - keep up the good work!

**Comment by quanglam2807** [comment]
Thank you for the information, Marcus! I'm working to refactor the codebase. As features are added, the code has become a bit bloated. Hopefully, with the process, many bugs and problems would be resolved.

**Comment by quanglam2807** [comment]
Is this problem fixed in the latest update, @marcusquinn?

**Comment by marcusquinn** [comment]
> Is this problem fixed in the latest update, @marcusquinn?

I think we're all good now, thank you!
